var util=require("util"),events=require("events"),fs=require("fs"),path=require("path"),Db=require("./leveldb/db").Db,common=require("./common"),System=require("./system").System,log=require("../../log"),addFields=common.addFields,substractFields=common.substractFields,MultipleAsyncWaiter=common.MultipleAsyncWaiter,validateColumnName=common.validateColumnName,ensureOpened=common.ensureOpened,ensureInitialized=common.ensureInitialized,ensureValidIndex=common.ensureValidIndex,raiseInvalidAddOptionError=
common.raiseInvalidAddOptionError,ensureValidAddOption=common.ensureValidAddOption,ensureValidBatchSize=common.ensureValidBatchSize,ifError=common.ifError,ensureValidIncrementAmount=common.ensureValidIncrementAmount,ensureValidArrayArgument=common.ensureValidArrayArgument,errorFilter=common.errorFilter,resultFilter=common.resultFilter,changedEmitter=common.changedEmitter,noop=common.noop,buildSimpleUpdaters=function(a,b,c){a.getCache(errorFilter(c,function(a,f){var d={existing:{},needed:{},all:{}},
g;for(g in b){var h=f.getCollectionInfo(g);h?d.existing[h.name]=b[g]:d.needed[g]=b[g]}addFields(d.all,d.existing);addFields(d.all,d.needed);c(null,d)}))},buildSimpleUpdatersForAll=function(a,b,c){a.getCache(errorFilter(c,function(a,f){var d={existing:{},needed:{},all:{}},g=f.getOrderedCollectionInfos(),h;for(h in g)d.existing[g[h].name]=b;addFields(d.all,d.existing);c(null,d)}))};
function createCollectionInfoForSimpleUpdaters(a,b,c){var e=new MultipleAsyncWaiter(c),f;for(f in b)e.wait(),a.createCollection(f,function(){e.done()});e.done()}var leveldbStrategy={buildUpdaters:buildSimpleUpdaters,buildUpdatersForAll:buildSimpleUpdatersForAll,createCollectionInfoForUpdaters:createCollectionInfoForSimpleUpdaters};
function SharedParameterApiServer(a,b){a=a||{};a.collectionInfo=a.collectionInfo||"__col_info";a.dbName=a.dbName||"Default";a.dbPath=a.dbPath||log.expandPath("%programdata%/Micro Focus/VTS/db/data");this.options=a;this.db=new Db(path.join(a.dbPath,a.dbName),a);this.system=null;this.initialized=this.opened=!1;this.strategy=b||leveldbStrategy}util.inherits(SharedParameterApiServer,events.EventEmitter);
SharedParameterApiServer.prototype.buildUpdaters=function(a,b){this.strategy.buildUpdaters(this.system,a,b)};SharedParameterApiServer.prototype.buildUpdatersForCollumns=function(a,b,c){if(a instanceof Array&&0<a.length){var e={},f;for(f in a){if(ifError(validateColumnName(a[f]),c))return;e[a[f]]=b}this.strategy.buildUpdaters(this.system,e,c)}else this.strategy.buildUpdatersForAll(this.system,b,c)};
SharedParameterApiServer.prototype.createCollectionInfoForUpdaters=function(a,b){this.strategy.createCollectionInfoForUpdaters(this.system,a,b)};function addSameRow(a,b,c){a.system.getCache(function(e,f){var d=0,g;for(g in b)var h=f.getCollectionInfo(g),d=Math.max(h.high-h.low,d);var i=new MultipleAsyncWaiter(c);for(g in b)i.wait(),a.system.updateRecord(g,d+1,b[g],function(){i.done()});i.done()})}
function addStack(a,b,c){var e=new MultipleAsyncWaiter(c),f;for(f in b)e.wait(),a.system.addRecord(f,b[f],function(a){e.done(a,null)});e.done(null,null)}function addStackUnique(a,b,c){var e=new MultipleAsyncWaiter(c),f=0,d;for(d in b)e.wait(),a.system.addUniqueRecord(d,b[d],function(a,b){!a&&b&&++f;e.done(a,f)});e.done(null,f)}
function add(a,b,c,e){a.buildUpdaters(b,errorFilter(e,function(b,d){a.createCollectionInfoForUpdaters(d.needed,errorFilter(e,function(){switch(c){case 0:addSameRow(a,d.all,e);break;case 1:addStack(a,d.all,e);break;case 2:addStackUnique(a,d.all,e);break;default:raiseInvalidAddOptionError(c,e)}}))}))}SharedParameterApiServer.prototype.add=function(a,b,c){ensureInitialized(this,c)&&ensureValidAddOption(b,c)&&add(this,a,b,changedEmitter(this,resultFilter(c)))};
function addStackMultiple(a,b,c){a.buildUpdaters(b[0],errorFilter(c,function(e,f){a.createCollectionInfoForUpdaters(f.needed,errorFilter(c,function(){f=f.all;var e=new MultipleAsyncWaiter(c),g=b.length,h;for(h in f){e.wait();for(var i=[],j,l=0;l<g;++l)j=b[l][h],void 0!=j&&i.push(j);a.system.addRecords(h,i,function(){e.done(null,null)})}e.done(null,null)}))}))}
SharedParameterApiServer.prototype.addStackMultiple=function(a,b){ensureInitialized(this,b)&&ensureValidArrayArgument("objects",a,b)&&(0>=a.length&&b(null,null),addStackMultiple(this,a,resultFilter(b)))};function get(a,b,c,e){a.buildUpdatersForCollumns(b,null,errorFilter(e,function(b,d){var g=new MultipleAsyncWaiter(e),h=d=d.all,i;for(i in d)(function(){g.wait();var b=i;a.system.getRecord(b,c,function(a,c){h[b]=c;g.done(null,h)})})();g.done(null,h)}))}
SharedParameterApiServer.prototype.get=function(a,b,c){ensureValidIndex(b,c)&&ensureInitialized(this,c)&&get(this,a,b,resultFilter(c))};function getMultiple(a,b,c,e,f){a.buildUpdatersForCollumns(b,null,errorFilter(f,function(b,g){var h=new MultipleAsyncWaiter(f),i=[],g=g.all,j;for(j in g)(function(){h.wait();var b=j;a.system.getRecords(b,c,c+e,function(a,c){if(!a&&c)for(var e=c.length,d=0;d<e;++d)i[d]=i[d]||{},i[d][b]=c[d];h.done(null,i)})})();h.done(null,i)}))}
SharedParameterApiServer.prototype.getMultiple=function(a,b,c,e){ensureValidIndex(b,e)&&(ensureValidBatchSize(c,e)&&ensureInitialized(this,e))&&getMultiple(this,a,b,c,resultFilter(e))};function retrieve(a,b,c){a.buildUpdatersForCollumns(b,null,errorFilter(c,function(b,f){var d=f=f.all,g=new MultipleAsyncWaiter(c),h;for(h in f)g.wait(),function(){var b=h;a.system.retrieveRecord(b,function(a,c){a||(d[b]=c);g.done(a,d)})}();g.done(null,d)}))}
SharedParameterApiServer.prototype.retrieve=function(a,b){ensureInitialized(this,b)&&retrieve(this,a,changedEmitter(this,resultFilter(b)))};
function rotate(a,b,c,e){a.buildUpdatersForCollumns(b,null,errorFilter(e,function(b,d){var g=d=d.all,h=new MultipleAsyncWaiter(function(b,d){if(b)e(b,d);else{for(var f in d)d[f]||(d[f]="");add(a,d,c,function(a,b){a?e(a,b):e(null,d)})}}),i;for(i in d)h.wait(),function(){var b=i;a.system.retrieveRecord(b,function(a,c){a||(g[b]=c);h.done(a,g)})}();h.done(null,g)}))}
SharedParameterApiServer.prototype.rotate=function(a,b,c){ensureInitialized(this,c)&&ensureValidAddOption(b,c)&&rotate(this,a,b,changedEmitter(this,resultFilter(c)))};function update(a,b,c,e){a.buildUpdaters(b,errorFilter(e,function(b,d){a.createCollectionInfoForUpdaters(d.needed,errorFilter(e,function(){d=d.all;var g=new MultipleAsyncWaiter(e),h;for(h in d)g.wait(),a.system.updateRecord(h,c,d[h],function(a){g.done(a,null)});g.done(b,null)}))}))}
SharedParameterApiServer.prototype.update=function(a,b,c){ensureValidIndex(b,c)&&ensureInitialized(this,c)&&update(this,a,b,changedEmitter(this,resultFilter(c)))};
function update_ifequals(a,b,c,e,f){a.buildUpdaters(b,errorFilter(f,function(b,g){a.buildUpdaters(c,errorFilter(f,function(b,c){for(var d in c.needed)null!==c.needed[d]&&(delete g.needed[d],delete g.all[d]);a.createCollectionInfoForUpdaters(g.needed,errorFilter(f,function(){g=g.all;c=c.all;var d=new MultipleAsyncWaiter(f),k=0,j;for(j in g)d.wait(),void 0===c[j]?a.system.updateRecord(j,e,g[j],function(a){++k;d.done(a,k)}):a.system.updateRecordIfEquals(j,e,c[j],g[j],function(a,b){k+=b;d.done(a,k)});
d.done(b,k)}))}))}))}SharedParameterApiServer.prototype.update_ifequals=function(a,b,c,e){ensureValidIndex(c,e)&&ensureInitialized(this,e)&&update_ifequals(this,a,b,c,changedEmitter(this,e))};function inc(a,b,c,e,f){a.buildUpdatersForCollumns([b],e,errorFilter(f,function(b,g){a.createCollectionInfoForUpdaters(g.needed,errorFilter(f,function(){g=g.all;var h=new MultipleAsyncWaiter(f),i;for(i in g)h.wait(),a.system.incrementRecord(i,c,e,function(a,b){h.done(a,b)});h.done(b,0)}))}))}
SharedParameterApiServer.prototype.inc=function(a,b,c,e){ensureValidIndex(b,e)&&(ensureValidIncrementAmount(c,e)&&ensureInitialized(this,e))&&inc(this,a,b,c,changedEmitter(this,resultFilter(e)))};function clear(a,b,c,e){a.buildUpdatersForCollumns(b,"",errorFilter(e,function(b,d){var d=d.existing,g=new MultipleAsyncWaiter(e),h;for(h in d)g.wait(),a.system.updateRecordIfExists(h,c,"",function(){g.done(null,null)});g.done(null,null)}))}
SharedParameterApiServer.prototype.clear=function(a,b,c){ensureValidIndex(b,c)&&ensureInitialized(this,c)&&clear(this,a,b,changedEmitter(this,resultFilter(c)))};function createColumn(a,b,c){a.buildUpdatersForCollumns(b,null,errorFilter(c,function(b,f){a.createCollectionInfoForUpdaters(f.needed,errorFilter(c,function(a){c(a,null)}))}))}SharedParameterApiServer.prototype.createColumn=function(a,b){ensureInitialized(this,b)&&createColumn(this,a,changedEmitter(this,resultFilter(b)))};
function clearColumn(a,b,c){a.buildUpdatersForCollumns(b,"",errorFilter(c,function(b,f){var f=f.existing,d=new MultipleAsyncWaiter(c),g;for(g in f)d.wait(),a.system.clearRecords(g,function(){d.done(null,null)});d.done(null,null)}))}SharedParameterApiServer.prototype.clearColumn=function(a,b){ensureInitialized(this,b)&&clearColumn(this,a,changedEmitter(this,resultFilter(b)))};
function ensureIndex(a,b,c){a.buildUpdatersForCollumns(b,"",errorFilter(c,function(b,f){var f=f.existing,d=new MultipleAsyncWaiter(c),g;for(g in f)d.wait(),a.system.ensureIndex(g,function(){d.done(null,null)});d.done(null,null)}))}SharedParameterApiServer.prototype.ensureIndex=function(a,b){ensureInitialized(this,b)&&ensureIndex(this,a,resultFilter(b))};
function dropIndex(a,b,c){a.buildUpdatersForCollumns(b,"",errorFilter(c,function(b,f){var f=f.existing,d=new MultipleAsyncWaiter(c),g;for(g in f)d.wait(),a.system.dropIndex(g,function(){d.done(null,null)});d.done(null,null)}))}SharedParameterApiServer.prototype.dropIndex=function(a,b){ensureInitialized(this,b)&&dropIndex(this,a,resultFilter(b))};
function getColumnSize(a,b,c){a.buildUpdatersForCollumns([b],null,errorFilter(c,function(b,f){var f=f.existing,d=null,g;for(g in f){(d=a.system.getCollectionInfo(g))&&c(b,d.high-d.low);break}d||c(b,0)}))}SharedParameterApiServer.prototype.getColumnSize=function(a,b){ensureInitialized(this,b)&&getColumnSize(this,a,resultFilter(b))};
function queryMessage(a,b,c,e){a.buildUpdatersForCollumns(b,null,errorFilter(e,function(b,d){var g=d=d.all,h=new MultipleAsyncWaiter(e),i;for(i in d)h.wait(),function(){var d=i,e=a.system.getCollectionInfo(i);if(e){var k=a.system.getCollection(e);g[d]=[];console.log(e.low,e.high+1);k.forRange(e.low,e.high+1,function(a,b,f){f===c&&(a||g[d].push(b-e.low))},function(){h.done(b,g)})}else h.done(null,null)}();h.done(null,g)}))}
SharedParameterApiServer.prototype.queryMessage=function(a,b,c){ensureInitialized(this,c)&&queryMessage(this,a,b,resultFilter(c))};
function updateAll_ifequals(a,b,c,e,f){a.buildUpdatersForCollumns(b,null,errorFilter(f,function(b,g){var h=g=g.all,i=new MultipleAsyncWaiter(f),j;for(j in g)i.wait(),function(){var b=j,d=a.system.getCollectionInfo(j);if(d){var f=a.system.getCollection(d);h[b]=[];console.log(d.low,d.high+1);f.forRange(d.low,d.high+1,function(f,g,h){h===c&&a.system.updateRecordIfExists(b,g-d.low,e,function(){})},function(){i.done(null,null)})}else i.done(null,null)}();i.done(null,null)}))}
SharedParameterApiServer.prototype.updateAll_ifequals=function(a,b,c,e){ensureInitialized(this,e)&&updateAll_ifequals(this,a,b,c,changedEmitter(this,resultFilter(e)))};SharedParameterApiServer.prototype.open=function(a){var b=this;this.opened?a(null,null):this.db.open(errorFilter(a,function(c,e){null!=e&&(b.opened=!0);b.system=new System(b.db,{collectionInfo:b.options.collectionInfo,startgc:b.options.startgc,startindex:b.options.startindex});a(c,null)}))};
function drop(a,b){a.buildUpdatersForCollumns(null,null,errorFilter(b,function(c,e){var e=e.existing,f=new MultipleAsyncWaiter(b),d;for(d in e)f.wait(),a.system.deleteCollection(d,function(){f.done(null,null)});f.done(null,null)}))}SharedParameterApiServer.prototype.drop=function(a){ensureInitialized(this,a)&&drop(this,a)};SharedParameterApiServer.prototype.initialize=function(a){ensureOpened(this,a)&&(this.initialized=!0,this.system.initialize(a))};var defaultApiServer=null;
SharedParameterApiServer.prototype.callAfterReady=function(a){var b=this,c=!1,e=!1;a&&(c?a():(e||(e=!0,b.open(function(f){null!==f&&void 0!=f?a(f):b.initialize(function(){c=!0;e=!1;b.emit("ready")})})),b.on("ready",a)))};function createInstance(a){return defaultApiServer=new SharedParameterApiServer(a)}function getInstance(){if(null==defaultApiServer)throw err=Error("should init before calling getInstance"),err;return defaultApiServer}module.exports.SharedParameterApiServer=SharedParameterApiServer;
module.exports.getInstance=getInstance;module.exports.createInstance=createInstance;module.exports.callAfterReady=function(a){a&&defaultApiServer.callAfterReady(a)};
