var util=require("util"),assert=require("assert"),events=require("events"),global=require("../../admin/common").Globalize,fs=require("fs"),strings=global.instance.getResource().errorMessages,errorCodeBase=-2E4,errorCodes={error_unknown:errorCodeBase,error_not_initialized:--errorCodeBase,error_not_opened:--errorCodeBase,error_invalid_index:--errorCodeBase,error_invalid_column_name:--errorCodeBase,error_invalid_add_option:--errorCodeBase,error_invalid_batch_size:--errorCodeBase,error_invalid_increment_amount:--errorCodeBase,
error_invalid_internal_index:--errorCodeBase,error_column_not_exist:--errorCodeBase,error_argument_should_be_array:--errorCodeBase};function noop(){}module.exports.noop=noop;function firstArg(a){return a}module.exports.firstArg=firstArg;function addFields(a,b){if(b)for(var c in b)"undefined"==typeof a[c]&&(a[c]=b[c]);return a}module.exports.addFields=addFields;function filterFields(a,b,c){for(var d in b)"undefined"!==typeof c[d]&&(a[d]=c[d]);return a}module.exports.filterFields=filterFields;
function setFields(a,b,c){if(b)for(var d in b)"undefined"!==typeof b[d]&&(a[d]=c);return a}module.exports.setFields=setFields;function substractFields(a,b){var c={},d;for(d in a)"undefined"==typeof b[d]&&(c[d]=a[d]);return c}module.exports.substractFields=substractFields;function testFields(a,b){for(field in a)if(a[field]!==b)return!1;return!0}module.exports.testFields=testFields;function RefCount(){this.count=1}module.exports.RefCount=RefCount;util.inherits(RefCount,events.EventEmitter);
RefCount.prototype.addRef=function(){++this.count};RefCount.prototype.release=function(){if(0==--this.count)switch(arguments.length){case 0:this.emit("destroy");break;case 1:this.emit("destroy",arguments[0]);break;case 2:this.emit("destroy",arguments[0],arguments[1]);break;default:var a=arguments.length,b=Array(2);b[0]="destroy";for(var c=0;c<a;c++)b[c+1]=arguments[c];this.emit.apply(this,argv)}};function MultipleAsyncWaiter(a){this.refCount=(new RefCount).on("destroy",a)}
module.exports.MultipleAsyncWaiter=MultipleAsyncWaiter;MultipleAsyncWaiter.prototype.wait=function(){this.refCount.addRef()};MultipleAsyncWaiter.prototype.done=function(a,b){a&&(this.error=a);this.refCount.release(this.error,b)};function buildError(a,b){b instanceof Error||("string"==typeof b&&(b=util.format.apply(null,Array.prototype.slice.call(arguments,1))),b=Error(b));b.code=a;return b}module.exports.buildError=buildError;function isValidNumber(a){return"number"==typeof a&&!isNaN(a)}
module.exports.isValidNumber=isValidNumber;function validateColumnName(a){return"string"!==typeof a?buildError(errorCodes.error_invalid_column_name,strings.error_column_name_must_be_a_String||"column name must be a String"):!a.match(/^[\w!#%&amp;(-\/:-@\ u0080-\uFFFF]*$/)?buildError(errorCodes.error_invalid_column_name,strings.error_reserved_column_name||"Invalid column name: %s",a):null}module.exports.validateColumnName=validateColumnName;function validateIndex(a){return isValidNumber(a)&&0<a}
module.exports.validateIndex=validateIndex;function isPreciseNumber(a){return 9007199254740992>a&&-9007199254740991<=a}module.exports.isPreciseNumber=isPreciseNumber;function ensureOpened(a,b){if(a.opened)return!0;b(buildError(errorCodes.error_not_opened,strings.error_not_opened||"Not opened"),null);return!1}module.exports.ensureOpened=ensureOpened;
function ensureInitialized(a,b){if(a.initialized)return!0;b(buildError(errorCodes.error_not_initialized,strings.error_not_initialized||"Not initialized"),null);return!1}module.exports.ensureInitialized=ensureInitialized;function ensureValidIndex(a,b){if(validateIndex(a))return!0;b(buildError(errorCodes.error_invalid_index,strings.error_invalid_index||"Invalid index: %s",a),null);return!1}module.exports.ensureValidIndex=ensureValidIndex;
function ensureValidInternalIndex(a,b){if(isPreciseNumber(a))return!0;b(buildError(errorCodes.error_invalid_internal_index,strings.error_invalid_internal_index||"Invalid internal index: %s",a),null);return!1}module.exports.ensureValidInternalIndex=ensureValidInternalIndex;function ensureValidAddOption(a,b){if(isValidNumber(a)&&0<=a&&2>=a)return!0;b(buildError(errorCodes.error_invalid_add_option,strings.error_invalid_add_option||"Invalid add option: %s",a),null);return!1}
module.exports.ensureValidAddOption=ensureValidAddOption;function ensureValidBatchSize(a,b){if(isValidNumber(a)&&0<=a)return!0;b(buildError(errorCodes.error_invalid_batch_size,strings.error_invalid_batch_size||"Invalid batch size: %s",a),null);return!1}module.exports.ensureValidBatchSize=ensureValidBatchSize;function ifError(a,b){return a?(b(a,null),!0):!1}module.exports.ifError=ifError;
function ensureValidIncrementAmount(a,b){if(isValidNumber(a))return!0;b(buildError(errorCodes.error_invalid_increment_amount,strings.error_invalid_increment_amount||"Invalid increment amount: %s",a),null);return!1}module.exports.ensureValidIncrementAmount=ensureValidIncrementAmount;function ensureValidArrayArgument(a,b,c){if(util.isArray(b))return!0;c(buildError(errorCodes.error_argument_should_be_array,strings.error_argument_should_be_array||'Argument "%s" should be an array',a),null);return!1}
module.exports.ensureValidArrayArgument=ensureValidArrayArgument;function errorFilter(a,b){return function(c,d){c?a(c,d):b(c,d)}}module.exports.errorFilter=errorFilter;function errorNullResultFilter(a,b){return function(c,d){c||void 0===d||null===d?a(c,null):b(c,d)}}module.exports.errorNullResultFilter=errorNullResultFilter;
function filterResult(a,b){if(a&&0<b)for(var c in a)filterResult(a[c],b-1);"object"==typeof a&&null!=a&&(void 0!==a._id&&delete a._id,void 0!==a._seq&&delete a._seq);return a}module.exports.filterResult=filterResult;function filterError(a){return a}module.exports.filterError=filterError;function resultFilter(a){return function(b,c){a(filterError(b),filterResult(c,1))}}module.exports.resultFilter=resultFilter;function changedEmitter(a,b){return function(c,d){b(c,d);a.emit("changed")}}
module.exports.changedEmitter=changedEmitter;function flagSetter(a,b,c,d){return function(e,f){a[b]=c;d(e,f)}}module.exports.flagSetter=flagSetter;function successFlagSetter(a,b,c){return function(d,e){d||(a[b]=!0,c(d,e))}}module.exports.successFlagSetter=successFlagSetter;function getAutoCollectionName(a){return"_"+a}module.exports.getAutoCollectionName=getAutoCollectionName;module.exports.getErrorCodes=function(){var a={};addFields(a,errorCodes);return a};
function increment(a,b){var c=parseInt(a);return!isNaN(c)?c+b:b}module.exports.increment=increment;function rmfso(a,b){fs.stat(a,function(c,d){debugger;d.isFile()?fs.unlink(a,function(c){console.log("unlinked "+a);console.log(c);b()}):d.isDirectory()&&fs.readdir(a,function(c,d){debugger;for(var g=(new RefCount).on("destory",function(){debugger;fs.rmdir(a,b)}),i=d.length,h=0;h<i;++h){var j=d[h];g.addRef();rmfso(a+"/"+j,function(){g.release()})}g.release()})})}module.exports.rmfso=rmfso;
function leftInsertPos(a,b,c,d){assert.ok(-1<d&&d>=c,"invalid range:("+c+","+d+")");for(var e=0,f=0;;){if(c===d)return c;e=Math.floor((c+d)/2);f=b[e];if(f===a)return e;f<a?c=e+1:d=e}}module.exports.leftInsertPos=leftInsertPos;function insertToSortedArray(a,b){a.splice(leftInsertPos(b,a,0,a.length),0,b);return a}module.exports.insertToSortedArray=insertToSortedArray;function removeFromSortedArray(a,b){var c=leftInsertPos(b,a,0,a.length);a[c]===b&&a.splice(c,1);return a}
module.exports.removeFromSortedArray=removeFromSortedArray;function Mutex(){this.state=!0;this.queue=[]}Mutex.prototype.wait=function(a){this.state?(this.state=!1,a()):this.queue.push(a)};Mutex.prototype.signal=function(){this.state=!0;0<this.queue.length&&(this.state=!1,setTimeout(this.queue.shift(),0))};module.exports.Mutex=Mutex;function ReaderWriterLock(){this.reads=0;this.writeMutex=new Mutex;this.readMutex=new Mutex;this.antiStarvingMutex=new Mutex}
ReaderWriterLock.prototype.acquireReaderLock=function(a){var b=this;b.antiStarvingMutex.wait(function(){b.antiStarvingMutex.signal();b.readMutex.wait(function(){0===b.reads++?b.writeMutex.wait(function(){b.readMutex.signal();a()}):(b.readMutex.signal(),a())})})};ReaderWriterLock.prototype.releaseReaderLock=function(){0===--this.reads&&this.writeMutex.signal()};
ReaderWriterLock.prototype.acquireWriterLock=function(a){var b=this;b.antiStarvingMutex.wait(function(){b.writeMutex.wait(function(){b.antiStarvingMutex.signal();a()})})};ReaderWriterLock.prototype.releaseWriterLock=function(){this.writeMutex.signal()};module.exports.ReaderWriterLock=ReaderWriterLock;
