var common=require("./common"),lock=require("./lock"),assert=require("assert"),util=require("util"),events=require("events"),errorFilter=common.errorFilter,validateColumnName=common.validateColumnName,ifError=common.ifError,getAutoCollectionName=common.getAutoCollectionName,setFields=common.setFields,errorNullResultFilter=common.errorNullResultFilter,noop=common.noop,Lock=lock.RowLock,Mutex=common.Mutex,addFields=common.addFields,ensureValidInternalIndex=common.ensureValidInternalIndex,MultipleAsyncWaiter=
common.MultipleAsyncWaiter,indexStatus_noindex=0,indexStatus_indexing=1,indexStatus_indexed=2,indexid_null=0,deleteStatus_deleting=1,deleteStatus_deleted=2;function MetaCache(a,b,c,d){this.deletedCollections={};this.collectionInfos={};this.orderedCollectionInfos={};this.indexInfos={};this.putCollectionInfo(a);this.putIndexInfo(c);this.collectionInfoMeta=b||{high:0};this.indexInfoMeta=d||{high:0}}
MetaCache.prototype.putCollectionInfo=function(a){var b=this.deletedCollections,c=this.collectionInfos,d;for(d in a){var e=a[d];e&&(e.deleted?(c[e.name]&&c[e.name].id==e.id&&delete c[e.name],b[e.id]=e):c[e.name]=e)}this.invalidateCollectionOrder()};MetaCache.prototype.putIndexInfo=function(a){cache=this.indexInfos;for(var b in a){var c=a[b];cache[c.id]=c}};
MetaCache.prototype.putCollectionInfoMeta=function(){1===arguments.length?this.collectionInfoMeta=arguments[0]:this.collectionInfoMeta[arguments[0]]=arguments[1]};MetaCache.prototype.getLiveCollectionInfos=function(){return this.collectionInfos};MetaCache.prototype.getCollectionInfo=function(a){return this.collectionInfos[a]};MetaCache.prototype.getDeletedCollectionInfos=function(){return this.deletedCollections};MetaCache.prototype.getIndexInfos=function(){return this.indexInfos};
MetaCache.prototype.getIndexInfo=function(a){return this.indexInfos[a]};MetaCache.prototype.markCollectionInfoForDelete=function(a){a.deleted=deleteStatus_deleting;this.putCollectionInfo([a])};MetaCache.prototype.markIndexInfoForDelete=function(a){a.deleted=deleteStatus_deleting;this.putIndexInfo([a])};MetaCache.prototype.deleteCollectionInfo=function(a){delete this.deletedCollections[a.id]};MetaCache.prototype.deleteIndexInfo=function(a){delete this.indexInfos[a.id]};
MetaCache.prototype.getOrderedCollectionInfos=function(){if(this.orderedCollectionInfos)return this.orderedCollectionInfos;var a=[],b;for(b in this.collectionInfos)a.push(this.collectionInfos[b]);a.sort(function(a,b){return a.order>b.order?1:a.order<b.order?-1:0});return this.orderedCollectionInfos=a};MetaCache.prototype.invalidateCollectionOrder=function(){this.orderedCollectionInfos=null};
function MetaStorage(a){a=a||{};this.options={};this.options.collectionInfo=a.collectionInfo||"__col_info";this.options.indexInfo=a.indexInfo||"__idx_info"}MetaStorage.prototype.getCollectionInfoStorageKey=function(a,b){switch(b){case "high":return this.options.collectionInfo+":"+a+":high";case "low":return this.options.collectionInfo+":"+a+":low";default:return this.options.collectionInfo+":"+a}};
MetaStorage.prototype.getCollectionInfoStorageValue=function(a,b){switch(b){case "high":return String(a.high);case "low":return String(a.low);default:return JSON.stringify({id:a.id,name:a.name,order:a.order,deleted:a.deleted,index:a.index,indexid:a.indexid})}};MetaStorage.prototype.getIndexInfoStorageKey=function(a){return this.options.indexInfo+":"+a};MetaStorage.prototype.getIndexInfoStorageValue=function(a){return JSON.stringify(a)};
MetaStorage.prototype.enumerateCollectionInfoStorages=function(a,b,c){c?b(this.getCollectionInfoStorageKey(a.id,c),this.getCollectionInfoStorageValue(a,c)):(this.enumerateCollectionInfoStorages(a,b,"high"),this.enumerateCollectionInfoStorages(a,b,"low"),this.enumerateCollectionInfoStorages(a,b,"base"))};MetaStorage.prototype.storeCollectionInfo=function(a,b,c){b.deleted!=deleteStatus_deleted&&this.enumerateCollectionInfoStorages(b,function(b,c){a.put(b,c)},c)};
MetaStorage.prototype.deleteCollectionInfo=function(a,b){this.enumerateCollectionInfoStorages(b,function(b){a.del(b)});b.deleted=deleteStatus_deleted};MetaStorage.prototype.storeCollectionInfoMeta=function(a,b){a.put(this.options.collectionInfo,JSON.stringify(b))};MetaStorage.prototype.storeIndexInfo=function(a,b){b.deleted!=deleteStatus_deleted&&a.put(this.getIndexInfoStorageKey(b.id),this.getIndexInfoStorageValue(b))};
MetaStorage.prototype.deleteIndexInfo=function(a,b){a.del(this.getIndexInfoStorageKey(b.id));b.deleted=deleteStatus_deleted};MetaStorage.prototype.storeIndexInfoMeta=function(a,b){a.put(this.options.indexInfo,JSON.stringify(b))};
MetaStorage.prototype.loadCollectionInfos=function(a,b){var c=null,d={};a.forPrefix(this.options.collectionInfo,{},function(a,b,g){a=b.split(":");1===a.length&&(c=JSON.parse(g));if(1<a.length)if(b=a[1],2===a.length){var h=JSON.parse(g);d[b]=h;assert.equal(h.id,b)}else if(3===a.length&&("high"==a[2]||"low"==a[2]))(h=d[b])&&(h[a[2]]=parseFloat(g))},function(){b(null,d,c)})};
MetaStorage.prototype.loadIndexInfos=function(a,b){var c=null,d={};a.forPrefix(this.options.indexInfo,{},function(a,b,g){b=b.split(":");1===b.length&&(c=JSON.parse(g));1<b.length&&(a=b[1],2===b.length&&(g=JSON.parse(g),d[a]=g,assert.equal(g.id,a)))},function(){b(null,d,c)})};
MetaStorage.prototype.loadMetaCache=function(a,b){var c=null,d=null,e=null,f=null,g=new MultipleAsyncWaiter(function(a){b(a,c,d,e,f)});g.wait();this.loadCollectionInfos(a,function(a,b,e){c=b;d=e;g.done(a)});g.wait();this.loadIndexInfos(a,function(a,b,d){e=b;f=d;g.done(a)});g.done()};function GarbageCollector(a){this.system=a;this.running=!1}GarbageCollector.prototype.getInterval=function(){return 0};
GarbageCollector.prototype.getGarbage=function(a){var b=a.getDeletedCollectionInfos(),c=null,d;for(d in b)if(c=b[d])return{type:"collection",payload:c};a=a.getIndexInfos();b=null;for(d in a)if(b=a[d],b.deleted)return{type:"index",payload:b};return null};
GarbageCollector.prototype.collectCollection=function(a,b,c,d,e,f){function g(){if(h.low<h.high){var j=h.low+1,i=h.high+1,k=Math.min(j+e,i),m=d;k>=i&&(m=0);self.system.db.asyncStore(function(a,d,e){h.low=k-1;b.storeCollectionInfo(d,h,"low");c.batchDeleteRange(d,j,k,e)},function(){setTimeout(g,m)})}else self.system.db.asyncStore(function(b,d,e){c.batchClean(d,function(){self.collectCollectionInfo(a,self.system.metaStore,d,h);e()})},f)}var h=c.info;g()};
GarbageCollector.prototype.collectCollectionIndex=function(a,b,c,d,e,f){var g=this;g.system.index.deleteIndex(c.id,function(){g.system.db.store(function(d,e){g.collectIndexInfo(a,b,e,c)},f)})};
GarbageCollector.prototype._collect=function(a,b,c){function d(){var h=e.getGarbage(f);if(h)switch(h.type){case "collection":e.collectCollection(f,g,e.system.getCollection(h.payload),a,b,d);break;case "index":e.collectCollectionIndex(f,g,h.payload,a,b,d);break;default:assert.fail(h.type,"collection|index","unexpected garbage type")}else c(null,null)}var e=this,f=e.system.cache,g=e.system.metaStore;d()};
GarbageCollector.prototype.collectCollectionInfo=function(a,b,c,d){this.system.destroyCollectionInstance(d);a.deleteCollectionInfo(d);b.deleteCollectionInfo(c,d);d.index&&(d=a.getIndexInfo(d.indexid))&&this.collectIndexInfo(a,b,c,d)};GarbageCollector.prototype.collectIndexInfo=function(a,b,c,d){this.system.index.deleteIndexInfo(a,b,c,d)};
GarbageCollector.prototype.collect=function(){self=this;self.running||(console.log("gc start"),self.running=!0,setTimeout(function(){self._collect(self.getInterval(),100,function(){console.log("gc end");self.running=!1})},self.getInterval()))};
function CollectionIndex(a,b){this.index=a;this.indexid=b.info.indexid;this.collection=b;this.addHandle=this.onAdd.bind(this);this.updateHandle=this.onUpdate.bind(this);this.delHandle=this.onDel.bind(this);b.on("add",this.addHandle);b.on("update",this.updateHandle);b.on("del",this.delHandle)}CollectionIndex.prototype.destroy=function(){this.collection.removeListener("add",this.addHandle);this.collection.removeListener("udpate",this.updateHandle);this.collection.removeListener("del",this.delHandle)};
CollectionIndex.prototype.onAdd=function(a,b,c){this.index.batchAddIndex(a,this.indexid,b,c)};CollectionIndex.prototype.onUpdate=function(a,b,c,d,e){if(void 0!==c)this.index.batchUpdateIndex(a,this.indexid,b,c,d);else{assert.notEqual(e,null);var f=this;e.wait();this.collection.get(b,function(c,h){f.index.batchUpdateIndex(a,f.indexid,b,h,d);e.done()})}};
CollectionIndex.prototype.onDel=function(a,b,c,d){if(void 0!==c)this.index.batchDeleteIndex(a,this.indexid,b,c);else{assert.notEqual(d,null);var e=this;d.wait();this.collection.get(b,function(c,g){e.index.batchDeleteIndex(a,e.indexid,b,g);d.done()})}};
function SystemIndex(a){this.system=a;this.index=a.db.getIndex();this.collectionIndexes={};a.on("createCollectionInstance",this.subscribeCollectionChangeEvents.bind(this));a.on("destroyCollectionInstance",this.unsubscribeCollectionChangeEvents.bind(this))}SystemIndex.prototype.getIndexInfo=function(a){return this.system.cache.getIndexInfo(a)};
SystemIndex.prototype.subscribeCollectionChangeEvents=function(a){a.info.index&&!this.collectionIndexes[a.id]&&(this.collectionIndexes[a.id]=new CollectionIndex(this.index,a))};SystemIndex.prototype.unsubscribeCollectionChangeEvents=function(a){a.info.index&&this.collectionIndexes[a.id]&&(this.collectionIndexes[a.id].destroy(),delete this.collectionIndexes[a.id])};
SystemIndex.prototype.createIndexInBackground=function(a){if(!a.info.index){var b=this;a.info.index=indexStatus_indexing;var c=this.system.cache,d=this.system.metaStore,e={id:++c.indexInfoMeta.high,col:a.info.id};a.info.indexid=e.id;b.subscribeCollectionChangeEvents(a);c.putIndexInfo([e]);var f=b.system.getCollectionLock(a.id);f.acquireTableLock(function(){b.system.db.store(function(b,f){d.storeCollectionInfo(f,a.info,"base");d.storeIndexInfoMeta(f,c.indexInfoMeta);d.storeIndexInfo(f,e)},function(){b.createIndex(a,
function(){b.system.db.store(function(b,c){a.info.index===indexStatus_indexing&&(a.info.index=indexStatus_indexed,d.storeCollectionInfo(c,a.info,"base"))},function(){f.releaseTableLock()})})})})}};
SystemIndex.prototype.removeIndexInBackground=function(a){if(a.info.index&&a.info.indexid){var b=this,c=b.getIndexInfo(a.info.indexid),d=b.system.metaStore;b.unsubscribeCollectionChangeEvents(a);a.info.index=indexStatus_noindex;a.info.indexid=indexid_null;c.deleted=deleteStatus_deleting;var e=b.system.getCollectionLock(a.id);e.acquireTableLock(function(){b.system.db.store(function(e,g){d.storeCollectionInfo(g,a.info,"base");d.storeIndexInfo(g,c);b.system.gc.collect()},function(){e.releaseTableLock()})})}};
SystemIndex.prototype.deleteIndex=function(a,b){this.index.deleteIndexForId(this.system.db,a,b)};SystemIndex.prototype.deleteIndexInfo=function(a,b,c,d){a.deleteIndexInfo(d);b.deleteIndexInfo(c,d)};
SystemIndex.prototype.createIndex=function(a,b){var c=this;if(a.info.deleted||!a.info.index)return b(null,null);c.system._batchIterate(a.info.low,a.info.high+1,function(b,e,f){if(a.info.deleted||!a.info.index)return f(null,null,!0);c.system.db.asyncStore(function(f,h,j){a.forRange(b,e,function(b,d,e){if(a.info.deleted||!a.info.index)return!0;c.index.batchAddIndex(h,a.info.indexid,d,e)},j)},f)},b)};
SystemIndex.prototype.redoUndoneIndex=function(a){var b=this,c=b.system.cache.getLiveCollectionInfos(),d=new MultipleAsyncWaiter(a),e;for(e in c)(function(){var a=c[e];if(a.index===indexStatus_indexing){d.wait();var g=b.system.getCollectionLock(a.id);g.acquireTableLock(function(){b.createIndex(b.system.getCollection(a),function(){b.system.db.store(function(d,c){a.index===indexStatus_indexing&&(a.index=indexStatus_indexed,b.system.metaStore.storeCollectionInfo(c,a,"base"))},function(){g.releaseTableLock();
d.done()})})})}})();d.done()};SystemIndex.prototype.getFirstIndexOfValue=function(a,b,c){this.index.getFirstKeyOfValue(this.system.db,a.info.indexid,b,errorFilter(c,function(a,b){null!==b&&(b=parseInt(b));c(a,b)}))};SystemIndex.prototype.getKeysOfValue=function(a,b,c,d){this.index.getKeysOfValue(this.system.db,a.info.indexid,b,errorFilter(c,function(a,b){null!==b&&(b=parseInt(b));c(a,b)}),d)};
function System(a,b){b=b||{};b.collectionInfo=b.collectionInfo||"__col_info";b.config=b.config||"__config";void 0===b.startgc&&(b.startgc=!0);void 0===b.startindex&&(b.startindex=!0);this.options=b;this.db=a;this.metaStore=new MetaStorage(this.options);this.locks={};this.cache=null;this.colllections={};this.gc=new GarbageCollector(this);this.index=new SystemIndex(this);this.initialized=!1}util.inherits(System,events.EventEmitter);
System.prototype.initialize=function(a){if(this.initialized)return a(null,null);console.log("System initialize");var b=this;this.loadMetaCache(function(){b.options.startgc&&b.gc.collect();b.options.startindex&&b.index.redoUndoneIndex(noop);b.initialized=!0;a()})};System.prototype.getCollection=function(a){if(this.colllections[a.id])return this.colllections[a.id];var b=this.createCollectionInstance(a);return this.colllections[a.id]=b};System.prototype.getCollectionInfo=function(a){return this.cache.getCollectionInfo(a)};
System.prototype.getCollectionLock=function(a){this.locks[a]=this.locks[a]||new Lock;return this.locks[a]};
System.prototype.createCollection=function(a,b){var c=this,d=this.cache,e=d.getCollectionInfo(a);null==e?(++d.collectionInfoMeta.high,e={name:a,id:d.collectionInfoMeta.high,order:d.collectionInfoMeta.high,high:0,low:0},d.putCollectionInfo([e]),c.db.store(function(b,e){c.metaStore.storeCollectionInfoMeta(e,d.collectionInfoMeta);c.metaStore.storeCollectionInfo(e,d.getCollectionInfo(a))},function(){configure.autoCreateIndexedColumn?c.ensureIndex(a,function(){b(null,e)}):b(null,e)})):b(null,e)};
System.prototype.destroyCollectionInstance=function(a){var b=this.colllections[a.id];delete this.colllections[a.id];delete this.locks[a.id];b&&this.emit("destroyCollectionInstance",b)};System.prototype.createCollectionInstance=function(a){a=this.db.getCollection(a);this.emit("createCollectionInstance",a);return a};System.prototype.clearCache=function(){this.cache=null};
System.prototype.loadMetaCache=function(a){var b=this;this.metaStore.loadMetaCache(this.db,function(c,d,e,f,g){b.cache=new MetaCache(d,e,f,g);a(null,b.cache)})};System.prototype.getCache=function(a){a(null,this.cache)};System.prototype.getRecord=function(a,b,c){(a=this.getCollectionInfo(a))?(b=a.low+b,this.getCollection(a).get(b,c)):c(null,null)};
System.prototype.getRecords=function(a,b,c,d){(a=this.getCollectionInfo(a))?(b=Math.min(a.low+b,a.high+1),c=Math.min(a.low+c,a.high+1),this.getCollection(a).getRange(b,c,d)):d(null,null)};
System.prototype.addRecord=function(a,b,c){var d=this,e=d.getCollectionInfo(a);if(e){var f=d.getCollection(e),g=d.getCollectionLock(e.id);g.acquireSharedTableLock(function(){function a(){g.releaseSharedTableLock();c.apply(null,arguments)}if(ensureValidInternalIndex(e.high,a)){var j=++e.high;g.acquireSingleLock(j,function(){d.db.store(function(a,c){f.batchAdd(c,j,b);d.metaStore.storeCollectionInfo(c,e,"high")},function(b,c){g.releaseSingleLock(j);a(b,c)})})}})}else c(null,null)};
System.prototype.addRecords=function(a,b,c){var d=this,e=d.getCollectionInfo(a);if(e){var f=d.getCollectionLock(e.id);f.acquireSharedTableLock(function(){function a(){f.releaseSharedTableLock();c.apply(null,arguments)}var h=e.high+1,j=e.high+b.length;ensureValidInternalIndex(j,a)&&(e.high=j,f.acquireRangeLock(h,j,function(){var c=d.getCollection(e);d.db.store(function(a,f){c.batchAddRange(f,h,b);d.metaStore.storeCollectionInfo(f,e,"high")},function(b,c){f.releaseRangeLock(h,j);a(b,c)})}))})}else c(null,
null)};System.prototype.insertRecord=function(a,b,c){var d=this,e=d.getCollectionInfo(a);if(e){var f=d.getCollection(e),g=d.getCollectionLock(e.id);g.acquireSharedTableLock(function(){function a(){g.releaseSharedTableLock();c.apply(null,arguments)}if(ensureValidInternalIndex(e.low,a)){var j=e.low--;g.acquireSingleLock(j,function(){d.db.store(function(a,c){a||(f.batchAdd(c,j,b),d.metaStore.storeCollectionInfo(c,e,"low"))},function(b,c){g.releaseSingleLock(j);a(b,c)})})}})}else c(null,null)};
System.prototype.mapReduce=function(a,b,c){function d(a,d){b&&b(a,d,c)}a?a(errorFilter(c,d)):d(null,result)};System.prototype.getKeysOfValue=function(a,b,c,d){if((a=this.getCollectionInfo(a))&&a.index===indexStatus_indexed)a=this.getCollection(a),this.index.getKeysOfValue(a,b,c,d)};
System.prototype.addUniqueRecord=function(a,b,c){var d=this,e=d.getCollectionInfo(a);if(e){var f=d.getCollection(e),g=e.high+1;if(ensureValidInternalIndex(g,c)){var h=null,h=e.index===indexStatus_indexed?function(a){d.index.getFirstIndexOfValue(f,b,function(b,c){a(b,b||null===c)})}:function(a){var c=!0,d=null;f.forRange(e.low,g,function(a,e,f){if(a)d=a;else if(f==b)return c=!1,!0},function(){a(d,c)})},j=function(a,c,h){a||!c?h(a,0):(g=e.high+1,e.high=g,d.db.store(function(a,c){f.batchAdd(c,g,b);d.metaStore.storeCollectionInfo(c,
e,"high")},function(a){h(a,1)}))},i=d.getCollectionLock(e.id);i.acquireTableLock(function(){d.mapReduce(h,j,function(a,b){i.releaseTableLock();c(a,b)})})}}else c(null,null)};System.prototype._batchIterate=function(a,b,c,d){function e(a,j){if(!a&&f<b){var i=Math.min(f+g,b);c(f,i,errorFilter(d,function(a,b,c){c||(f=i,e(a,b))}))}else d(a,j)}var f=a,g=100;e(null)};
System.prototype._fillRecord=function(a,b,c,d,e){var f=this;this._batchIterate(c,d,function(c,d,e){f.db.store(function(e,f){a.batchFillNewRange(f,c,d,b)},e)},function(){e()})};
System.prototype.updateRecord=function(a,b,c,d){var e=this,f=e.getCollectionInfo(a);if(f){var g=e.getCollection(f),h=e.getCollectionLock(f.id);h.acquireSharedTableLock(function(){function a(){h.releaseSharedTableLock();d.apply(null,arguments)}var i=f.low+b;if(ensureValidInternalIndex(i,a)){var k=i,m=i-f.high;0<m&&(k=f.high+1,f.high=i);1>=m?h.acquireSingleLock(i,function(){e.db.asyncStore(function(a,b,d){0<m?(g.batchAdd(b,i,c),e.metaStore.storeCollectionInfo(b,f,"high"),d()):g.batchUpdate(b,i,void 0,
c,d)},function(b,c){h.releaseSingleLock(i);a(b,c)})}):h.acquireRangeLock(k,i,function(){e._fillRecord(g,"",k,i,function(){e.db.store(function(a,b){g.batchAdd(b,i,c);e.metaStore.storeCollectionInfo(b,f,"high")},function(b,c){h.releaseRangeLock(k,i);a(null,c)})})})}})}else d(null,null)};
System.prototype.transformRecord=function(a,b,c,d){var e=this,f=e.getCollectionInfo(a);if(f){var g=e.getCollection(f),h=e.getCollectionLock(f.id);h.acquireSharedTableLock(function(){function a(){h.releaseSharedTableLock();d.apply(null,arguments)}var i=f.low+b;if(ensureValidInternalIndex(i,a)){var k=i,m=i-f.high,n=!1,l;if(0<m){k=f.high+1;l=c(null);n=!0;if(null===l)return a(null,0,l);f.high=i}1>=m?h.acquireSingleLock(i,function(){g.get(i,function(b,d){l=null===d&&n?l:c(d);if(l===d)return h.releaseSingleLock(i),
a(null,0,l);e.db.store(function(a,b){0<m?(g.batchAdd(b,i,l),e.metaStore.storeCollectionInfo(b,f,"high")):g.batchUpdate(b,i,d,l)},function(b){h.releaseSingleLock(i);return a(b,1,l)})})}):h.acquireRangeLock(k,i,function(){e._fillRecord(g,"",k,i,function(){e.db.store(function(a,b){g.batchAdd(b,i,l);e.metaStore.storeCollectionInfo(b,f,"high")},function(b){h.releaseRangeLock(k,i);return a(b,1,l)})})})}})}else d(null,null)};
System.prototype.incrementRecord=function(a,b,c,d){this.transformRecord(a,b,function(a){return common.increment(a,c).toString()},function(a,b,c){d(a,parseInt(c))})};System.prototype.updateRecordIfEquals=function(a,b,c,d,e){this.transformRecord(a,b,function(a){return a===c?d:a},e)};
System.prototype.retrieveRecord=function(a,b){var c=this,d=c.getCollectionInfo(a);if(d){var e=c.getCollection(d),f=c.getCollectionLock(d.id);f.acquireSharedTableLock(function(){function a(){f.releaseSharedTableLock();b.apply(null,arguments)}if(d.low>=d.high)a(null,null);else{var h=d.low+1;h<=d.high?(++d.low,f.acquireSingleLock(h,function(){e.get(h,function(b,i){c.db.store(function(a,b){a||(e.batchDelete(b,h,i),c.metaStore.storeCollectionInfo(b,d,"low"))},function(b){f.releaseSingleLock(h);a(b,i)})})})):
a(null,null)}})}else b(null,null)};
System.prototype.retrieveBottom=function(a,b){var c=this,d=c.getCollectionInfo(a);if(d){var e=c.getCollection(d),f=c.getCollectionLock(d.id);f.acquireSharedTableLock(function(){function a(){f.releaseSharedTableLock();b.apply(null,arguments)}if(d.low>=d.high)a(err,null);else{var h=d.high;h>=d.low?(--d.high,f.acquireSingleLock(h,function(){e.get(h,function(b,i){c.db.store(function(a,b){a||(e.batchDelete(b,h,i),c.metaStore.storeCollectionInfo(b,d,"high"))},function(b){f.releaseSingleLock(h);a(b,i)})})})):
a(null,null)}})}else b(null,null)};System.prototype.updateRecordIfExists=function(a,b,c,d){var e=this,f=e.getCollectionInfo(a);if(f){var g=e.getCollection(f),h=e.getCollectionLock(f.id);h.acquireSharedTableLock(function(){function a(){h.releaseSharedTableLock();d.apply(null,arguments)}var i=f.low+b;i>f.high?a(null,0):h.acquireSingleLock(i,function(){e.db.asyncStore(function(a,b,d){g.batchUpdate(b,i,void 0,c,d)},function(b){h.releaseSingleLock(i);a(b,1,c)})})})}else d(null,null)};
System.prototype.clearRecords=function(a,b){var c=this,d=c.getCollectionInfo(a);if(d){if(0==d.low&&0==d.high)return b();c.cache.markCollectionInfoForDelete(d);c.gc.collect();c.createCollection(a,function(a,f){f.order=d.order;c.db.store(function(a,b){c.metaStore.storeCollectionInfo(b,d,"base");c.metaStore.storeCollectionInfo(b,f,"base")},b)})}else b(null,null)};
System.prototype.deleteCollection=function(a,b){var c=this,d=c.getCollectionInfo(a);d?(c.cache.markCollectionInfoForDelete(d),0==d.low&&0==d.high?c.db.store(function(a,b){c.gc.collectCollectionInfo(c.cache,c.metaStore,b,d)},b):(c.gc.collect(),c.db.store(function(a,b){c.metaStore.storeCollectionInfo(b,d,"base")},b))):b(null,null)};System.prototype.ensureIndex=function(a,b){var c=this.getCollectionInfo(a);c&&this.index.createIndexInBackground(this.getCollection(c));b(null,null)};
System.prototype.dropIndex=function(a,b){var c=this.getCollectionInfo(a);c&&this.index.removeIndexInBackground(this.getCollection(c));b(null,null)};System.prototype.hasIndex=function(a){a=this.getCollectionInfo(a);return null!=a&&0<a.index};System.prototype.saveConfig=function(a,b,c){this.db.putMeta(this.options.config+a,b,function(a){c(a)})};System.prototype.getConfig=function(a,b){this.db.getMeta(this.options.config+a,function(a,d){b(a,d)})};
System.prototype.updateMeta=function(a,b){var c=this;this.db.store(function(b,e){c.metaStore.storeCollectionInfo(e,a,"base")},function(){b&&b()})};System.prototype.deleteDatabase=function(){this.db.destroy()};module.exports.System=System;
