(function(d){function a(){c.hide();b.hide()}var c,b,f,e,h,g={menuStyle:{listStyle:"none",padding:"1px",margin:"0px",backgroundColor:"#fff",border:"1px solid #999",minWidth:"100px","font-size":"110%"},itemStyle:{margin:"0px",color:"#000",display:"block",cursor:"default",padding:"3px","padding-right":"8px",border:"1px solid #fff","white-space":"nowrap",backgroundColor:"transparent"},itemHoverStyle:{"background-color":"#3B83E7",color:"White",border:"1px solid #3B83E7","border-radius":"4px"},eventPosX:"pageX",
eventPosY:"pageY",shadow:!0,onContextMenu:null,onShowMenu:null};d.fn.contextMenu=function(i,j){c||(c=d('<div id="jqContextMenu"></div>').hide().css({position:"absolute",zIndex:"500"}).appendTo("body").bind("click",function(d){d.stopPropagation()}));b||(b=d("<div></div>").css({backgroundColor:"#000",position:"absolute",opacity:0.2,zIndex:499}).appendTo("body").hide());e=e||[];e.push({id:i,menuStyle:d.extend({},g.menuStyle,j.menuStyle||{}),itemStyle:d.extend({},g.itemStyle,j.itemStyle||{}),itemHoverStyle:d.extend({},
g.itemHoverStyle,j.itemHoverStyle||{}),bindings:j.bindings||{},shadow:j.shadow||!1===j.shadow?j.shadow:g.shadow,onContextMenu:j.onContextMenu||g.onContextMenu,onShowMenu:j.onShowMenu||g.onShowMenu,eventPosX:j.eventPosX||g.eventPosX,eventPosY:j.eventPosY||g.eventPosY});var n=e.length-1;d(this).bind("contextmenu",function(l){var g=e[n].onContextMenu?e[n].onContextMenu(l):!0;h=l.target;if(g){var z=this,v=e[n];f=d("#"+v.id).find("ul:first").clone(!0);f.css(v.menuStyle).find("li").css(v.itemStyle).hover(function(){d(this).css(v.itemHoverStyle);
d(this).addClass("menuHover")},function(){d(this).css(v.itemStyle);d(this).removeClass("menuHover")}).find("img").css({verticalAlign:"middle",paddingRight:"2px"});c.html(f);v.onShowMenu&&(c=v.onShowMenu(l,c));d.each(v.bindings,function(b,v){d("#"+b,c).bind("click",function(){a();v(z,h)})});g=l[v.eventPosX];g+c.width()>d(window).width()&&(g=d(window).width()-c.width()-10);c.css({left:g,top:l[v.eventPosY]}).show();v.shadow&&b.css({width:c.width(),height:c.height(),left:g+2,top:l.pageY+2}).show();d(document).one("click",
a);return!1}});return this};d.contextMenu={defaults:function(a){d.each(a,function(a,b){"object"==typeof b&&g[a]?d.extend(g[a],b):g[a]=b})}}})(jQuery);$(function(){$("div.contextMenu").hide()});/*

 jQuery blockUI plugin
 Version 2.42 (11-MAY-2012)
 @requires jQuery v1.2.3 or later

 Examples at: http://malsup.com/jquery/block/
 Copyright (c) 2007-2010 M. Alsup
 Dual licensed under the MIT and GPL licenses:
 http://www.opensource.org/licenses/mit-license.php
 http://www.gnu.org/licenses/gpl.html

 Thanks to Amir-Hossein Sobhi for some excellent contributions!
*/
(function(){var d=jQuery,a=function(a,b){var e,i,q=a==window,p=b&&void 0!==b.message?b.message:void 0,b=d.extend({},d.blockUI.defaults,b||{});if(!b.ignoreIfBlocked||!d(a).data("blockUI.isBlocked")){b.overlayCSS=d.extend({},d.blockUI.defaults.overlayCSS,b.overlayCSS||{});e=d.extend({},d.blockUI.defaults.css,b.css||{});i=d.extend({},d.blockUI.defaults.themedCSS,b.themedCSS||{});p=void 0===p?b.message:p;q&&l&&c(window,{fadeOut:0});if(p&&"string"!=typeof p&&(p.parentNode||p.jquery)){var s=p.jquery?p[0]:
p,m={};d(a).data("blockUI.history",m);m.el=s;m.parent=s.parentNode;m.display=s.style.display;m.position=s.style.position;m.parent&&m.parent.removeChild(s)}d(a).data("blockUI.onUnblock",b.onUnblock);var m=b.baseZ,w=b.forceIframe?d('<iframe class="blockUI" style="z-index:'+m++ +';display:none;border:none;margin:0;padding:0;position:absolute;width:100%;height:100%;top:0;left:0" src="'+b.iframeSrc+'"></iframe>'):d('<div class="blockUI" style="display:none"></div>'),s=b.theme?d('<div class="blockUI blockOverlay ui-widget-overlay" style="z-index:'+
m++ +';display:none"></div>'):d('<div class="blockUI blockOverlay" style="z-index:'+m++ +';display:none;border:none;margin:0;padding:0;width:100%;height:100%;top:0;left:0"></div>'),m=d(b.theme&&q?'<div class="blockUI '+b.blockMsgClass+' blockPage ui-dialog ui-widget ui-corner-all" style="z-index:'+(m+10)+';display:none;position:fixed"><div class="ui-widget-header ui-dialog-titlebar ui-corner-all blockTitle">'+(b.title||"&nbsp;")+'</div><div class="ui-widget-content ui-dialog-content"></div></div>':
b.theme?'<div class="blockUI '+b.blockMsgClass+' blockElement ui-dialog ui-widget ui-corner-all" style="z-index:'+(m+10)+';display:none;position:absolute"><div class="ui-widget-header ui-dialog-titlebar ui-corner-all blockTitle">'+(b.title||"&nbsp;")+'</div><div class="ui-widget-content ui-dialog-content"></div></div>':q?'<div class="blockUI '+b.blockMsgClass+' blockPage" style="z-index:'+(m+10)+';display:none;position:fixed"></div>':'<div class="blockUI '+b.blockMsgClass+' blockElement" style="z-index:'+
(m+10)+';display:none;position:absolute"></div>');p&&(b.theme?(m.css(i),m.addClass("ui-widget-content")):m.css(e));!b.theme&&(!b.applyPlatformOpacityRules||!d.browser.mozilla||!/Linux/.test(navigator.platform))&&s.css(b.overlayCSS);s.css("position",q?"fixed":"absolute");(d.browser.msie||b.forceIframe)&&w.css("opacity",0);e=[w,s,m];var E=q?d("body"):d(a);d.each(e,function(){this.appendTo(E)});b.theme&&(b.draggable&&d.fn.draggable)&&m.draggable({handle:".ui-dialog-titlebar",cancel:"li"});e=j&&(!d.boxModel||
0<d("object,embed",q?null:a).length);if(n||e){q&&(b.allowBodyStretch&&d.boxModel)&&d("html,body").css("height","100%");if((n||!d.boxModel)&&!q){e=parseInt(d.css(a,"borderTopWidth"))||0;i=parseInt(d.css(a,"borderLeftWidth"))||0;var F=e?"(0 - "+e+")":0,A=i?"(0 - "+i+")":0}d.each([w,s,m],function(d,a){var c=a[0].style;c.position="absolute";if(2>d)q?c.setExpression("height","Math.max(document.body.scrollHeight, document.body.offsetHeight) - (jQuery.boxModel?0:"+b.quirksmodeOffsetHack+') + "px"'):c.setExpression("height",
'this.parentNode.offsetHeight + "px"'),q?c.setExpression("width",'jQuery.boxModel && document.documentElement.clientWidth || document.body.clientWidth + "px"'):c.setExpression("width",'this.parentNode.offsetWidth + "px"'),A&&c.setExpression("left",A),F&&c.setExpression("top",F);else if(b.centerY)q&&c.setExpression("top",'(document.documentElement.clientHeight || document.body.clientHeight) / 2 - (this.offsetHeight / 2) + (blah = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "px"'),
c.marginTop=0;else if(!b.centerY&&q){var e="((document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "+(b.css&&b.css.top?parseInt(b.css.top):0)+') + "px"';c.setExpression("top",e)}})}p&&(b.theme?m.find(".ui-widget-content").append(p):m.append(p),(p.jquery||p.nodeType)&&d(p).show());(d.browser.msie||b.forceIframe)&&b.showOverlay&&w.show();if(b.fadeIn)e=b.onBlock?b.onBlock:g,w=b.showOverlay&&!p?e:g,e=p?e:g,b.showOverlay&&s._fadeIn(b.fadeIn,w),p&&m._fadeIn(b.fadeIn,
e);else if(b.showOverlay&&s.show(),p&&m.show(),b.onBlock)b.onBlock();f(1,a,b);q?(l=m[0],r=d(":input:enabled:visible",l),b.focusInput&&setTimeout(h,20)):(e=m[0],p=b.centerX,s=b.centerY,i=e.parentNode,m=e.style,w=(i.offsetWidth-e.offsetWidth)/2-(parseInt(d.css(i,"borderLeftWidth"))||0),e=(i.offsetHeight-e.offsetHeight)/2-(parseInt(d.css(i,"borderTopWidth"))||0),p&&(m.left=0<w?w+"px":"0"),s&&(m.top=0<e?e+"px":"0"));b.timeout&&(p=setTimeout(function(){q?d.unblockUI(b):d(a).unblock(b)},b.timeout),d(a).data("blockUI.timeout",
p))}},c=function(a,c){var e=a==window,g=d(a),h=g.data("blockUI.history"),i=g.data("blockUI.timeout");i&&(clearTimeout(i),g.removeData("blockUI.timeout"));c=d.extend({},d.blockUI.defaults,c||{});f(0,a,c);null===c.onUnblock&&(c.onUnblock=g.data("blockUI.onUnblock"),g.removeData("blockUI.onUnblock"));var j;j=e?d("body").children().filter(".blockUI").add("body > .blockUI"):d(".blockUI",a);e&&(l=r=null);c.fadeOut?(j.fadeOut(c.fadeOut),setTimeout(function(){b(j,h,c,a)},c.fadeOut)):b(j,h,c,a)},b=function(a,
b,c,e){a.each(function(){this.parentNode&&this.parentNode.removeChild(this)});b&&b.el&&(b.el.style.display=b.display,b.el.style.position=b.position,b.parent&&b.parent.appendChild(b.el),d(e).removeData("blockUI.history"));if("function"==typeof c.onUnblock)c.onUnblock(e,c)},f=function(b,a,c){var g=a==window,a=d(a);if(b||!(g&&!l||!g&&!a.data("blockUI.isBlocked")))a.data("blockUI.isBlocked",b),c.bindEvents&&(!b||c.showOverlay)&&(b?d(document).bind("mousedown mouseup keydown keypress",c,e):d(document).unbind("mousedown mouseup keydown keypress",
e))},e=function(b){if(b.keyCode&&9==b.keyCode&&l&&b.data.constrainTabKey){var a=r,c=b.shiftKey&&b.target===a[0];if(!b.shiftKey&&b.target===a[a.length-1]||c)return setTimeout(function(){h(c)},10),!1}a=b.data;return 0<d(b.target).parents("div."+a.blockMsgClass).length?!0:0==d(b.target).parents().children().filter("div.blockUI").length},h=function(d){r&&(d=r[!0===d?r.length-1:0])&&d.focus()};d.fn._fadeIn=d.fn.fadeIn;var g=function(){},i=document.documentMode||0,j=d.browser.msie&&(8>d.browser.version&&
!i||8>i),n=d.browser.msie&&/MSIE 6.0/.test(navigator.userAgent)&&!i;d.blockUI=function(d){a(window,d)};d.unblockUI=function(d){c(window,d)};d.growlUI=function(b,a,c,e){var l=d('<div class="growlUI"></div>');b&&l.append("<h1>"+b+"</h1>");a&&l.append("<h2>"+a+"</h2>");void 0==c&&(c=3E3);d.blockUI({message:l,fadeIn:700,fadeOut:1E3,centerY:!1,timeout:c,showOverlay:!1,onUnblock:e,css:d.blockUI.defaults.growlCSS})};d.fn.block=function(b){var c=d.extend({},d.blockUI.defaults,b||{});this.each(function(){var b=
d(this);(!c.ignoreIfBlocked||!b.data("blockUI.isBlocked"))&&b.unblock({fadeOut:0})});return this.each(function(){"static"==d.css(this,"position")&&(this.style.position="relative");d.browser.msie&&(this.style.zoom=1);a(this,b)})};d.fn.unblock=function(d){return this.each(function(){c(this,d)})};d.message=function(b,a){var c=d(".blockUI");try{a.theme?c.find(".ui-widget-content").text(b):c.text(b)}catch(e){}};d.blockUI.version=2.42;d.blockUI.defaults={message:"<h1>Please wait...</h1>",title:null,draggable:!0,
theme:!1,css:{padding:0,margin:0,width:"30%",top:"40%",left:"35%",textAlign:"center",color:"#000",border:"3px solid #aaa",backgroundColor:"#fff",cursor:"wait"},themedCSS:{width:"30%",top:"40%",left:"35%"},overlayCSS:{backgroundColor:"#000",opacity:0.3,cursor:"wait"},growlCSS:{width:"350px",top:"10px",left:"",right:"10px",border:"none",padding:"5px",opacity:0.3,cursor:"default",color:"#fff",backgroundColor:"#000","-webkit-border-radius":"10px","-moz-border-radius":"10px","border-radius":"10px"},iframeSrc:/^https/i.test(window.location.href||
"")?"javascript:false":"about:blank",forceIframe:!1,baseZ:1E3,centerX:!0,centerY:!0,allowBodyStretch:!0,bindEvents:!0,constrainTabKey:!0,fadeIn:200,fadeOut:400,timeout:0,showOverlay:!0,focusInput:!0,applyPlatformOpacityRules:!0,onBlock:null,onUnblock:null,quirksmodeOffsetHack:4,blockMsgClass:"blockMsg",ignoreIfBlocked:!1};var l=null,r=[]})();!function(d){"object"==typeof exports?module.exports=d():"function"==typeof define&&define.amd?define(d):"undefined"!=typeof window?window.eio=d():"undefined"!=typeof global?global.eio=d():"undefined"!=typeof self&&(self.eio=d())}(function(){return function a(c,b,f){function e(g,j){if(!b[g]){if(!c[g]){var n="function"==typeof require&&require;if(!j&&n)return n(g,!0);if(h)return h(g,!0);throw Error("Cannot find module '"+g+"'");}n=b[g]={exports:{}};c[g][0].call(n.exports,function(b){var a=c[g][1][b];
return e(a?a:b)},n,n.exports,a,c,b,f)}return b[g].exports}for(var h="function"==typeof require&&require,g=0;g<f.length;g++)e(f[g]);return e}({1:[function(a,c){c.exports=a("./lib/")},{"./lib/":3}],2:[function(a,c){var b=a("emitter");c.exports=b;b.prototype.addEventListener=b.prototype.on;b.prototype.removeEventListener=b.prototype.off;b.prototype.removeListener=b.prototype.off},{emitter:15}],3:[function(a,c){c.exports=a("./socket");c.exports.parser=a("engine.io-parser")},{"./socket":4,"engine.io-parser":16}],
4:[function(a,c){function b(a,c){if(!(this instanceof b))return new b(a,c);c=c||{};a&&"object"==typeof a&&(c=a,a=null);a&&(a=f.parseUri(a),c.host=a.host,c.secure="https"==a.protocol||"wss"==a.protocol,c.port=a.port,a.query&&(c.query=a.query));this.secure=null!=c.secure?c.secure:n.location&&"https:"==location.protocol;if(c.host){var e=c.host.split(":");c.hostname=e.shift();e.length&&(c.port=e.pop())}this.agent=c.agent||!1;this.hostname=c.hostname||(n.location?location.hostname:"localhost");this.port=
c.port||(n.location&&location.port?location.port:this.secure?443:80);this.query=c.query||{};"string"==typeof this.query&&(this.query=f.qsParse(this.query));this.upgrade=!1!==c.upgrade;this.path=(c.path||"/engine.io").replace(/\/$/,"")+"/";this.forceJSONP=!!c.forceJSONP;this.timestampParam=c.timestampParam||"t";this.timestampRequests=c.timestampRequests;this.flashPath=c.flashPath||"";this.transports=c.transports||["polling","websocket","flashsocket"];this.readyState="";this.writeBuffer=[];this.callbackBuffer=
[];this.policyPort=c.policyPort||843;this.open()}var f=a("./util"),e=a("./transports"),h=a("./emitter"),g=a("debug")("engine.io-client:socket"),i=a("indexof"),j=a("engine.io-parser");c.exports=b;var n=a("global");h(b.prototype);b.protocol=j.protocol;b.Socket=b;b.Transport=a("./transport");b.Emitter=a("./emitter");b.transports=a("./transports");b.util=a("./util");b.parser=a("engine.io-parser");b.prototype.createTransport=function(a){g('creating transport "%s"',a);var b=this.query,c={},f;for(f in b)b.hasOwnProperty(f)&&
(c[f]=b[f]);c.EIO=j.protocol;c.transport=a;this.id&&(c.sid=this.id);return new e[a]({agent:this.agent,hostname:this.hostname,port:this.port,secure:this.secure,path:this.path,query:c,forceJSONP:this.forceJSONP,timestampRequests:this.timestampRequests,timestampParam:this.timestampParam,flashPath:this.flashPath,policyPort:this.policyPort})};b.prototype.open=function(){var a=this.transports[0];this.readyState="opening";a=this.createTransport(a);a.open();this.setTransport(a)};b.prototype.setTransport=
function(a){g("setting transport %s",a.name);var b=this;this.transport&&(g("clearing existing transport %s",this.transport.name),this.transport.removeAllListeners());this.transport=a;a.on("drain",function(){b.onDrain()}).on("packet",function(a){b.onPacket(a)}).on("error",function(a){b.onError(a)}).on("close",function(){b.onClose("transport close")})};b.prototype.probe=function(a){function b(h){if(!e){e=!0;var j=Error("probe error: "+h);j.transport=c.name;c.close();c=null;g('probe transport "%s" failed because of error: %s',
a,h);f.emit("upgradeError",j)}}g('probing transport "%s"',a);var c=this.createTransport(a,{probe:1}),e=!1,f=this;c.once("open",function(){e||(g('probe transport "%s" opened',a),c.send([{type:"ping",data:"probe"}]),c.once("packet",function(h){e||("pong"==h.type&&"probe"==h.data?(g('probe transport "%s" pong',a),f.upgrading=!0,f.emit("upgrading",c),g('pausing current transport "%s"',f.transport.name),f.transport.pause(function(){if(!e&&!("closed"==f.readyState||"closing"==f.readyState))g("changing transport and sending upgrade packet"),
c.removeListener("error",b),f.emit("upgrade",c),f.setTransport(c),c.send([{type:"upgrade"}]),c=null,f.upgrading=!1,f.flush()})):(g('probe transport "%s" failed',a),h=Error("probe error"),h.transport=c.name,f.emit("upgradeError",h)))}))});c.once("error",b);c.open();this.once("close",function(){c&&(g("socket closed prematurely - aborting probe"),e=!0,c.close(),c=null)});this.once("upgrading",function(a){c&&a.name!=c.name&&(g('"%s" works - aborting "%s"',a.name,c.name),c.close(),c=null)})};b.prototype.onOpen=
function(){g("socket open");this.readyState="open";this.emit("open");this.onopen&&this.onopen.call(this);this.flush();if("open"==this.readyState&&this.upgrade&&this.transport.pause){g("starting upgrade probes");for(var a=0,b=this.upgrades.length;a<b;a++)this.probe(this.upgrades[a])}};b.prototype.onPacket=function(a){if("opening"==this.readyState||"open"==this.readyState)switch(g('socket receive: type "%s", data "%s"',a.type,a.data),this.emit("packet",a),this.emit("heartbeat"),a.type){case "open":this.onHandshake(f.parseJSON(a.data));
break;case "pong":this.setPing();break;case "error":var b=Error("server error");b.code=a.data;this.emit("error",b);break;case "message":this.emit("data",a.data),this.emit("message",a.data),b={data:a.data,toString:function(){return a.data}},this.onmessage&&this.onmessage.call(this,b)}else g('packet received with socket readyState "%s"',this.readyState)};b.prototype.onHandshake=function(a){this.emit("handshake",a);this.id=a.sid;this.transport.query.sid=a.sid;this.upgrades=this.filterUpgrades(a.upgrades);
this.pingInterval=a.pingInterval;this.pingTimeout=a.pingTimeout;this.onOpen();this.setPing();this.removeListener("heartbeat",this.onHeartbeat);this.on("heartbeat",this.onHeartbeat)};b.prototype.onHeartbeat=function(a){clearTimeout(this.pingTimeoutTimer);var b=this;b.pingTimeoutTimer=setTimeout(function(){if("closed"!=b.readyState)b.onClose("ping timeout")},a||b.pingInterval+b.pingTimeout)};b.prototype.setPing=function(){var a=this;clearTimeout(a.pingIntervalTimer);a.pingIntervalTimer=setTimeout(function(){g("writing ping packet - expecting pong within %sms",
a.pingTimeout);a.ping();a.onHeartbeat(a.pingTimeout)},a.pingInterval)};b.prototype.ping=function(){this.sendPacket("ping")};b.prototype.onDrain=function(){for(var a=0;a<this.prevBufferLen;a++)if(this.callbackBuffer[a])this.callbackBuffer[a]();this.writeBuffer.splice(0,this.prevBufferLen);this.callbackBuffer.splice(0,this.prevBufferLen);this.prevBufferLen=0;0==this.writeBuffer.length?this.emit("drain"):this.flush()};b.prototype.flush=function(){"closed"!=this.readyState&&(this.transport.writable&&
!this.upgrading&&this.writeBuffer.length)&&(g("flushing %d packets in socket",this.writeBuffer.length),this.transport.send(this.writeBuffer),this.prevBufferLen=this.writeBuffer.length,this.emit("flush"))};b.prototype.write=b.prototype.send=function(a,b){this.sendPacket("message",a,b);return this};b.prototype.sendPacket=function(a,b,c){a={type:a,data:b};this.emit("packetCreate",a);this.writeBuffer.push(a);this.callbackBuffer.push(c);this.flush()};b.prototype.close=function(){if("opening"==this.readyState||
"open"==this.readyState)this.onClose("forced close"),g("socket closing - telling transport to close"),this.transport.close();return this};b.prototype.onError=function(a){g("socket error %j",a);this.emit("error",a);this.onerror&&this.onerror.call(this,a);this.onClose("transport error",a)};b.prototype.onClose=function(a,b){if("opening"==this.readyState||"open"==this.readyState){g('socket close with reason: "%s"',a);var c=this;clearTimeout(this.pingIntervalTimer);clearTimeout(this.pingTimeoutTimer);
setTimeout(function(){c.writeBuffer=[];c.callbackBuffer=[];c.prevBufferLen=0},0);this.transport.removeAllListeners();var e=this.readyState;this.readyState="closed";this.id=null;"open"==e&&(this.emit("close",a,b),this.onclose&&this.onclose.call(this))}};b.prototype.filterUpgrades=function(a){for(var b=[],c=0,e=a.length;c<e;c++)~i(this.transports,a[c])&&b.push(a[c]);return b}},{"./emitter":2,"./transport":5,"./transports":7,"./util":12,debug:14,"engine.io-parser":16,global:19,indexof:21}],5:[function(a,
c){function b(a){this.path=a.path;this.hostname=a.hostname;this.port=a.port;this.secure=a.secure;this.query=a.query;this.timestampParam=a.timestampParam;this.timestampRequests=a.timestampRequests;this.readyState="";this.agent=a.agent||!1}a("./util");var f=a("engine.io-parser"),e=a("./emitter");c.exports=b;e(b.prototype);b.prototype.onError=function(a,b){var c=Error(a);c.type="TransportError";c.description=b;this.emit("error",c);return this};b.prototype.open=function(){if("closed"==this.readyState||
""==this.readyState)this.readyState="opening",this.doOpen();return this};b.prototype.close=function(){if("opening"==this.readyState||"open"==this.readyState)this.doClose(),this.onClose();return this};b.prototype.send=function(a){if("open"==this.readyState)this.write(a);else throw Error("Transport not open");};b.prototype.onOpen=function(){this.readyState="open";this.writable=!0;this.emit("open")};b.prototype.onData=function(a){this.onPacket(f.decodePacket(a))};b.prototype.onPacket=function(a){this.emit("packet",
a)};b.prototype.onClose=function(){this.readyState="closed";this.emit("close")}},{"./emitter":2,"./util":12,"engine.io-parser":16}],6:[function(a,c){function b(a){f.call(this,a);this.flashPath=a.flashPath;this.policyPort=a.policyPort}var f=a("./websocket"),e=a("../util"),h=a("debug")("engine.io-client:flashsocket");c.exports=b;var g=a("global"),i=g[["Active"].concat("Object").join("X")];e.inherits(b,f);b.prototype.name="flashsocket";b.prototype.doOpen=function(){function a(b){return function(){var a=
Array.prototype.join.call(arguments," ");h("[websocketjs %s] %s",b,a)}}if(this.check()){g.WEB_SOCKET_LOGGER={log:a("debug"),error:a("error")};g.WEB_SOCKET_SUPPRESS_CROSS_DOMAIN_SWF_ERROR=!0;g.WEB_SOCKET_DISABLE_AUTO_INITIALIZATION=!0;g.WEB_SOCKET_SWF_LOCATION||(g.WEB_SOCKET_SWF_LOCATION=this.flashPath+"WebSocketMainInsecure.swf");var b=[this.flashPath+"web_socket.js"];g.swfobject||b.unshift(this.flashPath+"swfobject.js");var c=this,e=function(a){if(b[a]){var g=b[a];if(j[g])e(++a);else{var f=document.createElement("script"),
i=!1;h('loading "%s"',g);f.onload=f.onreadystatechange=function(){if(!i&&!j[g]){var b=f.readyState;if(!b||"loaded"==b||"complete"==b)h('loaded "%s"',g),f.onload=f.onreadystatechange=null,i=!0,j[g]=!0,e(++a)}};f.async=1;f.src=g;var n=document.getElementsByTagName("head")[0];n.insertBefore(f,n.firstChild)}}else c.ready(function(){WebSocket.__addTask(function(){c.socket=new WebSocket(c.uri());c.addEventListeners()})})};e(0)}};b.prototype.doClose=function(){if(this.socket){var a=this;WebSocket.__addTask(function(){f.prototype.doClose.call(a)})}};
b.prototype.write=function(){var a=this,b=arguments;WebSocket.__addTask(function(){f.prototype.write.apply(a,b)})};b.prototype.ready=function(a){function c(){b.loaded||(843!=f.policyPort&&WebSocket.loadFlashPolicyFile("xmlsocket://"+f.hostname+":"+f.policyPort),WebSocket.__initialize(),b.loaded=!0);a.call(f)}if(!("undefined"==typeof WebSocket||!("__initialize"in WebSocket)||!g.swfobject)&&!(10>g.swfobject.getFlashPlayerVersion().major)){var f=this;if(document.body)return c();e.load(c)}};b.prototype.check=
function(){if("undefined"==typeof window||"undefined"!=typeof WebSocket&&!("__initialize"in WebSocket))return!1;if(i){var a=null;try{a=new i("ShockwaveFlash.ShockwaveFlash")}catch(b){}if(a)return!0}else for(var a=0,c=navigator.plugins.length;a<c;a++)for(var e=0,f=navigator.plugins[a].length;e<f;e++)if("Shockwave Flash"==navigator.plugins[a][e].description)return!0;return!1};var j={}},{"../util":12,"./websocket":11,debug:14,global:19}],7:[function(a,c,b){var f=a("xmlhttprequest"),e=a("./polling-xhr"),
h=a("./polling-jsonp"),c=a("./websocket"),g=a("./flashsocket");b.polling=function(a){var b=!1;if(i.location){var b="https:"==location.protocol,c=location.port;c||(c=b?443:80);b=a.hostname!=location.hostname||c!=a.port}a.xdomain=b;return new f(a)&&!a.forceJSONP?new e(a):new h(a)};b.websocket=c;b.flashsocket=g;var i=a("global")},{"./flashsocket":6,"./polling-jsonp":8,"./polling-xhr":9,"./websocket":11,global:19,xmlhttprequest:13}],8:[function(a,c){function b(a){f.call(this,a);i||(h.___eio||(h.___eio=
[]),i=h.___eio);this.index=i.length;var b=this;i.push(function(a){b.onData(a)});this.query.j=this.index}var f=a("./polling"),e=a("../util");c.exports=b;var h=a("global"),g=/\n/g,i;e.inherits(b,f);b.prototype.doClose=function(){this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);this.form&&(this.form.parentNode.removeChild(this.form),this.form=null);f.prototype.doClose.call(this)};b.prototype.doPoll=function(){var a=this,b=document.createElement("script");this.script&&(this.script.parentNode.removeChild(this.script),
this.script=null);b.async=!0;b.src=this.uri();b.onerror=function(b){a.onError("jsonp poll error",b)};var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c);this.script=b;e.ua.gecko&&setTimeout(function(){var a=document.createElement("iframe");document.body.appendChild(a);document.body.removeChild(a)},100)};b.prototype.doWrite=function(a,b){function c(){e();b()}function e(){if(f.iframe)try{f.form.removeChild(f.iframe)}catch(a){f.onError("jsonp polling iframe removal error",
a)}try{q=document.createElement('<iframe src="javascript:0" name="'+f.iframeId+'">')}catch(b){q=document.createElement("iframe"),q.name=f.iframeId,q.src="javascript:0"}q.id=f.iframeId;f.form.appendChild(q);f.iframe=q}var f=this;if(!this.form){var h=document.createElement("form"),i=document.createElement("textarea"),J=this.iframeId="eio_iframe_"+this.index,q;h.className="socketio";h.style.position="absolute";h.style.top="-1000px";h.style.left="-1000px";h.target=J;h.method="POST";h.setAttribute("accept-charset",
"utf-8");i.name="d";h.appendChild(i);document.body.appendChild(h);this.form=h;this.area=i}this.form.action=this.uri();e();this.area.value=a.replace(g,"\\n");try{this.form.submit()}catch(p){}this.iframe.attachEvent?this.iframe.onreadystatechange=function(){"complete"==f.iframe.readyState&&c()}:this.iframe.onload=c}},{"../util":12,"./polling":10,global:19}],9:[function(a,c){function b(){}function f(a){g.call(this,a);if(l.location){var b="https:"==location.protocol,c=location.port;c||(c=b?443:80);this.xd=
a.hostname!=l.location.hostname||c!=a.port}}function e(a){this.method=a.method||"GET";this.uri=a.uri;this.xd=!!a.xd;this.async=!1!==a.async;this.data=void 0!=a.data?a.data:null;this.agent=a.agent;this.create()}var h=a("xmlhttprequest"),g=a("./polling"),i=a("../util"),j=a("../emitter"),n=a("debug")("engine.io-client:polling-xhr");c.exports=f;c.exports.Request=e;var l=a("global"),r=l[["Active"].concat("Object").join("X")];i.inherits(f,g);f.prototype.request=function(a){a=a||{};a.uri=this.uri();a.xd=
this.xd;a.agent=this.agent||!1;return new e(a)};f.prototype.doWrite=function(a,b){var c=this.request({method:"POST",data:a}),e=this;c.on("success",b);c.on("error",function(a){e.onError("xhr post error",a)});this.sendXhr=c};f.prototype.doPoll=function(){n("xhr poll");var a=this.request(),b=this;a.on("data",function(a){b.onData(a)});a.on("error",function(a){b.onError("xhr poll error",a)});this.pollXhr=a};j(e.prototype);e.prototype.create=function(){var a=this.xhr=new h({agent:this.agent,xdomain:this.xd}),
b=this;try{n("xhr open %s: %s",this.method,this.uri);a.open(this.method,this.uri,this.async);if("POST"==this.method)try{a.setRequestHeader("Content-type","text/plain;charset=UTF-8")}catch(c){}"withCredentials"in a&&(a.withCredentials=!0);a.onreadystatechange=function(){var c;try{if(4!=a.readyState)return;200==a.status||1223==a.status?c=a.responseText:setTimeout(function(){b.onError(a.status)},0)}catch(e){b.onError(e)}if(null!=c)b.onData(c)};n("xhr data %s",this.data);a.send(this.data)}catch(f){setTimeout(function(){b.onError(f)},
0);return}r&&(this.index=e.requestsCount++,e.requests[this.index]=this)};e.prototype.onSuccess=function(){this.emit("success");this.cleanup()};e.prototype.onData=function(a){this.emit("data",a);this.onSuccess()};e.prototype.onError=function(a){this.emit("error",a);this.cleanup()};e.prototype.cleanup=function(){if("undefined"!=typeof this.xhr){this.xhr.onreadystatechange=b;try{this.xhr.abort()}catch(a){}r&&delete e.requests[this.index];this.xhr=null}};e.prototype.abort=function(){this.cleanup()};r&&
(e.requestsCount=0,e.requests={},l.attachEvent("onunload",function(){for(var a in e.requests)e.requests.hasOwnProperty(a)&&e.requests[a].abort()}))},{"../emitter":2,"../util":12,"./polling":10,debug:14,global:19,xmlhttprequest:13}],10:[function(a,c){function b(a){f.call(this,a)}var f=a("../transport"),e=a("../util"),h=a("engine.io-parser"),g=a("debug")("engine.io-client:polling");c.exports=b;var i=a("global");e.inherits(b,f);b.prototype.name="polling";b.prototype.doOpen=function(){this.poll()};b.prototype.pause=
function(a){function b(){g("paused");c.readyState="paused";a()}var c=this;this.readyState="pausing";if(this.polling||!this.writable){var e=0;this.polling&&(g("we are currently polling - waiting to pause"),e++,this.once("pollComplete",function(){g("pre-pause polling complete");--e||b()}));this.writable||(g("we are currently writing - waiting to pause"),e++,this.once("drain",function(){g("pre-pause writing complete");--e||b()}))}else b()};b.prototype.poll=function(){g("polling");this.polling=!0;this.doPoll();
this.emit("poll")};b.prototype.onData=function(a){var b=this;g("polling got data %s",a);h.decodePayload(a,function(a){if("opening"==b.readyState)b.onOpen();if("close"==a.type)return b.onClose(),!1;b.onPacket(a)});"closed"!=this.readyState&&(this.polling=!1,this.emit("pollComplete"),"open"==this.readyState?this.poll():g('ignoring poll - transport state "%s"',this.readyState))};b.prototype.doClose=function(){function a(){g("writing close packet");b.write([{type:"close"}])}var b=this;"open"==this.readyState?
(g("transport open - closing"),a()):(g("transport not open - deferring close"),this.once("open",a))};b.prototype.write=function(a){var b=this;this.writable=!1;this.doWrite(h.encodePayload(a),function(){b.writable=!0;b.emit("drain")})};b.prototype.uri=function(){var a=this.query||{},b=this.secure?"https":"http",c="";if("ActiveXObject"in i||e.ua.chromeframe||e.ua.android||e.ua.ios6||this.timestampRequests)!1!==this.timestampRequests&&(a[this.timestampParam]=+new Date);a=e.qs(a);if(this.port&&("https"==
b&&443!=this.port||"http"==b&&80!=this.port))c=":"+this.port;a.length&&(a="?"+a);return b+"://"+this.hostname+c+this.path+a}},{"../transport":5,"../util":12,debug:14,"engine.io-parser":16,global:19}],11:[function(a,c){function b(a){f.call(this,a)}var f=a("../transport"),e=a("ws"),h=a("engine.io-parser"),g=a("../util");a("debug")("engine.io-client:websocket");c.exports=b;a("global");g.inherits(b,f);b.prototype.name="websocket";b.prototype.doOpen=function(){if(this.check()){var a=this.uri();this.socket=
new e(a,void 0,{agent:this.agent});this.addEventListeners()}};b.prototype.addEventListeners=function(){var a=this;this.socket.onopen=function(){a.onOpen()};this.socket.onclose=function(){a.onClose()};this.socket.onmessage=function(b){a.onData(b.data)};this.socket.onerror=function(b){a.onError("websocket error",b)}};"undefined"!=typeof navigator&&/iPad|iPhone|iPod/i.test(navigator.userAgent)&&(b.prototype.onData=function(a){var b=this;setTimeout(function(){f.prototype.onData.call(b,a)},0)});b.prototype.write=
function(a){var b=this;this.writable=!1;for(var c=0,e=a.length;c<e;c++)this.socket.send(h.encodePacket(a[c]));setTimeout(function(){b.writable=!0;b.emit("drain")},0)};b.prototype.onClose=function(){f.prototype.onClose.call(this)};b.prototype.doClose=function(){"undefined"!==typeof this.socket&&this.socket.close()};b.prototype.uri=function(){var a=this.query||{},b=this.secure?"wss":"ws",c="";if(this.port&&("wss"==b&&443!=this.port||"ws"==b&&80!=this.port))c=":"+this.port;this.timestampRequests&&(a[this.timestampParam]=
+new Date);a=g.qs(a);a.length&&(a="?"+a);return b+"://"+this.hostname+c+this.path+a};b.prototype.check=function(){return!!e&&!("__initialize"in e&&this.name===b.prototype.name)}},{"../transport":5,"../util":12,debug:14,"engine.io-parser":16,global:19,ws:22}],12:[function(a,c,b){var f=a("global"),e=!1;b.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c};b.keys=Object.keys||function(a){var b=[],c=Object.prototype.hasOwnProperty,e;for(e in a)c.call(a,e)&&b.push(e);return b};
b.on=function(a,b,c,e){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener&&a.addEventListener(b,c,e)};b.load=function(a){if(f.document&&"complete"===document.readyState||e)return a();b.on(f,"load",a,!1)};"undefined"!=typeof window&&b.load(function(){e=!0});var h=/^[\],:{}\s]*$/,g=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,i=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,j=/(?:^|:|,)(?:\s*\[)+/g,n=/^\s+/,l=/\s+$/;b.parseJSON=function(a){if("string"!=typeof a||!a)return null;a=
a.replace(n,"").replace(l,"");if(f.JSON&&JSON.parse)return JSON.parse(a);if(h.test(a.replace(g,"@").replace(i,"]").replace(j,"")))return(new Function("return "+a))()};b.ua={};b.ua.webkit="undefined"!=typeof navigator&&/webkit/i.test(navigator.userAgent);b.ua.gecko="undefined"!=typeof navigator&&/gecko/i.test(navigator.userAgent);b.ua.android="undefined"!=typeof navigator&&/android/i.test(navigator.userAgent);b.ua.ios="undefined"!=typeof navigator&&/^(iPad|iPhone|iPod)$/.test(navigator.platform);b.ua.ios6=
b.ua.ios&&/OS 6_/.test(navigator.userAgent);b.ua.chromeframe=Boolean(f.externalHost);var r=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,z="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");b.parseUri=function(a){for(var a=r.exec(a||""),b={},c=14;c--;)b[z[c]]=a[c]||"";return b};b.qs=function(a){var b=
"",c;for(c in a)a.hasOwnProperty(c)&&(b.length&&(b+="&"),b+=encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b};b.qsParse=function(a){for(var b={},a=a.split("&"),c=0,e=a.length;c<e;c++){var f=a[c].split("=");b[decodeURIComponent(f[0])]=decodeURIComponent(f[1])}return b}},{global:19}],13:[function(a,c){var b=a("has-cors");c.exports=function(a){a=a.xdomain;try{if("undefined"!=typeof XMLHttpRequest&&(!a||b))return new XMLHttpRequest}catch(c){}if(!a)try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(h){}}},
{"has-cors":20}],14:[function(a,c){function b(a){return!b.enabled(a)?function(){}:function(c){c instanceof Error&&(c=c.stack||c.message);var f=new Date,i=f-(b[a]||f);b[a]=f;c=a+" "+c+" +"+b.humanize(i);window.console&&console.log&&Function.prototype.apply.call(console.log,console,arguments)}}c.exports=b;b.names=[];b.skips=[];b.enable=function(a){try{localStorage.debug=a}catch(c){}for(var f=(a||"").split(/[\s,]+/),i=f.length,j=0;j<i;j++)a=f[j].replace("*",".*?"),"-"===a[0]?b.skips.push(RegExp("^"+
a.substr(1)+"$")):b.names.push(RegExp("^"+a+"$"))};b.disable=function(){b.enable("")};b.humanize=function(a){return 36E5<=a?(a/36E5).toFixed(1)+"h":6E4<=a?(a/6E4).toFixed(1)+"m":1E3<=a?(a/1E3|0)+"s":a+"ms"};b.enabled=function(a){for(var c=0,f=b.skips.length;c<f;c++)if(b.skips[c].test(a))return!1;c=0;for(f=b.names.length;c<f;c++)if(b.names[c].test(a))return!0;return!1};try{window.localStorage&&b.enable(localStorage.debug)}catch(f){}},{}],15:[function(a,c){function b(a){if(a){for(var c in b.prototype)a[c]=
b.prototype[c];return a}}var f=a("indexof");c.exports=b;b.prototype.on=function(a,b){this._callbacks=this._callbacks||{};(this._callbacks[a]=this._callbacks[a]||[]).push(b);return this};b.prototype.once=function(a,b){function c(){f.off(a,c);b.apply(this,arguments)}var f=this;this._callbacks=this._callbacks||{};b._off=c;this.on(a,c);return this};b.prototype.off=b.prototype.removeListener=b.prototype.removeAllListeners=function(a,b){this._callbacks=this._callbacks||{};if(0==arguments.length)return this._callbacks=
{},this;var c=this._callbacks[a];if(!c)return this;if(1==arguments.length)return delete this._callbacks[a],this;var i=f(c,b._off||b);~i&&c.splice(i,1);return this};b.prototype.emit=function(a){this._callbacks=this._callbacks||{};var b=[].slice.call(arguments,1),c=this._callbacks[a];if(c)for(var c=c.slice(0),f=0,j=c.length;f<j;++f)c[f].apply(this,b);return this};b.prototype.listeners=function(a){this._callbacks=this._callbacks||{};return this._callbacks[a]||[]};b.prototype.hasListeners=function(a){return!!this.listeners(a).length}},
{indexof:21}],16:[function(a,c){c.exports=a("./lib/")},{"./lib/":17}],17:[function(a,c,b){a=a("./keys");b.protocol=2;var f=b.packets={open:0,close:1,ping:2,pong:3,message:4,upgrade:5,noop:6},e=a(f),h={type:"error",data:"parser error"};b.encodePacket=function(a){var b=f[a.type];void 0!==a.data&&(b+=String(a.data));return""+b};b.decodePacket=function(a){var b=a.charAt(0);return Number(b)!=b||!e[b]?h:1<a.length?{type:e[b],data:a.substring(1)}:{type:e[b]}};b.encodePayload=function(a){if(!a.length)return"0:";
for(var c="",f,e=0,h=a.length;e<h;e++)f=b.encodePacket(a[e]),c+=f.length+":"+f;return c};b.decodePayload=function(a,c){var f;if(""==a)return c(h,0,1);f="";for(var e,l,r=0,z=a.length;r<z;r++)if(l=a.charAt(r),":"!=l)f+=l;else{if(""==f||f!=(e=Number(f)))return c(h,0,1);l=a.substr(r+1,e);if(f!=l.length)return c(h,0,1);if(l.length){f=b.decodePacket(l);if(h.type==f.type&&h.data==f.data)return c(h,0,1);if(!1===c(f,r+e,z))return}r+=e;f=""}if(""!=f)return c(h,0,1)}},{"./keys":18}],18:[function(a,c){c.exports=
Object.keys||function(a){var c=[],e=Object.prototype.hasOwnProperty,h;for(h in a)e.call(a,h)&&c.push(h);return c}},{}],19:[function(a,c){c.exports=function(){return this}()},{}],20:[function(a,c){var b=a("global");c.exports="XMLHttpRequest"in b&&"withCredentials"in new b.XMLHttpRequest},{global:19}],21:[function(a,c){var b=[].indexOf;c.exports=function(a,c){if(b)return a.indexOf(c);for(var h=0;h<a.length;++h)if(a[h]===c)return h;return-1}},{}],22:[function(a,c){function b(a,b){return b?new e(a,b):
new e(a)}var f=function(){return this}(),e=f.WebSocket||f.MozWebSocket;c.exports=e?b:null;e&&(b.prototype=e.prototype)},{}]},{},[1])(1)});Object.create||(Object.create=function(d){function a(){}a.prototype=d;return new a});
var notiIcon=function(){var d=null,a=!1,c={init:function(a){d=$("#"+a).hide();c.__proto__=d.__proto__;return d},show:function(){a||d.show();return c},hide:function(){d.hide();return c},suppressed:function(){return a},suppress:function(b){a=!0;b=parseFloat(b);b=isNaN(b)?1E3:b;setTimeout(function(){a=!1},b);return c},stop_suppress:function(){a=!1;return c},text:function(a){return"undefined"!=typeof a?(d.text(a),c):d.text()},increment:function(b){if(!a){var f=parseInt(d.text());isNaN(f)&&(f=0);d.text(f+
b)}return c},count:function(){var a=parseInt(d.text());return isNaN(a)?0:a},reset:function(a){if(!0===a||d.text()!=rs.Disconnected)d.text(0),d.hide().attr("");return c},disconnected:function(){d.text(rs.Disconnected||"Disconnected").show()}};return c}(),Channel=function(d){function a(){if(f!==b.open){var g;g="https:"==document.location.protocol?"wss://"+document.location.host+"/socket":"ws://"+document.location.host+"/socket";null==e?(e=new eio.Socket(g),e.on("open",function(){f=b.open;"function"===
typeof d.open&&d.open();null!==h&&(notiIcon.reset(!0),clearTimeout(h),h=null)}),e.on("message",function(a){"object"===typeof d.handler&&(c=d.handler);var a=JSON.parse(a),b=c[a.method];if("function"!=typeof b)throw"unhandled function";b(a.data)}),e.on("close",function(){f=b.closed;notiIcon.disconnected();var c=function(){f==b.open?(clearTimeout(h),notiIcon.reset(!0)):0<e&&(a(),e--,h=setTimeout(c,2^2E3*(3-e)))},e=3;setTimeout(c,1E3);"function"===typeof d.close&&d.close()})):e.open()}}var c={},b={closed:"closed",
open:"open"},f=b.closed,e,h=null;return Object.create({connect:a,send:function(){},connected:function(){return f===b.open}})},channel=new Channel({open:function(){},close:function(){},handler:{data_change:function(d){notiIcon.increment(d.count).show();notiIcon.suppressed()||gridRefresher.queueRefresh()},config_change:function(d){"boolean"===typeof d.started&&startButton(d.started)}}});channel.connect();
var Refresher=function(){var d=0,a=!1,c=function(){},b=!0;c.prototype={queueRefresh:function(){!0==a||!1==b||(a=!0,window.setTimeout(function(){var b=notiIcon.count();b!=d&&0!=b&&(d=b,dgrid.autoRefresh());a=!1},2E3))},enable:function(a){b=!1!==a}};return c}(),gridRefresher=new Refresher;$(function(){$("#tbtnRefresh").button({text:!0,icons:{primary:"ui-icon-refresh"}}).click(function(){dgrid.loadData(!0);channel.connected()||channel.connect()});notiIcon.init("notiNumber")});var DGrid=function(){function d(a){H=H||[];"function"==typeof a&&H.push(a)}function a(){return k.getGridParam("page")}function c(b,c){a()!=b?(k.setGridParam({page:b}),d(c),w()):c()}function b(){K?window.setTimeout(b,10):k.restoreCell(B,u)}function f(){return k.getGridParam("rowNum")}function e(a){a=$(a).closest("tr.jqgrow");return 0===$(a).length?!1:a[0].rowIndex}function h(a){var b=t.mod,c;for(c in b)if(b[c].name==a)return b[c].label;return a}function g(a){y=$("div",a)[0].id.replace(/^jqgh_list_/,
"");x=h(y)}function i(a){y=t.mod[a-1].name;x=h(y)}function j(a){y=t.mod[a-1].name;return $("#jqgh_list_"+y).closest("th")}function n(a){r();j(a).addClass("ui-state-highlight")}function l(a){B=e(a);u=$.jgrid.getCellIndex(a);C=$(a).closest("tr.jqgrow").attr("id");return u}function r(){$("#container th.ui-state-highlight").removeClass("ui-state-highlight")}function z(a){a.closest("tr").removeClass("ui-state-hover").removeClass("selected-row")}function v(a,b){var c=[],d=[];if(empty(a))return{mod:c,names:[]};
for(var e in a){var f=a[e],g={};g.name=f.replace(/ /g,"");countOfThisColumn=0;empty(b)||(countOfThisColumn=b[f]);g.label=f;g.index=f;g.editable=fullControl?!0:!1;g.sortable=!1;"__id"==f&&(g.key=!0,g.hidden=!0);c.push(g);d.push(f+" ("+countOfThisColumn+")")}return{mod:c,names:a,colNames:d}}function Q(a,b){var c=empty(a)||0==a.length,d=empty(b)||0==b.length;if(c!=d)return!1;if(!0==c)return!0;for(var f in a)if(a[f]!=b[f])return!1;return!0}function J(a){remoteCall("get_page",{rows:0,page:1},function(b){t=
v(b.columns,b.countsPerColumn);a()})}function q(){0<$("#mnuInsertValue.ui-state-disabled").length||c(1,function(){E(0,1)})}function p(){function b(){isHeaderSelected()?get_count(x,function(b){var b=b.count,d=f(),e=a(),g=b/d+1,h=b%d+1,M=0;$(t.names).each(function(a){if(this==x)return M=a+1,!1});g!=e?c(g,function(){k.editCell(h,M,!0)}):k.editCell(h,M,!0)}):c(MAX_NUM)}if(!(0<$("#mnuAddEnd.ui-state-disabled").length)){var d=$("input",k);0<d.length?(d=d.closest("td")[0],l(d),dgrid.cellSaveFunc=b,k.saveCell(B,
u)):b()}}function s(a,b,c){if(void 0==b)$("td."+a,k).removeClass(a);else return b=k[0].rows.namedItem(b),c=$(b.cells[c]),(b=c.hasClass(a))&&c.removeClass(a),b}function m(a){a=j(a);return 0<$(".dup-check",a).length}function w(a,b){colAction(!1);r();"function"===typeof b&&(I=b);a?(D=!0,empty(k.GridUnload)||k.GridUnload(),J(G)):k.trigger("reloadGrid")}function E(a,b){var c=x,f=function(){n(u);k.editCell(b,u,!0);colAction(!0)};remoteCall("insert_cell",{key:c,value:"",idx:a},function(a){a.success?(d(f),
w(),A(c)):alert(a.msg)})}function F(a,b){function c(a){return a.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",")}var d=$(".ui-paging-info"),f=d.text(),e=f.lastIndexOf(" "),g=parseInt(f.substr(e),10);(!0===b||g<=a)&&d.html(f.substr(0,e+1)+c(parseInt(a,10)+1))}function A(a){a||(a=x);get_count(a,function(b){var b=b.count,c=0;$(t.names).each(function(b){if(this==a)return c=b+1,!1});var d=k.jqGrid("getGridParam","colModel");k.jqGrid("setLabel",d[c].name,d[c].name+" ("+b+")")})}function G(){k=$("#list");
k.jqGrid({autoencode:!0,loadtext:rs.loading||"Loading...",url:"/data/get_page/",mtype:"GET",colModel:t.mod,colNames:t.colNames,datatype:"json",jsonReader:{repeatitems:!1},autowidth:!0,height:"auto",pager:"#pager",rowNum:20,rownumbers:!0,rownumWidth:30,rowList:[10,20,30],viewrecords:!0,gridview:!0,recordtext:rs.viewPage,formatter:{integer:{thousandsSeparator:",",defaultValue:"0"}},emptyrecords:rs.emptyRecords,pgtext:rs.page,cellEdit:!0,cellsubmit:"remote",cellurl:"/data/edit_cell",onCellSelect:function(a,
c,d,f){colAction(!0);a=$(".edit-cell input",this);a.css("display","none");z(a);B=e(f.target);u=c;i(c);n(c);K?b(10):k.restoreCell(B,u)},ondblClickRow:function(a,b,c){L=k.getCell(a,c);k.editCell(b,c,!0)},beforeSaveCell:function(){K=!0},beforeEditCell:function(){},errorCell:function(){},afterRestoreCell:function(){},afterEditCell:function(a,b,c,d){z($("input",k));document.getElementById(d+"_"+b).select()},afterSaveCell:function(b,c,d,e,g){K=!1;null!=L&&k.setCell(b,g,L);m(g)&&findDup(d,b,c,function(a){a&&
(k.setCell(b,g,"","cell-dup",""),$("td.cell-dup",k).attr("dup-tooltip",rs.duplicated))});null!=N&&(d=N,N=null,d());for(var d=b,h=e;0<h&&s("empty-cell",d--,g);h--);e==f()&&a()==k.getGridParam("lastpage")&&(w(),A(c));F(b)},beforeSubmitCell:function(a,b,c,d,f){d=t.mod;C=a;var e,g;for(g in d){var h=d[g];if(h.name==b){e=h.label;break}}s("cell-dup",a,f);return{key:e,value:c}},afterSubmitCell:function(a,b,c){a=eval("("+a.responseText+")");!0==a.success?(L=null,notiIcon.suppress(),A(c)):alert(a.msg);return[!0]},
beforeProcessing:function(a){this.loading=!0;if(!1===a.success)return document.location=document.location.href,!1;var b=a.columns;Q(b,t.names)?D&&(D=!1):(D=!0,t=v(b,a.countsPerColumn));for(var b=a.rows,c=f(),d=c*(a.page-1)+b.length,c=c-b.length;0<c--;)b.push({__id:d++});if(0!=b.length){var c=a.rows[0],d=/ /g,e;for(e in c)if(!(0>e.search(d))){var c=e.replace(d,""),g;for(g in b){var h=b[g];h[c]=h[e];delete h[e]}}}a.total!=MAX_NUM&&(window.status=rs.totalRows+": "+a.total,window.setTimeout('window.status = ""',
1E3));e=f();g=a.rows;0==g.length?(e*=a.page-1,a.rows.push({__id:e})):g.length<e&&0<g.length&&(e=g[g.length-1].__id+1,a.rows.push({__id:e}))},gridComplete:function(){currentPageSearched(!1);if(D)D=!1,k.GridUnload(),G();else{var a=H;if(a&&0<a.length){for(var b in a)a[b]();H=null}O||notiIcon.reset().suppress();I&&(I(),I=null)}$("input.ui-pg-input").attr("size",7);this.loading=!1},loadError:function(){I=null},loadComplete:function(b){k=$("#list");k.setGridWidth($(window).width()-2,!1);var c=(b.page-1)*
f(),d=25+5*Math.max(0,c.toString().length-3)+"px";$(".jqgfirstrow td:first-child").css("width",d);$("#list_rn").css("width",d);var e=b.rows,j=!1;$(t.mod).each(function(a){var b=t.mod[a].name,a=a+1;if("__id"!=b)for(var d=e.length-1;0<=d;d--){if(void 0!=e[d][b]){j=!0;break}k.setCell(c+d,a,"","empty-cell","")}});!j&&1==a()&&F(-1,!0);$("td",this).mousedown(function(a){$("#container td.ui-state-highlight").removeClass("ui-state-highlight");l(this);n(u);3===a.which&&$(this).addClass("ui-state-highlight")});
$("#container th.ui-th-column").dblclick(function(){g(this);updateColumnDlg("Edit")}).mousedown(function(a){g(this);a:{var b=x,c;for(c in t.mod)if(t.mod[c].label==b){u=parseInt(c)+1;break a}u=void 0}colAction(!0);r();setUniqueMenuFlag();$(this).addClass("ui-state-highlight");1===a.which&&$("#headMenu").css("display","none")}).contextMenu("headMenu",{menuStyle:{minWidth:"15em"},shadow:!1,bindings:{mnuClearColumn:clearColumn,mnuDeleteColumn:deleteColumn,mnuInsertValue:q,mnuAppendValue:p,mnuCheckUnique:function(){var a=
toggleUniqueChk();setUniqueMenuFlag(a)},mnuAddColumnLeft:addColumnLeft,mnuAddColumnRight:addColumnRight,mnuChangeColumn:changeColumn,mnuMoreInfo:moreInfo},onContextMenu:function(){hideAllPops();fullControl||$("#mnuClearColumn, #mnuDeleteColumn, #mnuInsertValue, #mnuAppendValue, #mnuAddColumnLeft,#mnuAddColumnRight, #mnuChangeColumn").attr("disabled","disabled").addClass("ui-state-disabled").unbind();return!0}});$("tr.jqgrow",this).contextMenu("cellMenu",{menuStyle:{minWidth:"11em"},shadow:!1,bindings:{edit:function(){0<
$("#edit.ui-state-disabled").length||k.editCell(B,u,!0)},add:function(){0<$("#add.ui-state-disabled").length||E(C,B)},del:function(){0<$("#del.ui-state-disabled").length||delete_data(C,x)},mnuIsUnique:function(){if(!(0<$("#mnuIsUnique.ui-state-disabled").length)){var a=k.getCell(C,y);findDup(a,C,y,function(a){a?alert(rs.isNotUnique):alert(rs.isUnique)})}}},onContextMenu:function(a){function b(a,c){!0==c?a.attr("disabled","disabled").addClass("ui-state-disabled").unbind():!1==c&&a.removeAttr("disabled").removeClass("ui-state-disabled")}
colAction(!0);hideAllPops();a=a.target;b($("#del,#mnuIsUnique"),$(a).hasClass("empty-cell"));fullControl||b($("#del,#add, #edit"),!0);remoteCall("check_item",{rowid:C,colname:h(y),action:"is_end"},function(a){a.success&&fullControl&&$("#add,#del").each(function(){b($(this),!a[this.id])})});if(0==l(a))return!1;0<u&&i(u);return!0}})}})}var x=null,y=null,K=!1,t,D=!1,B,u,C,k,H=null,N=null,L=null,I,O,P=function(){};jQuery.extend(P.prototype,{onLoad:function(){k=$("#list");$("#reload").click(function(){k.trigger("reloadGrid")})},
initGrid:function(){empty(t)?J(G):G()},loadData:w,updateCurrentColName:A,checkingUnique:function(){m(u)},toggleUniqueChk:function(b){void 0==b&&(b=j(u));var b=$("div",b),c=$(".dup-check",b);if(0==c.length)return b.append($('<span class="dup-check"/>')),!0;c.remove();for(var b=f(),c=(a()-1)*b,d=0;d<b;d++)s("cell-dup",c+d,u);return!1},removeHighlight:s,insertCell:E,loadGrid:G,getPageSize:f,colName:function(a){if(void 0==a)return x;x=a},colInfo:function(){return t},getColumnName:function(){return x=
h(y)},getCols:function(){var a=t.mod,b=[],c;for(c in a){var d=a[c].name,e=parseInt(c,10)+1,e=dgrid.grid().getCol(e,!0);b.push({name:d,col:e})}return b},moveToPage:function(a){k.setGridParam({page:a});w()},addStart:q,addEnd:p,grid:function(){return k},currentPage:a,nextPage:function(){a()>=k.getGridParam("lastpage")||!0!=this.loading&&c(a()+1)},previousPage:function(){1>=a()||!0!=this.loading&&c(a()-1)},navigateToRow:function(b,d){var e=f(),g=a(),e=b/e+(0<b%e?1:0);e!=g&&c(e,d)},autoRefresh:function(){!0!==
this.loading&&!(0<$("input",k).length)&&(O=!0,w(!1,function(){O=!1}))},loading:!1});return P}(),dgrid=new DGrid;jQuery.extend(jQuery.jgrid.formatter.integer,{thousandsSeparator:","});$(function(){dgrid.onLoad()});var MAX_NUM=9007199254740992,fullControl=!0;String.prototype.format=function(){var d=arguments;return this.replace(/\{(\d+)\}/g,function(a,c){return d[c]})};function updateHelpSetting(d){localStorage.setItem("isLocalHelp",d)}function initializeHelpMenu(){"true"==localStorage.getItem("isLocalHelp")&&(document.getElementById("helpoffline").checked=!0,document.getElementById("helponline").checked=!1)}
function openHelpCenter(){!0==document.getElementById("helpoffline").checked?$.get("/help/Index.htm").done(function(){window.open("/help/Index.htm","_blank").focus()}).fail(function(){onLocalHelpFailure()}):window.open("https://admhelp.microfocus.com/lr/en/12.60-12.62/help/WebHelp/Content/VTS/c_getting-started.htm","_blank").focus()}
function setClipboard(){var d=!!document.documentMode,a=document.createElement("textarea");a.style.cssText="position: absolute; left: -1000px; top: -1000px";a.textContent="https://admhelp.microfocus.com/vugen/en/latest/help/WebHelp/Content/Download-Help-Center.htm";document.body.appendChild(a);if(!0==d)window.clipboardData.setData("text",a.textContent);else{var d=document.getSelection(),c=document.createRange();c.selectNode(a);d.removeAllRanges();a.select();d.addRange(c);document.execCommand("copy");
d.removeAllRanges()}document.body.removeChild(a)}function onLocalHelpFailure(){confirmDlg(rs.message,rs.notFoundLocalHelp,setClipboard)}
(function(){Date.fromISO=isNaN(new Date("2013-03-13T17:20:29.380Z"))?function(d){var a,c=/^(\d{4}\-\d\d\-\d\d([tT][\d:\.]*)?)([zZ]|([+\-])(\d\d):(\d\d))?$/.exec(d)||[];if(c[1]){d=c[1].split(/\D/);a=0;for(var b=d.length;a<b;a++)d[a]=parseInt(d[a],10)||0;d[1]-=1;d=new Date(Date.UTC.apply(Date,d));if(!d.getDate())return NaN;c[5]&&(a=60*parseInt(c[5],10),c[6]&&(a+=parseInt(c[6],10)),"+"==c[4]&&(a*=-1),a&&d.setUTCMinutes(d.getUTCMinutes()+a));return d}return NaN}:function(d){return new Date(d)}})();
$(window).resize(function(){$("#list").setGridWidth($(window).width()-2,!0)}).bind("mousewheel DOMMouseScroll",function(d){var a=$(window);0<d.originalEvent.wheelDelta||0>d.originalEvent.detail?0==a.scrollTop()&&dgrid.previousPage():(d=a.height()+a.scrollTop()-$(document).height(),2>Math.abs(d)&&dgrid.nextPage())});$(window).keydown(function(d){switch(d.which){case 33:case 34:case 36:case 35:var a,d=d.which;36==d?a=1:35==d?a=MAX_NUM:33==d?a=dgrid.currentPage()-1:34==d&&(a=dgrid.currentPage()+1);dgrid.moveToPage(a)}});
function hideAllPops(){$(".pop-menu, #jqContextMenu").css("display","none")}function showMenu(d,a){hideAllPops();d.css("display","block").css(a)}$(function(){initControls();loadSettings();initializeHelpMenu();initSettings();$(window).unload(function(){saveSettings()});$("html").click(hideAllPops)});function empty(d){return null==d||void 0==d||"string"==typeof d&&0==d.length}function defEmpty(d,a){return empty(d)?a:d}
function getCookie(d){var a,c,b,f=document.cookie.split(";");for(a=0;a<f.length;a++)if(c=f[a].substr(0,f[a].indexOf("=")),b=f[a].substr(f[a].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==d)return unescape(b)}jQuery.ensureScript=function(){var d={};return function(a,c){if(d[a])c&&c();else return d[a]=!0,jQuery.getScript(a).done(c)}}();function setCookie(d,a,c){var b=new Date;b.setDate(b.getDate()+c);a=escape(a)+(null==c?"":"; expires="+b.toUTCString());document.cookie=d+"="+a}
function Polling(){this.hostid=parseInt(1E3*Math.random());this.inPolling=!1}Polling.prototype.isPrimary=function(){var d=getCookie("longpolling"),a=!0;if(!empty(d)&&(d=d.split("*"),new Date(d[0])>(new Date).getTime()-6E4&&(1>=d.length||d[1]!=this.hostid)))a=!1;!0==a&&(d=(new Date).toGMTString()+"*"+this.hostid,setCookie("longpolling",d));return a};var _polling=new Polling;function checktext(d,a){0<$("#"+d).val().length?$("#"+a).removeAttr("disabled"):$("#"+a).attr("disabled","disabled")}
function parse(d){var a={},d=d.split("&"),c;for(c in d){var b=d[c].split("=");2==b.length&&(a[b[0]]=decodeURIComponent(unescape(b[1])))}return a}function serialize(d){var a={},c;for(c in d)a[c]=encodeURIComponent(d[c]);return $.param(a)}function confirmDlg(d,a,c){$("#confirm").html("<p>"+a+"</p>").dialog("option","title",d).dialog("open")[0].dlgfunc=c}
function alert(d,a,c){d=$("#alert").html("<p>"+d+"</p>").dialog("option","title",empty(a)?rs.message:a).dialog("open");if("function"==typeof c)$("#btnAlertClose").on("click",function(){$("#btnAlertClose").off("click",this);c()});return d}$(document).ajaxError(function(d,a,c){if(0!=a.readyState){var b=rs[a.status];empty(b)?window.status="Error:{0} {1} {2}".format(a.status,d.msg,c.url):(alert(b),window.status="error accessing {0}".format(c.url));blocker.unblock()}});
var _defaultOptions={hideError:!1,type:"GET"};function remoteCall(d,a,c,b){b=b?$.extend({},_defaultOptions,b):_defaultOptions;$.ajax({url:"/data/"+d,cache:!1,data:a,type:b.type,complete:function(a){if(200==a.status){var e=null;try{empty(a.responseText)||(e=eval("("+a.responseText+")"))}catch(h){}e?!1==e.success&&!0!=b.hideError&&(empty(e.msg)?alert("{0}: Unspecfied Error".format(d)):alert(e.msg)):alert("{0}: Invalid reponse".format(d));c(e||{})}},timeout:function(){alert("timeout")}})}
function getUrlWithPort(d){var a=document.location.host,c=a.indexOf(":"),c=0>c?a.length:c;return document.location.protocol+"//"+a.substring(0,c)+":"+d}var _settings;
function initSettings(){remoteCall("get_settings",null,function(d){if(d.success){var a=location.host.search(/:/),c=location.host;0<a&&(c=location.host.substring(0,a));$("#txtserver").text(c);_settings=d.settings;$("#txtPort").val(_settings.port);"None"!=_settings.auth?(auth(),$("#lblUser").css("display",""),$.browser.msie||$("#lblLogout").hide()):afterAuth();"NamedInstance"==_settings.mode&&(document.title="VTS - "+_settings.name,$("#instancename").text("("+_settings.name+")"),$("#txtDlgPort").attr("disabled",
"disabled"),$("#miInstDefault").attr("href",getUrlWithPort(_settings.adminPort)),$("#mnuStart,#mnuStop").unbind("click").attr("disabled","disabled").attr("title",rs.canOnlyOnMainInst));gridRefresher&&gridRefresher.enable(_settings.autoRefreshGrid);startButton(_settings.started)}else empty(d.msg)||alert(d.msg,"Error",function(){$(document.body).css("display","none")})},{hideError:!0})}function loadKey(d){return d&&window.localStorage?window.localStorage.getItem(d):null}
function saveKey(d,a){d&&window.localStorage&&window.localStorage.setItem(d,a)}function loadSettings(){$(".preserve").each(function(){var d=loadKey(this.id);empty(d)||$(this).val(d)})}function saveSettings(){var d={};$(".preserve").each(function(){this.id&&(d[this.id]=$(this).val())});for(var a in d)saveKey(a,d[a])}
function initControls(){$("button, ul#icons li").hover(function(){$(this).addClass("ui-state-hover")},function(){$(this).removeClass("ui-state-hover")});$("#dlgColInfo").dialog({autoOpen:!1,width:400,modal:!0,resizable:!1,buttons:[{id:"btnColInfo",text:rs.ok,click:function(){var d=$("#chkIndex"),a=d.prop("checked"),c=$("#dlgColInfo");a==c.data("old")&&c.dialog("close");remoteCall("set_index",{colname:dgrid.colName(),index:a},function(a){!0==a.success&&(d.prop("checked",a.indexed),c.dialog("close"))})}}]});
$("#mnuCheckUnique").click(function(){var d=dgrid.toggleUniqueChk();setUniqueMenuFlag(d)});$("#mnuMoreInfo").click(moreInfo);$("#confirm").dialog({autoOpen:!1,width:400,modal:!0,resizable:!1,buttons:function(){var d={};d[rs.ok]=function(){var a=$(this)[0].dlgfunc;$.isFunction(a)&&a();$(this)[0].dlgfunc=null;$(this).dialog("close")};d[rs.cancel]=function(){$(this).dialog("close")};return d}()});$("#alert").dialog({autoOpen:!1,width:400,modal:!0,resizable:!0,buttons:[{id:"btnAlertClose",text:rs.close,
click:function(){$(this).dialog("close")}}]});$("#chkNewColumn").click(function(){var d=$(this).is(":checked"),a=$("#txtNewColumn"),c=$("#drpColumn");d?(a.show(),c.hide()):(c.show(),a.hide())})}function moreInfo(){var d=dgrid.getColumnName();$("#lblColName").html(d);remoteCall("col_info",{colname:d},function(a){a.success&&($("#chkIndex").prop("checked",a.indexed),$("#dlgColInfo").dialog("open").data("old",a.indexed))})}function findDup(d,a,c,b){find_dup(dgrid.getColumnName(c),d,b)}
function find_dup(d,a,c){remoteCall("check_item",{colname:d,value:a,action:"has_dup"},function(a){a.success&&c(a.duplicated)})}
$(function(){$("#txtDlgPort").bind("keyup",function(){$("#btnStart").button(function(d){var a=/^\d{1,5}$/;return!(empty(d)||0!=d.search(a))}($(this).val())?"enable":"disable")});$("#dlgStartServer").dialog({autoOpen:!1,width:"auto",modal:!0,resizable:!1,buttons:[{id:"btnStart",text:rs.enable,click:function(){$("#txtDlgServer").val();var d=$("#txtDlgPort").val();start_server(!0,d,function(a){a.started?(startButton(a.started),$("#txtPort").val(parseInt(d,10)),$("#dlgStartServer").dialog("close")):$(".autherror").html(rs.portInUse).show()},
!0)}},{text:rs.close,click:function(){$(this).dialog("close")}}]});0<$("#mnuLanguage li").length?$("#mnuLanguage li").click(function(){var d=$("span.value",this).text();setCookie("ln",d,365);document.location=document.location.href;document.location.reload(!0)}):$("#lblLanguage").hide();$("#mnuEnableAPI").menu({menuStyle:{width:"200px"}}).click(function(){$(this).css("display","none")});$("#options").click(function(d){$.ensureScript("options.js");d.stopPropagation()});$("#helpcenter").click(function(d){$("#mnuHelp").menu();
var a=$(this).position();a.top+=$(this).height();a.left=Math.min(a.left,$(window).width()-$("#mnuHelp").width()-10);showMenu($("#mnuHelp"),a);d.stopPropagation()});$("#miHelpOptions").mouseenter(function(){setTimeout(function(){$("#mnuOptions").not(":visible")&&$("#mnuOptions").show()},350)});$("#miOpenHelp").click(openHelpCenter);$("#miOpenHelp1").click(openHelpCenter);$("#miOpenHelp2").click(openHelpCenter);$('input[type="checkbox"]').on("change",function(){$('input[type="checkbox"]').not(this).prop("checked",
!1);"helponline"==$(this).attr("id")?updateHelpSetting("false"):updateHelpSetting("true")});$("#mnuStart,#mnuStop").click(function(d){var a=$(this).position();a.top+=$("span.enable-script").height();a.left-=Math.max(a.left+$("#mnuEnableAPI").width()+20-$(window).width(),0);showMenu($("#mnuEnableAPI"),a);d.stopPropagation()});$("#btnStartDlg").click(function(){$("#txtDlgServer").text($("#txtserver").text());$("#txtDlgPort").val($("#txtPort").val()).focus().trigger("keyup");$(".autherror").hide();$("#dlgStartServer").dialog("open");
$("#btnStartDlg")});$("#btnStop").click(function(){start_server(!1,null,function(d){startButton(d.started)})})});function startButton(d){!0==d?($("#mnuStart").hide(),$("#mnuStop").show()):($("#mnuStop").hide(),$("#mnuStart").show())}function start_server(d,a,c,b){remoteCall("start_server",{start:d,port:a},function(a){a.success?($(".autherror").hide(),$.isFunction(c)&&c(a)):$(".autherror").html(a.msg).show()},{hideError:b})}
function Blocker(){this.opts={css:{border:"none",padding:"15px","border-radius":"10px","font-size":"1.2em"}}}Blocker.prototype.block=function(d){this.opts.message=d||rs.pleaseWait;$.blockUI(this.opts)};Blocker.prototype.unblock=function(d){"function"==typeof d?$.unblockUI({onUnblock:d}):$.unblockUI(this.opts)};Blocker.prototype.message=function(d){0<d.length&&$.message(d,this.opts)};var blocker=new Blocker,Status={inProgress:1,failed:2,succeeded:3};
function checkStatus(d,a){remoteCall("job_status",{jobid:d},function(c){c.success&&(c=c.job,1===c.status?(blocker.message(c.msg),setTimeout(function(){checkStatus(d,a)},1E3)):(blocker.unblock(),a(c)))})}
$(function(){$("#dlgExport").dialog({modal:!0,width:"auto",autoOpen:!1,resizable:!1,buttons:[{id:"btnExport",text:rs.startExport,click:function(){var d=$("#rdoExpCsv").is(":checked");$(".autherror").hide();if(d)window.open("/data/export_csv","_blank"),$(this).dialog("close"),alert(rs.exportStarted.format('<a href="/data/export_csv">',"</a>"));else{var a=$("#txtExpTable"),d=$("#txtExportConn").val(),c=$.trim(a.val());a.val(c);a=$("#chkDropTable").is(":checked");if(!d||!c)$(".autherror").html(rs.connectionMissing).show();
else{var b=$(this).dialog("close");blocker.block();export_database(d,c,a,function(a){a.success?setTimeout(function(){checkStatus(a.jobid,function(a){a.status===Status.failed?alert(a.msg):a.status===Status.succeeded&&alert(rs.exportSuccessful.format(a.msg))})},1E3):(blocker.unblock(),b.dialog("open"),alert(a.msg))})}}}},{text:rs.close,click:function(){$(this).dialog("close");$(".autherror").hide()}}]});$("#dlgImport").dialog({modal:!0,width:"auto",autoOpen:!1,resizable:!1,buttons:[{id:"btnImport",
text:rs.startImportBtn,disabled:"disabled",click:function(){function d(a){!0==a.success?setTimeout(function(){checkStatus(a.jobid,function(a){a.status===Status.failed?alert(a.msg):alert(rs.importSuccessful);dgrid.loadData(!0)})},1E3):blocker.unblock(function(){$(this).dialog("open");var c=rs.importFailed;empty(a.msg)||(c+=" "+rs.error+':<br />"'+a.msg+'"');alert(c)})}if($("#rdoImpCsv").is(":checked")){if(empty($("#fileToUpload").val()))return alert(rs.chooseFile);$(this).dialog("close");blocker.block();
var a=$("#drpSeparator").val();ajaxFileUpload({separator:[a]},d)}else{var a=$("#txtImportConn").val(),c=$("#txtSql").val();!a||!c?alert(rs.sqlMissing):(blocker.block(),$(this).dialog("close"),import_database(a,c,d))}}},{text:rs.close,click:function(){$(this).dialog("close")}}]});$("#tbtnImport").button({text:!0,icons:{primary:"ui-icon-import"}}).click(function(){$("#dlgImport").dialog("open")});$("#tbtnExport").button({text:!0,icons:{primary:"ui-icon-export"}}).click(function(){$("#dlgExport").dialog("open")});
$("#fileToUpload,#drpSeparator").click(function(){$("#rdoImpCsv").click()});$("#txtSql,#txtImportConn,#btnImpTestConn").click(function(){$("#rdoImpDb").click()});$("#rdoImpDb").click(function(){$("#optImpDb").removeClass("ui-state-disabled");$("#btnImpTestConn").removeAttr("disabled");$("#optImpCsv,#optImpCsv2").addClass("ui-state-disabled")});$("#rdoImpCsv").click(function(){$("#optImpDb").addClass("ui-state-disabled");$("#btnImpTestConn").attr("disabled","disabled");$("#optImpCsv,#optImpCsv2").removeClass("ui-state-disabled")});
$("#chkDropTable,#txtExportConn,#txtExpTable").click(function(){$("#rdoExpDb").click()});$("#rdoExpDb").click(function(){$("#optExpDb").removeClass("ui-state-disabled");$("#btnExpTestConn").removeAttr("disabled")});$("#rdoExpCsv").click(function(){$("#optExpDb").addClass("ui-state-disabled");$("#btnExpTestConn").attr("disabled","disabled")});$("input[name=importtype]").click(function(){$("#btnImport").button("enable")});$("input[name=exporttype]").click(function(){$("#btnExport").button("enable")});
$("#btnImpTestConn").button().click(function(){var d=$("#txtImportConn").val();test_connection(d)});$("#btnExpTestConn").button().click(function(){var d=$("#txtExportConn").val();test_connection(d)});$("#toolbar").addClass("flat").mouseover(function(){$(this).removeClass("flat")}).mouseout(function(){$(this).addClass("flat")})});
function test_connection(d){var a=$("#dlgExport,#dlgImport");a.addClass("wait");var c=alert(rs.pleaseWait);remoteCall("test_connection",{conn:d},function(b){a.removeClass("wait");c.dialog("close");b.success?alert(rs.testConnSuccess):alert(rs.testConnFailed+(empty(b.msg)?".":':<br />"{0}"'.format(b.msg)))},{hideError:!0})}function import_database(d,a,c){remoteCall("import_database",{conn:d,sql:a},function(a){c(a)},{hideError:!0,type:"POST"})}
function export_database(d,a,c,b){remoteCall("export_database",{conn:d,tbl:a,droptbl:c},b,{hideError:!0})}
$(function(){function d(a,b){var d=$.trim($("#txtColName",a).val());if(!empty(d)){var e="add"==b?a.prop("left"):null;"__id"==e&&(e="");var h=dgrid.colName();update_column(d,h,b,e,function(b){b.success?($(".autherror").hide(),dgrid.loadData(d!=h),a.dialog("close")):$(".autherror").html(b.msg).show()})}}$("#mnuDeleteAll").click(function(){deleteColumn(dgrid.colName())});$("#mnuColumn").menu({menuStyle:{width:"600px"}}).click(function(){$("#mnuColumn").css("display","none")});$("#tmnuClearColumn").click(function(){clearColumn()});
$("#tbtnDeleteTable").button({text:!0,icons:{primary:"ui-icon-close"}}).click(function(){clearTable()});$("#tbtnActions").button().click(function(a){var b=$(this).position();b.top+=$("#tbtnActions").height();setUniqueMenuFlag();showMenu($("#mnuColumn"),b);a.stopPropagation()}).button("disable");$("#dlgCreateCol").dialog({autoOpen:!1,width:600,modal:!0,buttons:[{text:rs.ok,click:function(){$(this).dialog("close")}},{text:rs.cancel,click:function(){$(this).dialog("close")}}]});var a=function(a){a.keyCode==
$.ui.keyCode.ENTER&&$(a.delegateTarget).parent().find(".ui-dialog-buttonpane button:first").click()};$("#dlgColEdit").dialog({autoOpen:!1,width:320,resizable:!1,modal:!0,buttons:[{id:"btnColEdit",text:rs.save,click:function(){d($("#dlgColEdit"),"edit")}},{text:rs.cancel,click:function(){$(".autherror").hide();$(this).dialog("close")}}]}).keypress(a);$("#dlgColAdd").dialog({autoOpen:!1,width:320,resizable:!1,modal:!0,buttons:[{id:"btnColAdd",text:rs.save,click:function(){d($("#dlgColAdd"),"add")}},
{text:rs.cancel,click:function(){$(".autherror").hide();$(this).dialog("close")}}]}).keypress(a);$("#mnuAddColumnLeft").click(addColumnLeft);$("#mnuAddColumnRight").click(addColumnRight);$("#mnuChangeColumn").click(changeColumn)});function addColumnLeft(){if(!(0<$("#mnuAddColumnLeft.ui-state-disabled").length)){var d=null,a=0,c=dgrid.colInfo();$(c.names).each(function(b){if(this==dgrid.colName())return a=b,!1});0!=a&&(d=c.names[a-1]);updateColumnDlg("Add",d)}}
function addColumnRight(){0<$("#mnuAddColumnRight.ui-state-disabled").length||updateColumnDlg("Add",dgrid.colName())}function changeColumn(){0<$("#mnuChangeColumn.ui-state-disabled").length||updateColumnDlg("Edit")}function setUniqueMenuFlag(d){void 0==d&&(d=dgrid.checkingUnique());var a=$("#imgCheckUnique,#imgCheckUnique1");d?a.addClass("ui-icon").addClass("ui-icon-check"):a.removeClass("ui-icon").removeClass("ui-icon-check")}
function updateColumnDlg(d,a){$(".autherror").hide();var c=$("#dlgCol"+d).dialog("open");c.prop("left",a);var b="Edit"==d?dgrid.colName():"";$("#txtColName",c).val(b).click().select()}function isHeaderSelected(){return 0<$("#container .ui-state-highlight").length}function clearTable(){confirmDlg(rs.deleteTable,rs.confirmDeleteAll,function(){delete_all()})}
function delete_all(){0<$("#mnuClearColumn.ui-state-disabled").length||remoteCall("delete_all",null,function(d){d.success&&(alert(rs.tableDeleted),dgrid.loadData(!0))})}function clearColumn(){if(!(0<$("#mnuClearColumn.ui-state-disabled").length)){var d=dgrid.colName();empty(d)?alert(rs.chooseColumn):confirmDlg(rs.clearContent,rs.confirmClear.format(d),function(){clear_column(d)})}}function clear_column(d){remoteCall("clear_column",{colname:d},function(a){a.success&&dgrid.loadData(!0)})}
function deleteColumn(){if(!(0<$("#mnuDeleteColumn.ui-state-disabled").length)){var d=dgrid.colName();empty(d)?alert(rs.chooseColumn):confirmDlg(rs.deleteColumn,rs.confirmDelete.format(d),function(){delete_column(d);dgrid.colName(null)})}}function delete_column(d){remoteCall("delete_column",{colname:d},function(a){a.success&&dgrid.loadData(!0)})}function update_column(d,a,c,b,f){remoteCall("update_column",{colname:d,curname:a,type:c,left:b},f,{hideError:!0})}
function get_count(d,a){var c=empty(d)?{}:{colname:d};remoteCall("get_count",c,function(b){b.success&&a(b)})}$(function(){$("#mnuAddEnd").click(dgrid.addEnd);$("#mnuInsertValue").click(dgrid.addStart)});function delete_data(d,a){remoteCall("delete_data",{colname:a,rowid:d},function(c){c.success?(dgrid.loadData(!1),dgrid.updateCurrentColName(a)):alert(c.msg)})}function afterAuth(){dgrid.initGrid()}
function auth(){remoteCall("auth",null,function(d){if(d.success){var a=d.display||d.user;$("#username").html(a);fullControl=d.isAdmin;fullControl||($("#tbtnImport").button("disable"),$("#tbtnDeleteTable").button("disable"),$("#mnuStart,#mnuStop").unbind("click").attr("disabled","disabled"),alert('<span class="ui-icon ui-icon-warning"></span>'+rs.userPermissionNeeded))}});afterAuth()}
$(function(){$("#logout").click(function(){document.execCommand("ClearAuthenticationCache","false");document.location=document.location.href})});function colAction(d){fullControl?$("#tbtnActions").button(d?"enable":"disable"):$("#tbtnActions").button("disable")}var _lastFoundPage=null,_startPage,_cpSearched=!1;function initSearch(){_lastFoundPage=null;_cpSearched=!1;dgrid.grid()&&(_startPage=dgrid.currentPage())}
function searchblur(){var d=$("#txtSearch");empty(d.val())&&d.removeClass("search-focus")}
$(function(){var d=$("#txtSearch");empty(d.val())||d.addClass("search-focus");$("#txtSearch").focus(function(){$(this).addClass("search-focus")});$("#txtSearch").blur(searchblur).keypress(function(a){a.keyCode==$.ui.keyCode.ENTER?($("#tbtnSearch").click(),window.setTimeout(function(){$("#txtSearch").focus()},1)):initSearch()}).bind("input",function(){empty($(this).val())&&dgrid.removeHighlight("highlight")});$("#tbtnSearch").button({text:!1,icons:{primary:"ui-icon-search"}}).click(function(){var a=
$("#txtSearch").val();empty(a)||(currentPageSearched()?searchDb(a):searchInPage(a))});initSearch()});RegExp.escape=function(d){return d.replace(RegExp("[.*+?|()\\[\\]{}\\\\]","g"),"\\$&")};function containValue(d,a){if(0<=a.search(d))return!0}function getNextStart(){var d=dgrid.grid().getDataIDs();return 0<d.length?parseInt(d.pop())+1:0}function currentPageSearched(d){if(void 0!=d)_cpSearched=!0==d;else return _cpSearched}
function searchInPage(d){var a=dgrid.getCols();dgrid.removeHighlight("highlight");$("th.ui-state-highlight").removeClass("ui-state-highlight");if(!empty(d)){var c=RegExp(RegExp.escape(d),"i"),b=0<a.length?a[0].col.length:0,f=0,e;for(e in a){containValue(c,a[e].name)&&(_lastFoundPage=dgrid.currentPage(),dgrid.grid().setLabel(a[e].name,"","ui-state-highlight"),f++);for(var h=0;h<b;h++){var g=a[e].col[h];if(containValue(c,g.value)){_lastFoundPage=dgrid.currentPage();var i=parseInt(e,10)+1;dgrid.grid().setCell(g.id,
i,"","highlight","");f++}}}currentPageSearched(!0);0==f&&searchDb(d)}}
function searchDb(d,a){function c(a){e=!1;if(a.success){if(a.timeout){f.start=a.start;var b=dgrid.getPageSize();blocker.block(rs.searchingPage.format(a.start/b));return remoteCall("search",f,c)}blocker.unblock();a.found?(_lastFoundPage=dgrid.currentPage(),(a=a.match)&&0<a.length&&dgrid.navigateToRow(a[0].index,function(){var a=$("#txtSearch").val();searchInPage(a);$("#txtSearch").focus()})):!1==a.found&&(1<_startPage||1<=_lastFoundPage?(_startPage=1,confirmDlg(rs.search,rs.searchEnd,function(){initSearch();
_startPage=1;searchDb(d,0)})):alert(rs.notFound))}else blocker.unblock()}var b=empty(a)?getNextStart():a,f={q:d,start:b},e=!0;window.setTimeout(function(){e&&blocker.block()},500);remoteCall("search",f,c)}var offscrn="-3000px",gid=0;
$.extend({createIframe:function(d,a){var c="jUploadFrame"+d,b='<iframe id="{0}" name="{0}" style="position:absolute; top:{1}; left:{1}" src="{2}"/>'.format(c,offscrn,"string"==typeof a?a:"javascript:void(0)");$(b).appendTo(document.body);return $("#"+c).get(0)},createUploadForm:function(d,a,c){var b=$('<form action="/" method="POST" name="{0}" id="{0}" enctype="multipart/form-data"></form>'.format("jUploadForm"+d));if(c)for(var f in c)$('<input type="hidden" name="{0}" value="{1}" />'.format(f,c[f])).appendTo(b);
a=$("#"+a);d="jUploadFile"+d;c=$(a).clone();$(a).attr("id",d).before(c).appendTo(b);$(b).css("position","absolute").css("top",offscrn).css("left",offscrn).appendTo("body");return b},ajaxFileUpload:function(d){var a=$.extend({},$.ajaxSettings,d),d=gid++,c=$.createUploadForm(d,a.fileElementId,"undefined"==typeof a.data?!1:a.data),b=$.createIframe(d,a.secureuri),d="jUploadFrame"+d;a.global&&!$.active++&&$.event.trigger("ajaxStart");var f=!1,e={};a.global&&$.event.trigger("ajaxSend",[e,a]);var h=function(d){try{var g=
(b.contentWindow||b.contentDocument).document;e.responseText=g.body?g.body.innerHTML:null;e.responseXML=g.XMLDocument?g.XMLDocument:g}catch(h){e.responseText=e.responseXML="{}"}if(e||"timeout"==d)f=!0,d="timeout"!=d?"success":"error","error"!=d?(g=$.uploadHttpData(e,a.dataType),a.success&&a.success(g,d),a.global&&$.event.trigger("ajaxSuccess",[e,a])):alert(a),a.global&&$.event.trigger("ajaxComplete",[e,a]),a.global&&!--$.active&&$.event.trigger("ajaxStop"),a.complete&&a.complete(e,d),$(b).unbind(),
setTimeout(function(){try{$(b).remove(),$(c).remove()}catch(d){$.handleError(a,e,null,d)}},100),e=null};0<a.timeout&&setTimeout(function(){f||h("timeout")},a.timeout);try{c.attr("action",a.url).attr("target",d).submit()}catch(g){$.handleError(a,e,null,g)}$("#"+d).load(h);return{abort:function(){}}},uploadHttpData:function(d,a){var c;c="xml"==a||!a?d.responseXML:d.responseText;if("json"==a){-1!=c.indexOf("<pre")&&(c=$("<div />").html(c),c=$("pre:first",c).html());try{return eval("("+c+")")}catch(b){return{}}}return c}});
function ajaxFileUpload(d,a){$.ajaxFileUpload({url:"/data/import_csv",secureuri:!1,fileElementId:"fileToUpload",dataType:"json",data:d,success:a,global:!0,error:function(a,b,d){alert("Error:"+d)}})};
