(function(d){function b(){c.hide();a.hide()}var c,a,g,e,h,f={menuStyle:{listStyle:"none",padding:"1px",margin:"0px",backgroundColor:"#fff",border:"1px solid #999",minWidth:"100px","font-size":"110%"},itemStyle:{margin:"0px",color:"#000",display:"block",cursor:"default",padding:"3px","padding-right":"8px",border:"1px solid #fff","white-space":"nowrap",backgroundColor:"transparent"},itemHoverStyle:{"background-color":"#3B83E7",color:"White",border:"1px solid #3B83E7","border-radius":"4px"},eventPosX:"pageX",
eventPosY:"pageY",shadow:!0,onContextMenu:null,onShowMenu:null};d.fn.contextMenu=function(i,j){c||(c=d('<div id="jqContextMenu"></div>').hide().css({position:"absolute",zIndex:"500"}).appendTo("body").bind("click",function(d){d.stopPropagation()}));a||(a=d("<div></div>").css({backgroundColor:"#000",position:"absolute",opacity:0.2,zIndex:499}).appendTo("body").hide());e=e||[];e.push({id:i,menuStyle:d.extend({},f.menuStyle,j.menuStyle||{}),itemStyle:d.extend({},f.itemStyle,j.itemStyle||{}),itemHoverStyle:d.extend({},
f.itemHoverStyle,j.itemHoverStyle||{}),bindings:j.bindings||{},shadow:j.shadow||!1===j.shadow?j.shadow:f.shadow,onContextMenu:j.onContextMenu||f.onContextMenu,onShowMenu:j.onShowMenu||f.onShowMenu,eventPosX:j.eventPosX||f.eventPosX,eventPosY:j.eventPosY||f.eventPosY});var n=e.length-1;d(this).bind("contextmenu",function(m){var f=e[n].onContextMenu?e[n].onContextMenu(m):!0;h=m.target;if(f){var z=this,v=e[n];g=d("#"+v.id).find("ul:first").clone(!0);g.css(v.menuStyle).find("li").css(v.itemStyle).hover(function(){d(this).css(v.itemHoverStyle);
d(this).addClass("menuHover")},function(){d(this).css(v.itemStyle);d(this).removeClass("menuHover")}).find("img").css({verticalAlign:"middle",paddingRight:"2px"});c.html(g);v.onShowMenu&&(c=v.onShowMenu(m,c));d.each(v.bindings,function(a,v){d("#"+a,c).bind("click",function(){b();v(z,h)})});f=m[v.eventPosX];f+c.width()>d(window).width()&&(f=d(window).width()-c.width()-10);c.css({left:f,top:m[v.eventPosY]}).show();v.shadow&&a.css({width:c.width(),height:c.height(),left:f+2,top:m.pageY+2}).show();d(document).one("click",
b);return!1}});return this};d.contextMenu={defaults:function(b){d.each(b,function(b,a){"object"==typeof a&&f[b]?d.extend(f[b],a):f[b]=a})}}})(jQuery);$(function(){$("div.contextMenu").hide()});/*

 jQuery blockUI plugin
 Version 2.42 (11-MAY-2012)
 @requires jQuery v1.2.3 or later

 Examples at: http://malsup.com/jquery/block/
 Copyright (c) 2007-2010 M. Alsup
 Dual licensed under the MIT and GPL licenses:
 http://www.opensource.org/licenses/mit-license.php
 http://www.gnu.org/licenses/gpl.html

 Thanks to Amir-Hossein Sobhi for some excellent contributions!
*/
(function(){var d=jQuery,b=function(b,a){var e,i,q=b==window,p=a&&void 0!==a.message?a.message:void 0,a=d.extend({},d.blockUI.defaults,a||{});if(!a.ignoreIfBlocked||!d(b).data("blockUI.isBlocked")){a.overlayCSS=d.extend({},d.blockUI.defaults.overlayCSS,a.overlayCSS||{});e=d.extend({},d.blockUI.defaults.css,a.css||{});i=d.extend({},d.blockUI.defaults.themedCSS,a.themedCSS||{});p=void 0===p?a.message:p;q&&m&&c(window,{fadeOut:0});if(p&&"string"!=typeof p&&(p.parentNode||p.jquery)){var s=p.jquery?p[0]:
p,l={};d(b).data("blockUI.history",l);l.el=s;l.parent=s.parentNode;l.display=s.style.display;l.position=s.style.position;l.parent&&l.parent.removeChild(s)}d(b).data("blockUI.onUnblock",a.onUnblock);var l=a.baseZ,w=a.forceIframe?d('<iframe class="blockUI" style="z-index:'+l++ +';display:none;border:none;margin:0;padding:0;position:absolute;width:100%;height:100%;top:0;left:0" src="'+a.iframeSrc+'"></iframe>'):d('<div class="blockUI" style="display:none"></div>'),s=a.theme?d('<div class="blockUI blockOverlay ui-widget-overlay" style="z-index:'+
l++ +';display:none"></div>'):d('<div class="blockUI blockOverlay" style="z-index:'+l++ +';display:none;border:none;margin:0;padding:0;width:100%;height:100%;top:0;left:0"></div>'),l=d(a.theme&&q?'<div class="blockUI '+a.blockMsgClass+' blockPage ui-dialog ui-widget ui-corner-all" style="z-index:'+(l+10)+';display:none;position:fixed"><div class="ui-widget-header ui-dialog-titlebar ui-corner-all blockTitle">'+(a.title||"&nbsp;")+'</div><div class="ui-widget-content ui-dialog-content"></div></div>':
a.theme?'<div class="blockUI '+a.blockMsgClass+' blockElement ui-dialog ui-widget ui-corner-all" style="z-index:'+(l+10)+';display:none;position:absolute"><div class="ui-widget-header ui-dialog-titlebar ui-corner-all blockTitle">'+(a.title||"&nbsp;")+'</div><div class="ui-widget-content ui-dialog-content"></div></div>':q?'<div class="blockUI '+a.blockMsgClass+' blockPage" style="z-index:'+(l+10)+';display:none;position:fixed"></div>':'<div class="blockUI '+a.blockMsgClass+' blockElement" style="z-index:'+
(l+10)+';display:none;position:absolute"></div>');p&&(a.theme?(l.css(i),l.addClass("ui-widget-content")):l.css(e));!a.theme&&(!a.applyPlatformOpacityRules||!d.browser.mozilla||!/Linux/.test(navigator.platform))&&s.css(a.overlayCSS);s.css("position",q?"fixed":"absolute");(d.browser.msie||a.forceIframe)&&w.css("opacity",0);e=[w,s,l];var A=q?d("body"):d(b);d.each(e,function(){this.appendTo(A)});a.theme&&(a.draggable&&d.fn.draggable)&&l.draggable({handle:".ui-dialog-titlebar",cancel:"li"});e=j&&(!d.boxModel||
0<d("object,embed",q?null:b).length);if(n||e){q&&(a.allowBodyStretch&&d.boxModel)&&d("html,body").css("height","100%");if((n||!d.boxModel)&&!q){e=parseInt(d.css(b,"borderTopWidth"))||0;i=parseInt(d.css(b,"borderLeftWidth"))||0;var D=e?"(0 - "+e+")":0,F=i?"(0 - "+i+")":0}d.each([w,s,l],function(d,b){var c=b[0].style;c.position="absolute";if(2>d)q?c.setExpression("height","Math.max(document.body.scrollHeight, document.body.offsetHeight) - (jQuery.boxModel?0:"+a.quirksmodeOffsetHack+') + "px"'):c.setExpression("height",
'this.parentNode.offsetHeight + "px"'),q?c.setExpression("width",'jQuery.boxModel && document.documentElement.clientWidth || document.body.clientWidth + "px"'):c.setExpression("width",'this.parentNode.offsetWidth + "px"'),F&&c.setExpression("left",F),D&&c.setExpression("top",D);else if(a.centerY)q&&c.setExpression("top",'(document.documentElement.clientHeight || document.body.clientHeight) / 2 - (this.offsetHeight / 2) + (blah = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "px"'),
c.marginTop=0;else if(!a.centerY&&q){var e="((document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "+(a.css&&a.css.top?parseInt(a.css.top):0)+') + "px"';c.setExpression("top",e)}})}p&&(a.theme?l.find(".ui-widget-content").append(p):l.append(p),(p.jquery||p.nodeType)&&d(p).show());(d.browser.msie||a.forceIframe)&&a.showOverlay&&w.show();if(a.fadeIn)e=a.onBlock?a.onBlock:f,w=a.showOverlay&&!p?e:f,e=p?e:f,a.showOverlay&&s._fadeIn(a.fadeIn,w),p&&l._fadeIn(a.fadeIn,
e);else if(a.showOverlay&&s.show(),p&&l.show(),a.onBlock)a.onBlock();g(1,b,a);q?(m=l[0],r=d(":input:enabled:visible",m),a.focusInput&&setTimeout(h,20)):(e=l[0],p=a.centerX,s=a.centerY,i=e.parentNode,l=e.style,w=(i.offsetWidth-e.offsetWidth)/2-(parseInt(d.css(i,"borderLeftWidth"))||0),e=(i.offsetHeight-e.offsetHeight)/2-(parseInt(d.css(i,"borderTopWidth"))||0),p&&(l.left=0<w?w+"px":"0"),s&&(l.top=0<e?e+"px":"0"));a.timeout&&(p=setTimeout(function(){q?d.unblockUI(a):d(b).unblock(a)},a.timeout),d(b).data("blockUI.timeout",
p))}},c=function(b,c){var e=b==window,f=d(b),i=f.data("blockUI.history"),h=f.data("blockUI.timeout");h&&(clearTimeout(h),f.removeData("blockUI.timeout"));c=d.extend({},d.blockUI.defaults,c||{});g(0,b,c);null===c.onUnblock&&(c.onUnblock=f.data("blockUI.onUnblock"),f.removeData("blockUI.onUnblock"));var j;j=e?d("body").children().filter(".blockUI").add("body > .blockUI"):d(".blockUI",b);e&&(m=r=null);c.fadeOut?(j.fadeOut(c.fadeOut),setTimeout(function(){a(j,i,c,b)},c.fadeOut)):a(j,i,c,b)},a=function(b,
a,c,e){b.each(function(){this.parentNode&&this.parentNode.removeChild(this)});a&&a.el&&(a.el.style.display=a.display,a.el.style.position=a.position,a.parent&&a.parent.appendChild(a.el),d(e).removeData("blockUI.history"));if("function"==typeof c.onUnblock)c.onUnblock(e,c)},g=function(a,b,c){var f=b==window,b=d(b);if(a||!(f&&!m||!f&&!b.data("blockUI.isBlocked")))b.data("blockUI.isBlocked",a),c.bindEvents&&(!a||c.showOverlay)&&(a?d(document).bind("mousedown mouseup keydown keypress",c,e):d(document).unbind("mousedown mouseup keydown keypress",
e))},e=function(a){if(a.keyCode&&9==a.keyCode&&m&&a.data.constrainTabKey){var b=r,c=a.shiftKey&&a.target===b[0];if(!a.shiftKey&&a.target===b[b.length-1]||c)return setTimeout(function(){h(c)},10),!1}b=a.data;return 0<d(a.target).parents("div."+b.blockMsgClass).length?!0:0==d(a.target).parents().children().filter("div.blockUI").length},h=function(d){r&&(d=r[!0===d?r.length-1:0])&&d.focus()};d.fn._fadeIn=d.fn.fadeIn;var f=function(){},i=document.documentMode||0,j=d.browser.msie&&(8>d.browser.version&&
!i||8>i),n=d.browser.msie&&/MSIE 6.0/.test(navigator.userAgent)&&!i;d.blockUI=function(d){b(window,d)};d.unblockUI=function(d){c(window,d)};d.growlUI=function(a,b,c,e){var f=d('<div class="growlUI"></div>');a&&f.append("<h1>"+a+"</h1>");b&&f.append("<h2>"+b+"</h2>");void 0==c&&(c=3E3);d.blockUI({message:f,fadeIn:700,fadeOut:1E3,centerY:!1,timeout:c,showOverlay:!1,onUnblock:e,css:d.blockUI.defaults.growlCSS})};d.fn.block=function(a){var c=d.extend({},d.blockUI.defaults,a||{});this.each(function(){var a=
d(this);(!c.ignoreIfBlocked||!a.data("blockUI.isBlocked"))&&a.unblock({fadeOut:0})});return this.each(function(){"static"==d.css(this,"position")&&(this.style.position="relative");d.browser.msie&&(this.style.zoom=1);b(this,a)})};d.fn.unblock=function(d){return this.each(function(){c(this,d)})};d.message=function(a,b){var c=d(".blockUI");try{b.theme?c.find(".ui-widget-content").text(a):c.text(a)}catch(e){}};d.blockUI.version=2.42;d.blockUI.defaults={message:"<h1>Please wait...</h1>",title:null,draggable:!0,
theme:!1,css:{padding:0,margin:0,width:"30%",top:"40%",left:"35%",textAlign:"center",color:"#000",border:"3px solid #aaa",backgroundColor:"#fff",cursor:"wait"},themedCSS:{width:"30%",top:"40%",left:"35%"},overlayCSS:{backgroundColor:"#000",opacity:0.3,cursor:"wait"},growlCSS:{width:"350px",top:"10px",left:"",right:"10px",border:"none",padding:"5px",opacity:0.3,cursor:"default",color:"#fff",backgroundColor:"#000","-webkit-border-radius":"10px","-moz-border-radius":"10px","border-radius":"10px"},iframeSrc:/^https/i.test(window.location.href||
"")?"javascript:false":"about:blank",forceIframe:!1,baseZ:1E3,centerX:!0,centerY:!0,allowBodyStretch:!0,bindEvents:!0,constrainTabKey:!0,fadeIn:200,fadeOut:400,timeout:0,showOverlay:!0,focusInput:!0,applyPlatformOpacityRules:!0,onBlock:null,onUnblock:null,quirksmodeOffsetHack:4,blockMsgClass:"blockMsg",ignoreIfBlocked:!1};var m=null,r=[]})();!function(d){"object"==typeof exports?module.exports=d():"function"==typeof define&&define.amd?define(d):"undefined"!=typeof window?window.eio=d():"undefined"!=typeof global?global.eio=d():"undefined"!=typeof self&&(self.eio=d())}(function(){return function b(c,a,g){function e(f,j){if(!a[f]){if(!c[f]){var n="function"==typeof require&&require;if(!j&&n)return n(f,!0);if(h)return h(f,!0);throw Error("Cannot find module '"+f+"'");}n=a[f]={exports:{}};c[f][0].call(n.exports,function(a){var b=c[f][1][a];
return e(b?b:a)},n,n.exports,b,c,a,g)}return a[f].exports}for(var h="function"==typeof require&&require,f=0;f<g.length;f++)e(g[f]);return e}({1:[function(b,c){c.exports=b("./lib/")},{"./lib/":3}],2:[function(b,c){var a=b("emitter");c.exports=a;a.prototype.addEventListener=a.prototype.on;a.prototype.removeEventListener=a.prototype.off;a.prototype.removeListener=a.prototype.off},{emitter:15}],3:[function(b,c){c.exports=b("./socket");c.exports.parser=b("engine.io-parser")},{"./socket":4,"engine.io-parser":16}],
4:[function(b,c){function a(b,c){if(!(this instanceof a))return new a(b,c);c=c||{};b&&"object"==typeof b&&(c=b,b=null);b&&(b=g.parseUri(b),c.host=b.host,c.secure="https"==b.protocol||"wss"==b.protocol,c.port=b.port,b.query&&(c.query=b.query));this.secure=null!=c.secure?c.secure:n.location&&"https:"==location.protocol;if(c.host){var e=c.host.split(":");c.hostname=e.shift();e.length&&(c.port=e.pop())}this.agent=c.agent||!1;this.hostname=c.hostname||(n.location?location.hostname:"localhost");this.port=
c.port||(n.location&&location.port?location.port:this.secure?443:80);this.query=c.query||{};"string"==typeof this.query&&(this.query=g.qsParse(this.query));this.upgrade=!1!==c.upgrade;this.path=(c.path||"/engine.io").replace(/\/$/,"")+"/";this.forceJSONP=!!c.forceJSONP;this.timestampParam=c.timestampParam||"t";this.timestampRequests=c.timestampRequests;this.flashPath=c.flashPath||"";this.transports=c.transports||["polling","websocket","flashsocket"];this.readyState="";this.writeBuffer=[];this.callbackBuffer=
[];this.policyPort=c.policyPort||843;this.open()}var g=b("./util"),e=b("./transports"),h=b("./emitter"),f=b("debug")("engine.io-client:socket"),i=b("indexof"),j=b("engine.io-parser");c.exports=a;var n=b("global");h(a.prototype);a.protocol=j.protocol;a.Socket=a;a.Transport=b("./transport");a.Emitter=b("./emitter");a.transports=b("./transports");a.util=b("./util");a.parser=b("engine.io-parser");a.prototype.createTransport=function(a){f('creating transport "%s"',a);var b=this.query,c={},g;for(g in b)b.hasOwnProperty(g)&&
(c[g]=b[g]);c.EIO=j.protocol;c.transport=a;this.id&&(c.sid=this.id);return new e[a]({agent:this.agent,hostname:this.hostname,port:this.port,secure:this.secure,path:this.path,query:c,forceJSONP:this.forceJSONP,timestampRequests:this.timestampRequests,timestampParam:this.timestampParam,flashPath:this.flashPath,policyPort:this.policyPort})};a.prototype.open=function(){var a=this.transports[0];this.readyState="opening";a=this.createTransport(a);a.open();this.setTransport(a)};a.prototype.setTransport=
function(a){f("setting transport %s",a.name);var b=this;this.transport&&(f("clearing existing transport %s",this.transport.name),this.transport.removeAllListeners());this.transport=a;a.on("drain",function(){b.onDrain()}).on("packet",function(a){b.onPacket(a)}).on("error",function(a){b.onError(a)}).on("close",function(){b.onClose("transport close")})};a.prototype.probe=function(a){function b(h){if(!e){e=!0;var j=Error("probe error: "+h);j.transport=c.name;c.close();c=null;f('probe transport "%s" failed because of error: %s',
a,h);g.emit("upgradeError",j)}}f('probing transport "%s"',a);var c=this.createTransport(a,{probe:1}),e=!1,g=this;c.once("open",function(){e||(f('probe transport "%s" opened',a),c.send([{type:"ping",data:"probe"}]),c.once("packet",function(h){e||("pong"==h.type&&"probe"==h.data?(f('probe transport "%s" pong',a),g.upgrading=!0,g.emit("upgrading",c),f('pausing current transport "%s"',g.transport.name),g.transport.pause(function(){if(!e&&!("closed"==g.readyState||"closing"==g.readyState))f("changing transport and sending upgrade packet"),
c.removeListener("error",b),g.emit("upgrade",c),g.setTransport(c),c.send([{type:"upgrade"}]),c=null,g.upgrading=!1,g.flush()})):(f('probe transport "%s" failed',a),h=Error("probe error"),h.transport=c.name,g.emit("upgradeError",h)))}))});c.once("error",b);c.open();this.once("close",function(){c&&(f("socket closed prematurely - aborting probe"),e=!0,c.close(),c=null)});this.once("upgrading",function(a){c&&a.name!=c.name&&(f('"%s" works - aborting "%s"',a.name,c.name),c.close(),c=null)})};a.prototype.onOpen=
function(){f("socket open");this.readyState="open";this.emit("open");this.onopen&&this.onopen.call(this);this.flush();if("open"==this.readyState&&this.upgrade&&this.transport.pause){f("starting upgrade probes");for(var a=0,b=this.upgrades.length;a<b;a++)this.probe(this.upgrades[a])}};a.prototype.onPacket=function(a){if("opening"==this.readyState||"open"==this.readyState)switch(f('socket receive: type "%s", data "%s"',a.type,a.data),this.emit("packet",a),this.emit("heartbeat"),a.type){case "open":this.onHandshake(g.parseJSON(a.data));
break;case "pong":this.setPing();break;case "error":var b=Error("server error");b.code=a.data;this.emit("error",b);break;case "message":this.emit("data",a.data),this.emit("message",a.data),b={data:a.data,toString:function(){return a.data}},this.onmessage&&this.onmessage.call(this,b)}else f('packet received with socket readyState "%s"',this.readyState)};a.prototype.onHandshake=function(a){this.emit("handshake",a);this.id=a.sid;this.transport.query.sid=a.sid;this.upgrades=this.filterUpgrades(a.upgrades);
this.pingInterval=a.pingInterval;this.pingTimeout=a.pingTimeout;this.onOpen();this.setPing();this.removeListener("heartbeat",this.onHeartbeat);this.on("heartbeat",this.onHeartbeat)};a.prototype.onHeartbeat=function(a){clearTimeout(this.pingTimeoutTimer);var b=this;b.pingTimeoutTimer=setTimeout(function(){if("closed"!=b.readyState)b.onClose("ping timeout")},a||b.pingInterval+b.pingTimeout)};a.prototype.setPing=function(){var a=this;clearTimeout(a.pingIntervalTimer);a.pingIntervalTimer=setTimeout(function(){f("writing ping packet - expecting pong within %sms",
a.pingTimeout);a.ping();a.onHeartbeat(a.pingTimeout)},a.pingInterval)};a.prototype.ping=function(){this.sendPacket("ping")};a.prototype.onDrain=function(){for(var a=0;a<this.prevBufferLen;a++)if(this.callbackBuffer[a])this.callbackBuffer[a]();this.writeBuffer.splice(0,this.prevBufferLen);this.callbackBuffer.splice(0,this.prevBufferLen);this.prevBufferLen=0;0==this.writeBuffer.length?this.emit("drain"):this.flush()};a.prototype.flush=function(){"closed"!=this.readyState&&(this.transport.writable&&
!this.upgrading&&this.writeBuffer.length)&&(f("flushing %d packets in socket",this.writeBuffer.length),this.transport.send(this.writeBuffer),this.prevBufferLen=this.writeBuffer.length,this.emit("flush"))};a.prototype.write=a.prototype.send=function(a,b){this.sendPacket("message",a,b);return this};a.prototype.sendPacket=function(a,b,c){a={type:a,data:b};this.emit("packetCreate",a);this.writeBuffer.push(a);this.callbackBuffer.push(c);this.flush()};a.prototype.close=function(){if("opening"==this.readyState||
"open"==this.readyState)this.onClose("forced close"),f("socket closing - telling transport to close"),this.transport.close();return this};a.prototype.onError=function(a){f("socket error %j",a);this.emit("error",a);this.onerror&&this.onerror.call(this,a);this.onClose("transport error",a)};a.prototype.onClose=function(a,b){if("opening"==this.readyState||"open"==this.readyState){f('socket close with reason: "%s"',a);var c=this;clearTimeout(this.pingIntervalTimer);clearTimeout(this.pingTimeoutTimer);
setTimeout(function(){c.writeBuffer=[];c.callbackBuffer=[];c.prevBufferLen=0},0);this.transport.removeAllListeners();var e=this.readyState;this.readyState="closed";this.id=null;"open"==e&&(this.emit("close",a,b),this.onclose&&this.onclose.call(this))}};a.prototype.filterUpgrades=function(a){for(var b=[],c=0,e=a.length;c<e;c++)~i(this.transports,a[c])&&b.push(a[c]);return b}},{"./emitter":2,"./transport":5,"./transports":7,"./util":12,debug:14,"engine.io-parser":16,global:19,indexof:21}],5:[function(b,
c){function a(a){this.path=a.path;this.hostname=a.hostname;this.port=a.port;this.secure=a.secure;this.query=a.query;this.timestampParam=a.timestampParam;this.timestampRequests=a.timestampRequests;this.readyState="";this.agent=a.agent||!1}b("./util");var g=b("engine.io-parser"),e=b("./emitter");c.exports=a;e(a.prototype);a.prototype.onError=function(a,b){var c=Error(a);c.type="TransportError";c.description=b;this.emit("error",c);return this};a.prototype.open=function(){if("closed"==this.readyState||
""==this.readyState)this.readyState="opening",this.doOpen();return this};a.prototype.close=function(){if("opening"==this.readyState||"open"==this.readyState)this.doClose(),this.onClose();return this};a.prototype.send=function(a){if("open"==this.readyState)this.write(a);else throw Error("Transport not open");};a.prototype.onOpen=function(){this.readyState="open";this.writable=!0;this.emit("open")};a.prototype.onData=function(a){this.onPacket(g.decodePacket(a))};a.prototype.onPacket=function(a){this.emit("packet",
a)};a.prototype.onClose=function(){this.readyState="closed";this.emit("close")}},{"./emitter":2,"./util":12,"engine.io-parser":16}],6:[function(b,c){function a(a){g.call(this,a);this.flashPath=a.flashPath;this.policyPort=a.policyPort}var g=b("./websocket"),e=b("../util"),h=b("debug")("engine.io-client:flashsocket");c.exports=a;var f=b("global"),i=f[["Active"].concat("Object").join("X")];e.inherits(a,g);a.prototype.name="flashsocket";a.prototype.doOpen=function(){function a(b){return function(){var a=
Array.prototype.join.call(arguments," ");h("[websocketjs %s] %s",b,a)}}if(this.check()){f.WEB_SOCKET_LOGGER={log:a("debug"),error:a("error")};f.WEB_SOCKET_SUPPRESS_CROSS_DOMAIN_SWF_ERROR=!0;f.WEB_SOCKET_DISABLE_AUTO_INITIALIZATION=!0;f.WEB_SOCKET_SWF_LOCATION||(f.WEB_SOCKET_SWF_LOCATION=this.flashPath+"WebSocketMainInsecure.swf");var b=[this.flashPath+"web_socket.js"];f.swfobject||b.unshift(this.flashPath+"swfobject.js");var c=this,e=function(a){if(b[a]){var f=b[a];if(j[f])e(++a);else{var g=document.createElement("script"),
i=!1;h('loading "%s"',f);g.onload=g.onreadystatechange=function(){if(!i&&!j[f]){var b=g.readyState;if(!b||"loaded"==b||"complete"==b)h('loaded "%s"',f),g.onload=g.onreadystatechange=null,i=!0,j[f]=!0,e(++a)}};g.async=1;g.src=f;var n=document.getElementsByTagName("head")[0];n.insertBefore(g,n.firstChild)}}else c.ready(function(){WebSocket.__addTask(function(){c.socket=new WebSocket(c.uri());c.addEventListeners()})})};e(0)}};a.prototype.doClose=function(){if(this.socket){var a=this;WebSocket.__addTask(function(){g.prototype.doClose.call(a)})}};
a.prototype.write=function(){var a=this,b=arguments;WebSocket.__addTask(function(){g.prototype.write.apply(a,b)})};a.prototype.ready=function(b){function c(){a.loaded||(843!=g.policyPort&&WebSocket.loadFlashPolicyFile("xmlsocket://"+g.hostname+":"+g.policyPort),WebSocket.__initialize(),a.loaded=!0);b.call(g)}if(!("undefined"==typeof WebSocket||!("__initialize"in WebSocket)||!f.swfobject)&&!(10>f.swfobject.getFlashPlayerVersion().major)){var g=this;if(document.body)return c();e.load(c)}};a.prototype.check=
function(){if("undefined"==typeof window||"undefined"!=typeof WebSocket&&!("__initialize"in WebSocket))return!1;if(i){var a=null;try{a=new i("ShockwaveFlash.ShockwaveFlash")}catch(b){}if(a)return!0}else for(var a=0,c=navigator.plugins.length;a<c;a++)for(var e=0,f=navigator.plugins[a].length;e<f;e++)if("Shockwave Flash"==navigator.plugins[a][e].description)return!0;return!1};var j={}},{"../util":12,"./websocket":11,debug:14,global:19}],7:[function(b,c,a){var g=b("xmlhttprequest"),e=b("./polling-xhr"),
h=b("./polling-jsonp"),c=b("./websocket"),f=b("./flashsocket");a.polling=function(a){var b=!1;if(i.location){var b="https:"==location.protocol,c=location.port;c||(c=b?443:80);b=a.hostname!=location.hostname||c!=a.port}a.xdomain=b;return new g(a)&&!a.forceJSONP?new e(a):new h(a)};a.websocket=c;a.flashsocket=f;var i=b("global")},{"./flashsocket":6,"./polling-jsonp":8,"./polling-xhr":9,"./websocket":11,global:19,xmlhttprequest:13}],8:[function(b,c){function a(a){g.call(this,a);i||(h.___eio||(h.___eio=
[]),i=h.___eio);this.index=i.length;var b=this;i.push(function(a){b.onData(a)});this.query.j=this.index}var g=b("./polling"),e=b("../util");c.exports=a;var h=b("global"),f=/\n/g,i;e.inherits(a,g);a.prototype.doClose=function(){this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);this.form&&(this.form.parentNode.removeChild(this.form),this.form=null);g.prototype.doClose.call(this)};a.prototype.doPoll=function(){var a=this,b=document.createElement("script");this.script&&(this.script.parentNode.removeChild(this.script),
this.script=null);b.async=!0;b.src=this.uri();b.onerror=function(b){a.onError("jsonp poll error",b)};var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c);this.script=b;e.ua.gecko&&setTimeout(function(){var a=document.createElement("iframe");document.body.appendChild(a);document.body.removeChild(a)},100)};a.prototype.doWrite=function(a,b){function c(){e();b()}function e(){if(g.iframe)try{g.form.removeChild(g.iframe)}catch(a){g.onError("jsonp polling iframe removal error",
a)}try{q=document.createElement('<iframe src="javascript:0" name="'+g.iframeId+'">')}catch(b){q=document.createElement("iframe"),q.name=g.iframeId,q.src="javascript:0"}q.id=g.iframeId;g.form.appendChild(q);g.iframe=q}var g=this;if(!this.form){var i=document.createElement("form"),h=document.createElement("textarea"),J=this.iframeId="eio_iframe_"+this.index,q;i.className="socketio";i.style.position="absolute";i.style.top="-1000px";i.style.left="-1000px";i.target=J;i.method="POST";i.setAttribute("accept-charset",
"utf-8");h.name="d";i.appendChild(h);document.body.appendChild(i);this.form=i;this.area=h}this.form.action=this.uri();e();this.area.value=a.replace(f,"\\n");try{this.form.submit()}catch(p){}this.iframe.attachEvent?this.iframe.onreadystatechange=function(){"complete"==g.iframe.readyState&&c()}:this.iframe.onload=c}},{"../util":12,"./polling":10,global:19}],9:[function(b,c){function a(){}function g(a){f.call(this,a);if(m.location){var b="https:"==location.protocol,c=location.port;c||(c=b?443:80);this.xd=
a.hostname!=m.location.hostname||c!=a.port}}function e(a){this.method=a.method||"GET";this.uri=a.uri;this.xd=!!a.xd;this.async=!1!==a.async;this.data=void 0!=a.data?a.data:null;this.agent=a.agent;this.create()}var h=b("xmlhttprequest"),f=b("./polling"),i=b("../util"),j=b("../emitter"),n=b("debug")("engine.io-client:polling-xhr");c.exports=g;c.exports.Request=e;var m=b("global"),r=m[["Active"].concat("Object").join("X")];i.inherits(g,f);g.prototype.request=function(a){a=a||{};a.uri=this.uri();a.xd=
this.xd;a.agent=this.agent||!1;return new e(a)};g.prototype.doWrite=function(a,b){var c=this.request({method:"POST",data:a}),e=this;c.on("success",b);c.on("error",function(a){e.onError("xhr post error",a)});this.sendXhr=c};g.prototype.doPoll=function(){n("xhr poll");var a=this.request(),b=this;a.on("data",function(a){b.onData(a)});a.on("error",function(a){b.onError("xhr poll error",a)});this.pollXhr=a};j(e.prototype);e.prototype.create=function(){var a=this.xhr=new h({agent:this.agent,xdomain:this.xd}),
b=this;try{n("xhr open %s: %s",this.method,this.uri);a.open(this.method,this.uri,this.async);if("POST"==this.method)try{a.setRequestHeader("Content-type","text/plain;charset=UTF-8")}catch(c){}"withCredentials"in a&&(a.withCredentials=!0);a.onreadystatechange=function(){var c;try{if(4!=a.readyState)return;200==a.status||1223==a.status?c=a.responseText:setTimeout(function(){b.onError(a.status)},0)}catch(e){b.onError(e)}if(null!=c)b.onData(c)};n("xhr data %s",this.data);a.send(this.data)}catch(f){setTimeout(function(){b.onError(f)},
0);return}r&&(this.index=e.requestsCount++,e.requests[this.index]=this)};e.prototype.onSuccess=function(){this.emit("success");this.cleanup()};e.prototype.onData=function(a){this.emit("data",a);this.onSuccess()};e.prototype.onError=function(a){this.emit("error",a);this.cleanup()};e.prototype.cleanup=function(){if("undefined"!=typeof this.xhr){this.xhr.onreadystatechange=a;try{this.xhr.abort()}catch(b){}r&&delete e.requests[this.index];this.xhr=null}};e.prototype.abort=function(){this.cleanup()};r&&
(e.requestsCount=0,e.requests={},m.attachEvent("onunload",function(){for(var a in e.requests)e.requests.hasOwnProperty(a)&&e.requests[a].abort()}))},{"../emitter":2,"../util":12,"./polling":10,debug:14,global:19,xmlhttprequest:13}],10:[function(b,c){function a(a){g.call(this,a)}var g=b("../transport"),e=b("../util"),h=b("engine.io-parser"),f=b("debug")("engine.io-client:polling");c.exports=a;var i=b("global");e.inherits(a,g);a.prototype.name="polling";a.prototype.doOpen=function(){this.poll()};a.prototype.pause=
function(a){function b(){f("paused");c.readyState="paused";a()}var c=this;this.readyState="pausing";if(this.polling||!this.writable){var e=0;this.polling&&(f("we are currently polling - waiting to pause"),e++,this.once("pollComplete",function(){f("pre-pause polling complete");--e||b()}));this.writable||(f("we are currently writing - waiting to pause"),e++,this.once("drain",function(){f("pre-pause writing complete");--e||b()}))}else b()};a.prototype.poll=function(){f("polling");this.polling=!0;this.doPoll();
this.emit("poll")};a.prototype.onData=function(a){var b=this;f("polling got data %s",a);h.decodePayload(a,function(a){if("opening"==b.readyState)b.onOpen();if("close"==a.type)return b.onClose(),!1;b.onPacket(a)});"closed"!=this.readyState&&(this.polling=!1,this.emit("pollComplete"),"open"==this.readyState?this.poll():f('ignoring poll - transport state "%s"',this.readyState))};a.prototype.doClose=function(){function a(){f("writing close packet");b.write([{type:"close"}])}var b=this;"open"==this.readyState?
(f("transport open - closing"),a()):(f("transport not open - deferring close"),this.once("open",a))};a.prototype.write=function(a){var b=this;this.writable=!1;this.doWrite(h.encodePayload(a),function(){b.writable=!0;b.emit("drain")})};a.prototype.uri=function(){var a=this.query||{},b=this.secure?"https":"http",c="";if("ActiveXObject"in i||e.ua.chromeframe||e.ua.android||e.ua.ios6||this.timestampRequests)!1!==this.timestampRequests&&(a[this.timestampParam]=+new Date);a=e.qs(a);if(this.port&&("https"==
b&&443!=this.port||"http"==b&&80!=this.port))c=":"+this.port;a.length&&(a="?"+a);return b+"://"+this.hostname+c+this.path+a}},{"../transport":5,"../util":12,debug:14,"engine.io-parser":16,global:19}],11:[function(b,c){function a(a){g.call(this,a)}var g=b("../transport"),e=b("ws"),h=b("engine.io-parser"),f=b("../util");b("debug")("engine.io-client:websocket");c.exports=a;b("global");f.inherits(a,g);a.prototype.name="websocket";a.prototype.doOpen=function(){if(this.check()){var a=this.uri();this.socket=
new e(a,void 0,{agent:this.agent});this.addEventListeners()}};a.prototype.addEventListeners=function(){var a=this;this.socket.onopen=function(){a.onOpen()};this.socket.onclose=function(){a.onClose()};this.socket.onmessage=function(b){a.onData(b.data)};this.socket.onerror=function(b){a.onError("websocket error",b)}};"undefined"!=typeof navigator&&/iPad|iPhone|iPod/i.test(navigator.userAgent)&&(a.prototype.onData=function(a){var b=this;setTimeout(function(){g.prototype.onData.call(b,a)},0)});a.prototype.write=
function(a){var b=this;this.writable=!1;for(var c=0,e=a.length;c<e;c++)this.socket.send(h.encodePacket(a[c]));setTimeout(function(){b.writable=!0;b.emit("drain")},0)};a.prototype.onClose=function(){g.prototype.onClose.call(this)};a.prototype.doClose=function(){"undefined"!==typeof this.socket&&this.socket.close()};a.prototype.uri=function(){var a=this.query||{},b=this.secure?"wss":"ws",c="";if(this.port&&("wss"==b&&443!=this.port||"ws"==b&&80!=this.port))c=":"+this.port;this.timestampRequests&&(a[this.timestampParam]=
+new Date);a=f.qs(a);a.length&&(a="?"+a);return b+"://"+this.hostname+c+this.path+a};a.prototype.check=function(){return!!e&&!("__initialize"in e&&this.name===a.prototype.name)}},{"../transport":5,"../util":12,debug:14,"engine.io-parser":16,global:19,ws:22}],12:[function(b,c,a){var g=b("global"),e=!1;a.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c};a.keys=Object.keys||function(a){var b=[],c=Object.prototype.hasOwnProperty,e;for(e in a)c.call(a,e)&&b.push(e);return b};
a.on=function(a,b,c,e){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener&&a.addEventListener(b,c,e)};a.load=function(b){if(g.document&&"complete"===document.readyState||e)return b();a.on(g,"load",b,!1)};"undefined"!=typeof window&&a.load(function(){e=!0});var h=/^[\],:{}\s]*$/,f=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,i=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,j=/(?:^|:|,)(?:\s*\[)+/g,n=/^\s+/,m=/\s+$/;a.parseJSON=function(a){if("string"!=typeof a||!a)return null;a=
a.replace(n,"").replace(m,"");if(g.JSON&&JSON.parse)return JSON.parse(a);if(h.test(a.replace(f,"@").replace(i,"]").replace(j,"")))return(new Function("return "+a))()};a.ua={};a.ua.webkit="undefined"!=typeof navigator&&/webkit/i.test(navigator.userAgent);a.ua.gecko="undefined"!=typeof navigator&&/gecko/i.test(navigator.userAgent);a.ua.android="undefined"!=typeof navigator&&/android/i.test(navigator.userAgent);a.ua.ios="undefined"!=typeof navigator&&/^(iPad|iPhone|iPod)$/.test(navigator.platform);a.ua.ios6=
a.ua.ios&&/OS 6_/.test(navigator.userAgent);a.ua.chromeframe=Boolean(g.externalHost);var r=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,z="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");a.parseUri=function(a){for(var a=r.exec(a||""),b={},c=14;c--;)b[z[c]]=a[c]||"";return b};a.qs=function(a){var b=
"",c;for(c in a)a.hasOwnProperty(c)&&(b.length&&(b+="&"),b+=encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b};a.qsParse=function(a){for(var b={},a=a.split("&"),c=0,e=a.length;c<e;c++){var f=a[c].split("=");b[decodeURIComponent(f[0])]=decodeURIComponent(f[1])}return b}},{global:19}],13:[function(b,c){var a=b("has-cors");c.exports=function(b){b=b.xdomain;try{if("undefined"!=typeof XMLHttpRequest&&(!b||a))return new XMLHttpRequest}catch(c){}if(!b)try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(h){}}},
{"has-cors":20}],14:[function(b,c){function a(b){return!a.enabled(b)?function(){}:function(c){c instanceof Error&&(c=c.stack||c.message);var f=new Date,g=f-(a[b]||f);a[b]=f;c=b+" "+c+" +"+a.humanize(g);window.console&&console.log&&Function.prototype.apply.call(console.log,console,arguments)}}c.exports=a;a.names=[];a.skips=[];a.enable=function(b){try{localStorage.debug=b}catch(c){}for(var f=(b||"").split(/[\s,]+/),g=f.length,j=0;j<g;j++)b=f[j].replace("*",".*?"),"-"===b[0]?a.skips.push(RegExp("^"+
b.substr(1)+"$")):a.names.push(RegExp("^"+b+"$"))};a.disable=function(){a.enable("")};a.humanize=function(a){return 36E5<=a?(a/36E5).toFixed(1)+"h":6E4<=a?(a/6E4).toFixed(1)+"m":1E3<=a?(a/1E3|0)+"s":a+"ms"};a.enabled=function(b){for(var c=0,f=a.skips.length;c<f;c++)if(a.skips[c].test(b))return!1;c=0;for(f=a.names.length;c<f;c++)if(a.names[c].test(b))return!0;return!1};try{window.localStorage&&a.enable(localStorage.debug)}catch(g){}},{}],15:[function(b,c){function a(b){if(b){for(var c in a.prototype)b[c]=
a.prototype[c];return b}}var g=b("indexof");c.exports=a;a.prototype.on=function(a,b){this._callbacks=this._callbacks||{};(this._callbacks[a]=this._callbacks[a]||[]).push(b);return this};a.prototype.once=function(a,b){function c(){g.off(a,c);b.apply(this,arguments)}var g=this;this._callbacks=this._callbacks||{};b._off=c;this.on(a,c);return this};a.prototype.off=a.prototype.removeListener=a.prototype.removeAllListeners=function(a,b){this._callbacks=this._callbacks||{};if(0==arguments.length)return this._callbacks=
{},this;var c=this._callbacks[a];if(!c)return this;if(1==arguments.length)return delete this._callbacks[a],this;var i=g(c,b._off||b);~i&&c.splice(i,1);return this};a.prototype.emit=function(a){this._callbacks=this._callbacks||{};var b=[].slice.call(arguments,1),c=this._callbacks[a];if(c)for(var c=c.slice(0),g=0,j=c.length;g<j;++g)c[g].apply(this,b);return this};a.prototype.listeners=function(a){this._callbacks=this._callbacks||{};return this._callbacks[a]||[]};a.prototype.hasListeners=function(a){return!!this.listeners(a).length}},
{indexof:21}],16:[function(b,c){c.exports=b("./lib/")},{"./lib/":17}],17:[function(b,c,a){b=b("./keys");a.protocol=2;var g=a.packets={open:0,close:1,ping:2,pong:3,message:4,upgrade:5,noop:6},e=b(g),h={type:"error",data:"parser error"};a.encodePacket=function(a){var b=g[a.type];void 0!==a.data&&(b+=String(a.data));return""+b};a.decodePacket=function(a){var b=a.charAt(0);return Number(b)!=b||!e[b]?h:1<a.length?{type:e[b],data:a.substring(1)}:{type:e[b]}};a.encodePayload=function(b){if(!b.length)return"0:";
for(var c="",e,g=0,h=b.length;g<h;g++)e=a.encodePacket(b[g]),c+=e.length+":"+e;return c};a.decodePayload=function(b,c){var e;if(""==b)return c(h,0,1);e="";for(var g,m,r=0,z=b.length;r<z;r++)if(m=b.charAt(r),":"!=m)e+=m;else{if(""==e||e!=(g=Number(e)))return c(h,0,1);m=b.substr(r+1,g);if(e!=m.length)return c(h,0,1);if(m.length){e=a.decodePacket(m);if(h.type==e.type&&h.data==e.data)return c(h,0,1);if(!1===c(e,r+g,z))return}r+=g;e=""}if(""!=e)return c(h,0,1)}},{"./keys":18}],18:[function(b,c){c.exports=
Object.keys||function(a){var b=[],c=Object.prototype.hasOwnProperty,h;for(h in a)c.call(a,h)&&b.push(h);return b}},{}],19:[function(b,c){c.exports=function(){return this}()},{}],20:[function(b,c){var a=b("global");c.exports="XMLHttpRequest"in a&&"withCredentials"in new a.XMLHttpRequest},{global:19}],21:[function(b,c){var a=[].indexOf;c.exports=function(b,c){if(a)return b.indexOf(c);for(var h=0;h<b.length;++h)if(b[h]===c)return h;return-1}},{}],22:[function(b,c){function a(a,b){return b?new e(a,b):
new e(a)}var g=function(){return this}(),e=g.WebSocket||g.MozWebSocket;c.exports=e?a:null;e&&(a.prototype=e.prototype)},{}]},{},[1])(1)});Object.create||(Object.create=function(d){function b(){}b.prototype=d;return new b});
var notiIcon=function(){var d=null,b=!1,c={init:function(a){d=$("#"+a).hide();c.__proto__=d.__proto__;return d},show:function(){b||d.show();return c},hide:function(){d.hide();return c},suppressed:function(){return b},suppress:function(a){b=!0;a=parseFloat(a);a=isNaN(a)?1E3:a;setTimeout(function(){b=!1},a);return c},stop_suppress:function(){b=!1;return c},text:function(a){return"undefined"!=typeof a?(d.text(a),c):d.text()},increment:function(a){if(!b){var g=parseInt(d.text());isNaN(g)&&(g=0);d.text(g+
a)}return c},count:function(){var a=parseInt(d.text());return isNaN(a)?0:a},reset:function(a){if(!0===a||d.text()!=rs.Disconnected)d.text(0),d.hide().attr("");return c},disconnected:function(){d.text(rs.Disconnected||"Disconnected").show()}};return c}(),Channel=function(d){function b(){if(g!==a.open){var f;f="https:"==document.location.protocol?"wss://"+document.location.host+"/socket":"ws://"+document.location.host+"/socket";null==e?(e=new eio.Socket(f),e.on("open",function(){g=a.open;"function"===
typeof d.open&&d.open();null!==h&&(notiIcon.reset(!0),clearTimeout(h),h=null)}),e.on("message",function(a){"object"===typeof d.handler&&(c=d.handler);var a=JSON.parse(a),b=c[a.method];if("function"!=typeof b)throw"unhandled function";b(a.data)}),e.on("close",function(){g=a.closed;notiIcon.disconnected();var c=function(){g==a.open?(clearTimeout(h),notiIcon.reset(!0)):0<e&&(b(),e--,h=setTimeout(c,2^2E3*(3-e)))},e=3;setTimeout(c,1E3);"function"===typeof d.close&&d.close()})):e.open()}}var c={},a={closed:"closed",
open:"open"},g=a.closed,e,h=null;return Object.create({connect:b,send:function(){},connected:function(){return g===a.open}})},channel=new Channel({open:function(){},close:function(){},handler:{data_change:function(d){notiIcon.increment(d.count).show();notiIcon.suppressed()||gridRefresher.queueRefresh()},config_change:function(d){"boolean"===typeof d.started&&startButton(d.started)}}});channel.connect();
var Refresher=function(){var d=0,b=!1,c=function(){},a=!0;c.prototype={queueRefresh:function(){!0==b||!1==a||(b=!0,window.setTimeout(function(){var a=notiIcon.count();a!=d&&0!=a&&(d=a,dgrid.autoRefresh());b=!1},2E3))},enable:function(b){a=!1!==b}};return c}(),gridRefresher=new Refresher;$(function(){$("#tbtnRefresh").button({text:!0,icons:{primary:"ui-icon-refresh"}}).click(function(){dgrid.loadData(!0);channel.connected()||channel.connect()});notiIcon.init("notiNumber")});var DGrid=function(){function d(a){H=H||[];"function"==typeof a&&H.push(a)}function b(){return k.getGridParam("page")}function c(a,c){b()!=a?(k.setGridParam({page:a}),d(c),A()):c()}function a(){L?window.setTimeout(a,10):k.restoreCell(B,u)}function g(){return k.getGridParam("rowNum")}function e(a){a=$(a).closest("tr.jqgrow");return 0===$(a).length?!1:a[0].rowIndex}function h(a){var b=t.mod,c;for(c in b)if(b[c].name==a)return b[c].label;return a}function f(a){y=$("div",a)[0].id.replace(/^jqgh_list_/,
"");x=h(y)}function i(a){y=t.mod[a-1].name;x=h(y)}function j(a){y=t.mod[a-1].name;return $("#jqgh_list_"+y).closest("th")}function n(a){r();j(a).addClass("ui-state-highlight")}function m(a){B=e(a);u=$.jgrid.getCellIndex(a);C=$(a).closest("tr.jqgrow").attr("id");return u}function r(){$("#container th.ui-state-highlight").removeClass("ui-state-highlight")}function z(a){a.closest("tr").removeClass("ui-state-hover").removeClass("selected-row")}function v(a,b){var c=[],d=[];if(empty(a))return{mod:c,names:[]};
for(var e in a){var g=a[e],f={};f.name=g.replace(/ /g,"_vts_space_");countOfThisColumn=0;empty(b)||(countOfThisColumn=b[g]);f.label=g;f.index=g;f.editable=fullControl?!0:!1;f.sortable=!1;"__id"==g&&(f.key=!0,f.hidden=!0);c.push(f);d.push(g+" ("+countOfThisColumn+")")}return{mod:c,names:a,colNames:d}}function R(a,b){var c=empty(a)||0==a.length,d=empty(b)||0==b.length;if(c!=d)return!1;if(!0==c)return!0;for(var e in a)if(a[e]!=b[e])return!1;return!0}function J(a){remoteCall("get_page",{rows:0,page:1},
function(b){t=v(b.columns,b.countsPerColumn);a()})}function q(){0<$("#mnuInsertValue.ui-state-disabled").length||c(1,function(){D(0,1)})}function p(){function a(){isHeaderSelected()?get_count(x,function(a){var a=a.count,d=g(),e=b(),f=a/d+1,h=a%d+1,N=0;$(t.names).each(function(a){if(this==x)return N=a+1,!1});f!=e?c(f,function(){k.editCell(h,N,!0)}):k.editCell(h,N,!0)}):c(MAX_NUM)}if(!(0<$("#mnuAddEnd.ui-state-disabled").length)){var d=$("input",k);0<d.length?(d=d.closest("td")[0],m(d),dgrid.cellSaveFunc=
a,k.saveCell(B,u)):a()}}function s(a,b,c){if(void 0==b)$("td."+a,k).removeClass(a);else return b=k[0].rows.namedItem(b),c=$(b.cells[c]),(b=c.hasClass(a))&&c.removeClass(a),b}function l(a){a=j(a);return 0<$(".dup-check",a).length}function w(a){void 0==a&&(a=j(u));var a=$("div",a),c=$(".dup-check",a);if(0==c.length)return a.append($('<span class="dup-check"/>')),!0;c.remove();for(var a=g(),c=(b()-1)*a,d=0;d<a;d++)s("cell-dup",c+d,u);return!1}function A(a,b){colAction(!1);r();"function"===typeof b&&
(I=b);a?(E=!0,empty(k.GridUnload)||k.GridUnload(),J(G)):k.trigger("reloadGrid")}function D(a,b){var c=x,e=function(){n(u);k.editCell(b,u,!0);colAction(!0)};remoteCall("insert_cell",{key:c,value:"",idx:a},function(a){a.success?(d(e),A(),K(c)):alert(a.msg)})}function F(a,b){function c(a){return a.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",")}var d=$(".ui-paging-info"),e=d.text(),g=e.lastIndexOf(" "),f=parseInt(e.substr(g),10);(!0===b||f<=a)&&d.html(e.substr(0,g+1)+c(parseInt(a,10)+1))}function K(a){a||
(a=x);get_count(a,function(b){var b=b.count,c=0;$(t.names).each(function(b){if(this==a)return c=b+1,!1});var d=k.jqGrid("getGridParam","colModel");k.jqGrid("setLabel",d[c].name,d[c].name+" ("+b+")")})}function G(){k=$("#list");k.jqGrid({autoencode:!0,loadtext:rs.loading||"Loading...",url:"/data/get_page/",mtype:"GET",colModel:t.mod,colNames:t.colNames,datatype:"json",jsonReader:{repeatitems:!1},autowidth:!0,height:"auto",pager:"#pager",rowNum:20,rownumbers:!0,rownumWidth:30,rowList:[10,20,30],viewrecords:!0,
gridview:!0,recordtext:rs.viewPage,formatter:{integer:{thousandsSeparator:",",defaultValue:"0"}},emptyrecords:rs.emptyRecords,pgtext:rs.page,cellEdit:!0,cellsubmit:"remote",cellurl:"/data/edit_cell",onCellSelect:function(b,c,d,g){colAction(!0);b=$(".edit-cell input",this);b.css("display","none");z(b);B=e(g.target);u=c;i(c);n(c);L?a(10):k.restoreCell(B,u)},ondblClickRow:function(a,b,c){M=k.getCell(a,c);k.editCell(b,c,!0)},beforeSaveCell:function(){L=!0},beforeEditCell:function(){},errorCell:function(){},
afterRestoreCell:function(){},afterEditCell:function(a,b,c,d){z($("input",k));document.getElementById(d+"_"+b).select()},afterSaveCell:function(a,c,d,e,f){L=!1;null!=M&&k.setCell(a,f,M);l(f)&&findDup(d,a,c,function(b){b&&(k.setCell(a,f,"","cell-dup",""),$("td.cell-dup",k).attr("dup-tooltip",rs.duplicated))});null!=O&&(d=O,O=null,d());for(var d=a,h=e;0<h&&s("empty-cell",d--,f);h--);e==g()&&b()==k.getGridParam("lastpage")&&(A(),K(c));F(a)},beforeSubmitCell:function(a,b,c,d,e){d=t.mod;C=a;var g,f;for(f in d){var h=
d[f];if(h.name==b){g=h.label;break}}s("cell-dup",a,e);return{key:g,value:c}},afterSubmitCell:function(a,b,c){a=eval("("+a.responseText+")");!0==a.success?(M=null,notiIcon.suppress(),K(c)):alert(a.msg);return[!0]},beforeProcessing:function(a){this.loading=!0;if(!1===a.success)return document.location=document.location.href,!1;var b=a.columns;R(b,t.names)?E&&(E=!1):(E=!0,t=v(b,a.countsPerColumn));for(var b=a.rows,c=g(),d=c*(a.page-1)+b.length,c=c-b.length;0<c--;)b.push({__id:d++});if(0!=b.length){var c=
a.rows[0],d=/ /g,e;for(e in c)if(!(0>e.search(d))){var c=e.replace(d,"_vts_space_"),f;for(f in b){var h=b[f];h[c]=h[e];delete h[e]}}}a.total!=MAX_NUM&&(window.status=rs.totalRows+": "+a.total,window.setTimeout('window.status = ""',1E3));e=g();f=a.rows;0==f.length?(e*=a.page-1,a.rows.push({__id:e})):f.length<e&&0<f.length&&(e=f[f.length-1].__id+1,a.rows.push({__id:e}))},gridComplete:function(){currentPageSearched(!1);if(E)E=!1,k.GridUnload(),G();else{var a=H;if(a&&0<a.length){for(var b in a)a[b]();
H=null}P||notiIcon.reset().suppress();I&&(I(),I=null)}$("input.ui-pg-input").attr("size",7);this.loading=!1},loadError:function(){I=null},loadComplete:function(a){k=$("#list");k.setGridWidth($(window).width()-2,!1);var c=(a.page-1)*g(),d=25+5*Math.max(0,c.toString().length-3)+"px";$(".jqgfirstrow td:first-child").css("width",d);$("#list_rn").css("width",d);var e=a.rows,j=!1;$(t.mod).each(function(a){var b=t.mod[a].name,a=a+1;if("__id"!=b)for(var d=e.length-1;0<=d;d--){if(void 0!=e[d][b]){j=!0;break}k.setCell(c+
d,a,"","empty-cell","")}});!j&&1==b()&&F(-1,!0);$("td",this).mousedown(function(a){$("#container td.ui-state-highlight").removeClass("ui-state-highlight");m(this);n(u);3===a.which&&$(this).addClass("ui-state-highlight")});$("#container th.ui-th-column").dblclick(function(){f(this);updateColumnDlg("Edit")}).mousedown(function(a){f(this);a:{var b=x,c;for(c in t.mod)if(t.mod[c].label==b){u=parseInt(c)+1;break a}u=void 0}colAction(!0);r();setUniqueMenuFlag();$(this).addClass("ui-state-highlight");1===
a.which&&$("#headMenu").css("display","none")}).contextMenu("headMenu",{menuStyle:{minWidth:"15em"},shadow:!1,bindings:{mnuClearColumn:clearColumn,mnuDeleteColumn:deleteColumn,mnuInsertValue:q,mnuAppendValue:p,mnuCheckUnique:function(){var a=w();setUniqueMenuFlag(a)},mnuAddColumnLeft:addColumnLeft,mnuAddColumnRight:addColumnRight,mnuChangeColumn:changeColumn,mnuMoreInfo:moreInfo},onContextMenu:function(){hideAllPops();fullControl||$("#mnuClearColumn, #mnuDeleteColumn, #mnuInsertValue, #mnuAppendValue, #mnuAddColumnLeft,#mnuAddColumnRight, #mnuChangeColumn").attr("disabled",
"disabled").addClass("ui-state-disabled").unbind();return!0}});$("tr.jqgrow",this).contextMenu("cellMenu",{menuStyle:{minWidth:"11em"},shadow:!1,bindings:{edit:function(){0<$("#edit.ui-state-disabled").length||k.editCell(B,u,!0)},add:function(){0<$("#add.ui-state-disabled").length||D(C,B)},del:function(){0<$("#del.ui-state-disabled").length||delete_data(C,x)},mnuIsUnique:function(){if(!(0<$("#mnuIsUnique.ui-state-disabled").length)){var a=k.getCell(C,y);findDup(a,C,y,function(a){a?alert(rs.isNotUnique):
alert(rs.isUnique)})}}},onContextMenu:function(a){function b(a,c){!0==c?a.attr("disabled","disabled").addClass("ui-state-disabled").unbind():!1==c&&a.removeAttr("disabled").removeClass("ui-state-disabled")}colAction(!0);hideAllPops();a=a.target;b($("#del,#mnuIsUnique"),$(a).hasClass("empty-cell"));fullControl||b($("#del,#add, #edit"),!0);remoteCall("check_item",{rowid:C,colname:h(y),action:"is_end"},function(a){a.success&&fullControl&&$("#add,#del").each(function(){b($(this),!a[this.id])})});if(0==
m(a))return!1;0<u&&i(u);return!0}})}})}var x=null,y=null,L=!1,t,E=!1,B,u,C,k,H=null,O=null,M=null,I,P,Q=function(){};jQuery.extend(Q.prototype,{onLoad:function(){k=$("#list");$("#reload").click(function(){k.trigger("reloadGrid")})},initGrid:function(){empty(t)?J(G):G()},loadData:A,updateCurrentColName:K,checkingUnique:function(){l(u)},toggleUniqueChk:function(a){w(a)},removeHighlight:s,insertCell:D,loadGrid:G,getPageSize:g,colName:function(a){if(void 0==a)return x;x=a},colInfo:function(){return t},
getColumnName:function(){return x=h(y)},getCols:function(){var a=t.mod,b=[],c;for(c in a){var d=a[c].name,e=parseInt(c,10)+1,e=dgrid.grid().getCol(e,!0);b.push({name:d,col:e})}return b},moveToPage:function(a){k.setGridParam({page:a});A()},addStart:q,addEnd:p,grid:function(){return k},currentPage:b,nextPage:function(){b()>=k.getGridParam("lastpage")||!0!=this.loading&&c(b()+1)},previousPage:function(){1>=b()||!0!=this.loading&&c(b()-1)},navigateToRow:function(a,d){var e=g(),f=b(),e=a/e+(0<a%e?1:0);
e!=f&&c(e,d)},autoRefresh:function(){!0!==this.loading&&!(0<$("input",k).length)&&(P=!0,A(!1,function(){P=!1}))},loading:!1});return Q}(),dgrid=new DGrid;jQuery.extend(jQuery.jgrid.formatter.integer,{thousandsSeparator:","});$(function(){dgrid.onLoad()});var MAX_NUM=9007199254740992,fullControl=!0;String.prototype.format=function(){var d=arguments;return this.replace(/\{(\d+)\}/g,function(b,c){return d[c]})};function updateHelpSetting(d){localStorage.setItem("isLocalHelp",d)}function initializeHelpMenu(){"true"==localStorage.getItem("isLocalHelp")&&(document.getElementById("helpoffline").checked=!0,document.getElementById("helponline").checked=!1)}
function openHelpCenter(){!0==document.getElementById("helpoffline").checked?$.get("/help/Index.htm").done(function(){window.open("/help/Index.htm","_blank").focus()}).fail(function(){onLocalHelpFailure()}):window.open("https://admhelp.microfocus.com/lr/en/12.60-12.62/help/WebHelp/Content/VTS/c_getting-started.htm","_blank").focus()}
function setClipboard(){var d=!!document.documentMode,b=document.createElement("textarea");b.style.cssText="position: absolute; left: -1000px; top: -1000px";b.textContent="https://admhelp.microfocus.com/vugen/en/latest/help/WebHelp/Content/Download-Help-Center.htm";document.body.appendChild(b);if(!0==d)window.clipboardData.setData("text",b.textContent);else{var d=document.getSelection(),c=document.createRange();c.selectNode(b);d.removeAllRanges();b.select();d.addRange(c);document.execCommand("copy");
d.removeAllRanges()}document.body.removeChild(b)}function onLocalHelpFailure(){confirmDlg(rs.message,rs.notFoundLocalHelp,setClipboard)}
(function(){Date.fromISO=isNaN(new Date("2013-03-13T17:20:29.380Z"))?function(d){var b,c=/^(\d{4}\-\d\d\-\d\d([tT][\d:\.]*)?)([zZ]|([+\-])(\d\d):(\d\d))?$/.exec(d)||[];if(c[1]){d=c[1].split(/\D/);b=0;for(var a=d.length;b<a;b++)d[b]=parseInt(d[b],10)||0;d[1]-=1;d=new Date(Date.UTC.apply(Date,d));if(!d.getDate())return NaN;c[5]&&(b=60*parseInt(c[5],10),c[6]&&(b+=parseInt(c[6],10)),"+"==c[4]&&(b*=-1),b&&d.setUTCMinutes(d.getUTCMinutes()+b));return d}return NaN}:function(d){return new Date(d)}})();
$(window).resize(function(){$("#list").setGridWidth($(window).width()-2,!0)}).bind("mousewheel DOMMouseScroll",function(d){var b=$(window);0<d.originalEvent.wheelDelta||0>d.originalEvent.detail?0==b.scrollTop()&&dgrid.previousPage():(d=b.height()+b.scrollTop()-$(document).height(),2>Math.abs(d)&&dgrid.nextPage())});$(window).keydown(function(d){switch(d.which){case 33:case 34:case 36:case 35:var b,d=d.which;36==d?b=1:35==d?b=MAX_NUM:33==d?b=dgrid.currentPage()-1:34==d&&(b=dgrid.currentPage()+1);dgrid.moveToPage(b)}});
function hideAllPops(){$(".pop-menu, #jqContextMenu").css("display","none")}function showMenu(d,b){hideAllPops();d.css("display","block").css(b)}$(function(){initControls();loadSettings();initializeHelpMenu();initSettings();$(window).unload(function(){saveSettings()});$("html").click(hideAllPops)});function empty(d){return null==d||void 0==d||"string"==typeof d&&0==d.length}function defEmpty(d,b){return empty(d)?b:d}
function getCookie(d){var b,c,a,g=document.cookie.split(";");for(b=0;b<g.length;b++)if(c=g[b].substr(0,g[b].indexOf("=")),a=g[b].substr(g[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==d)return unescape(a)}jQuery.ensureScript=function(){var d={};return function(b,c){if(d[b])c&&c();else return d[b]=!0,jQuery.getScript(b).done(c)}}();function setCookie(d,b,c){var a=new Date;a.setDate(a.getDate()+c);b=escape(b)+(null==c?"":"; expires="+a.toUTCString());document.cookie=d+"="+b}
function Polling(){this.hostid=parseInt(1E3*Math.random());this.inPolling=!1}Polling.prototype.isPrimary=function(){var d=getCookie("longpolling"),b=!0;if(!empty(d)&&(d=d.split("*"),new Date(d[0])>(new Date).getTime()-6E4&&(1>=d.length||d[1]!=this.hostid)))b=!1;!0==b&&(d=(new Date).toGMTString()+"*"+this.hostid,setCookie("longpolling",d));return b};var _polling=new Polling;function checktext(d,b){0<$("#"+d).val().length?$("#"+b).removeAttr("disabled"):$("#"+b).attr("disabled","disabled")}
function parse(d){var b={},d=d.split("&"),c;for(c in d){var a=d[c].split("=");2==a.length&&(b[a[0]]=decodeURIComponent(unescape(a[1])))}return b}function serialize(d){var b={},c;for(c in d)b[c]=encodeURIComponent(d[c]);return $.param(b)}function confirmDlg(d,b,c){$("#confirm").html("<p>"+b+"</p>").dialog("option","title",d).dialog("open")[0].dlgfunc=c}
function alert(d,b,c){d=$("#alert").html("<p>"+d+"</p>").dialog("option","title",empty(b)?rs.message:b).dialog("open");if("function"==typeof c)$("#btnAlertClose").on("click",function(){$("#btnAlertClose").off("click",this);c()});return d}$(document).ajaxError(function(d,b,c){if(0!=b.readyState){var a=rs[b.status];empty(a)?window.status="Error:{0} {1} {2}".format(b.status,d.msg,c.url):(alert(a),window.status="error accessing {0}".format(c.url));blocker.unblock()}});
var _defaultOptions={hideError:!1,type:"GET"};function remoteCall(d,b,c,a){a=a?$.extend({},_defaultOptions,a):_defaultOptions;$.ajax({url:"/data/"+d,cache:!1,data:b,type:a.type,complete:function(b){if(200==b.status){var e=null;try{empty(b.responseText)||(e=eval("("+b.responseText+")"))}catch(h){}e?!1==e.success&&!0!=a.hideError&&(empty(e.msg)?alert("{0}: Unspecfied Error".format(d)):alert(e.msg)):alert("{0}: Invalid reponse".format(d));c(e||{})}},timeout:function(){alert("timeout")}})}
function getUrlWithPort(d){return document.location.protocol+"//"+document.location.host+"/port="+d}function getUrlOfMainInst(){return document.location.protocol+"//"+document.location.host}var _settings;
function initSettings(){remoteCall("get_settings",null,function(d){if(d.success){var b=location.host.search(/:/),c=location.host;0<b&&(c=location.host.substring(0,b));$("#txtserver").text(c);_settings=d.settings;$("#txtPort").val(_settings.port);"None"!=_settings.auth?(auth(),$("#lblUser").css("display",""),$.browser.msie||$("#lblLogout").hide()):afterAuth();"NamedInstance"==_settings.mode&&(document.title="VTS - "+_settings.name,$("#instancename").text("("+_settings.name+")"),$("#txtDlgPort").attr("disabled",
"disabled"),$("#miInstDefault").attr("href",getUrlOfMainInst()),$("#mnuStart,#mnuStop").unbind("click").attr("disabled","disabled").attr("title",rs.canOnlyOnMainInst));gridRefresher&&gridRefresher.enable(_settings.autoRefreshGrid);startButton(_settings.started)}else empty(d.msg)||alert(d.msg,"Error",function(){$(document.body).css("display","none")})},{hideError:!0})}function loadKey(d){return d&&window.localStorage?window.localStorage.getItem(d):null}
function saveKey(d,b){d&&window.localStorage&&window.localStorage.setItem(d,b)}function loadSettings(){$(".preserve").each(function(){var d=loadKey(this.id);empty(d)||$(this).val(d)})}function saveSettings(){var d={};$(".preserve").each(function(){this.id&&(d[this.id]=$(this).val())});for(var b in d)saveKey(b,d[b])}
function initControls(){$("button, ul#icons li").hover(function(){$(this).addClass("ui-state-hover")},function(){$(this).removeClass("ui-state-hover")});$("#dlgColInfo").dialog({autoOpen:!1,width:400,modal:!0,resizable:!1,buttons:[{id:"btnColInfo",text:rs.ok,click:function(){var d=$("#chkIndex"),b=d.prop("checked"),c=$("#dlgColInfo");b==c.data("old")&&c.dialog("close");remoteCall("set_index",{colname:dgrid.colName(),index:b},function(a){!0==a.success&&(d.prop("checked",a.indexed),c.dialog("close"))})}}]});
$("#mnuCheckUnique").click(function(){var d=dgrid.toggleUniqueChk();setUniqueMenuFlag(d)});$("#mnuMoreInfo").click(moreInfo);$("#confirm").dialog({autoOpen:!1,width:400,modal:!0,resizable:!1,buttons:function(){var d={};d[rs.ok]=function(){var b=$(this)[0].dlgfunc;$.isFunction(b)&&b();$(this)[0].dlgfunc=null;$(this).dialog("close")};d[rs.cancel]=function(){$(this).dialog("close")};return d}()});$("#alert").dialog({autoOpen:!1,width:400,modal:!0,resizable:!0,buttons:[{id:"btnAlertClose",text:rs.close,
click:function(){$(this).dialog("close")}}]});$("#chkNewColumn").click(function(){var d=$(this).is(":checked"),b=$("#txtNewColumn"),c=$("#drpColumn");d?(b.show(),c.hide()):(c.show(),b.hide())})}function moreInfo(){var d=dgrid.getColumnName();$("#lblColName").html(d);remoteCall("col_info",{colname:d},function(b){b.success&&($("#chkIndex").prop("checked",b.indexed),$("#dlgColInfo").dialog("open").data("old",b.indexed))})}function findDup(d,b,c,a){find_dup(dgrid.getColumnName(c),d,a)}
function find_dup(d,b,c){remoteCall("check_item",{colname:d,value:b,action:"has_dup"},function(a){a.success&&c(a.duplicated)})}
$(function(){$("#txtDlgPort").bind("keyup",function(){$("#btnStart").button(function(d){var b=/^\d{1,5}$/;return!(empty(d)||0!=d.search(b))}($(this).val())?"enable":"disable")});$("#dlgStartServer").dialog({autoOpen:!1,width:"auto",modal:!0,resizable:!1,buttons:[{id:"btnStart",text:rs.enable,click:function(){$("#txtDlgServer").val();var d=$("#txtDlgPort").val();start_server(!0,d,function(b){b.started?(startButton(b.started),$("#txtPort").val(parseInt(d,10)),$("#dlgStartServer").dialog("close")):$(".autherror").html(rs.portInUse).show()},
!0)}},{text:rs.close,click:function(){$(this).dialog("close")}}]});0<$("#mnuLanguage li").length?$("#mnuLanguage li").click(function(){var d=$("span.value",this).text();setCookie("ln",d,365);document.location=document.location.href;document.location.reload(!0)}):$("#lblLanguage").hide();$("#mnuEnableAPI").menu({menuStyle:{width:"200px"}}).click(function(){$(this).css("display","none")});$("#options").click(function(d){$.ensureScript("options.js");d.stopPropagation()});$("#helpcenter").click(function(d){$("#mnuHelp").menu();
var b=$(this).position();b.top+=$(this).height();b.left=Math.min(b.left,$(window).width()-$("#mnuHelp").width()-10);showMenu($("#mnuHelp"),b);d.stopPropagation()});$("#miHelpOptions").mouseenter(function(){setTimeout(function(){$("#mnuOptions").not(":visible")&&$("#mnuOptions").show()},350)});$("#miOpenHelp").click(openHelpCenter);$("#miOpenHelp1").click(openHelpCenter);$("#miOpenHelp2").click(openHelpCenter);$('input[type="checkbox"]').on("change",function(){$('input[type="checkbox"]').not(this).prop("checked",
!1);"helponline"==$(this).attr("id")?updateHelpSetting("false"):updateHelpSetting("true")});$("#mnuStart,#mnuStop").click(function(d){var b=$(this).position();b.top+=$("span.enable-script").height();b.left-=Math.max(b.left+$("#mnuEnableAPI").width()+20-$(window).width(),0);showMenu($("#mnuEnableAPI"),b);d.stopPropagation()});$("#btnStartDlg").click(function(){$("#txtDlgServer").text($("#txtserver").text());$("#txtDlgPort").val($("#txtPort").val()).focus().trigger("keyup");$(".autherror").hide();$("#dlgStartServer").dialog("open");
$("#btnStartDlg")});$("#btnStop").click(function(){start_server(!1,null,function(d){startButton(d.started)})})});function startButton(d){!0==d?($("#mnuStart").hide(),$("#mnuStop").show()):($("#mnuStop").hide(),$("#mnuStart").show())}function start_server(d,b,c,a){remoteCall("start_server",{start:d,port:b},function(a){a.success?($(".autherror").hide(),$.isFunction(c)&&c(a)):$(".autherror").html(a.msg).show()},{hideError:a})}
function Blocker(){this.opts={css:{border:"none",padding:"15px","border-radius":"10px","font-size":"1.2em"}}}Blocker.prototype.block=function(d){this.opts.message=d||rs.pleaseWait;$.blockUI(this.opts)};Blocker.prototype.unblock=function(d){"function"==typeof d?$.unblockUI({onUnblock:d}):$.unblockUI(this.opts)};Blocker.prototype.message=function(d){0<d.length&&$.message(d,this.opts)};var blocker=new Blocker,Status={inProgress:1,failed:2,succeeded:3};
function checkStatus(d,b){remoteCall("job_status",{jobid:d},function(c){c.success&&(c=c.job,1===c.status?(blocker.message(c.msg),setTimeout(function(){checkStatus(d,b)},1E3)):(blocker.unblock(),b(c)))})}
$(function(){$("#dlgExport").dialog({modal:!0,width:"auto",autoOpen:!1,resizable:!1,buttons:[{id:"btnExport",text:rs.startExport,click:function(){var d=$("#rdoExpCsv").is(":checked");$(".autherror").hide();if(d)document.documentMode?(d=document.createElement("a"),d.click&&(d.setAttribute("href","/data/export_csv"),d.style.display="none",document.body.appendChild(d),d.click())):window.open("/data/export_csv","_blank"),$(this).dialog("close"),alert(rs.exportStarted.format('<a href="/data/export_csv">',
"</a>"));else{var b=$("#txtExpTable"),d=$("#txtExportConn").val(),c=$.trim(b.val());b.val(c);b=$("#chkDropTable").is(":checked");if(!d||!c)$(".autherror").html(rs.connectionMissing).show();else{var a=$(this).dialog("close");blocker.block();export_database(d,c,b,function(b){b.success?setTimeout(function(){checkStatus(b.jobid,function(a){a.status===Status.failed?alert(a.msg):a.status===Status.succeeded&&alert(rs.exportSuccessful.format(a.msg))})},1E3):(blocker.unblock(),a.dialog("open"),alert(b.msg))})}}}},
{text:rs.close,click:function(){$(this).dialog("close");$(".autherror").hide()}}]});$("#dlgImport").dialog({modal:!0,width:"auto",autoOpen:!1,resizable:!1,buttons:[{id:"btnImport",text:rs.startImportBtn,disabled:"disabled",click:function(){function d(a){!0==a.success?setTimeout(function(){checkStatus(a.jobid,function(a){a.status===Status.failed?alert(a.msg):alert(rs.importSuccessful);dgrid.loadData(!0)})},1E3):blocker.unblock(function(){$(this).dialog("open");var b=rs.importFailed;empty(a.msg)||(b+=
" "+rs.error+':<br />"'+a.msg+'"');alert(b)})}if($("#rdoImpCsv").is(":checked")){if(empty($("#fileToUpload").val()))return alert(rs.chooseFile);$(this).dialog("close");blocker.block();var b=$("#drpSeparator").val();ajaxFileUpload({separator:[b]},d)}else{var b=$("#txtImportConn").val(),c=$("#txtSql").val();!b||!c?alert(rs.sqlMissing):(blocker.block(),$(this).dialog("close"),import_database(b,c,d))}}},{text:rs.close,click:function(){$(this).dialog("close")}}]});$("#tbtnImport").button({text:!0,icons:{primary:"ui-icon-import"}}).click(function(){$("#dlgImport").dialog("open")});
$("#tbtnExport").button({text:!0,icons:{primary:"ui-icon-export"}}).click(function(){$("#dlgExport").dialog("open")});$("#fileToUpload,#drpSeparator").click(function(){$("#rdoImpCsv").click()});$("#txtSql,#txtImportConn,#btnImpTestConn").click(function(){$("#rdoImpDb").click()});$("#rdoImpDb").click(function(){$("#optImpDb").removeClass("ui-state-disabled");$("#btnImpTestConn").removeAttr("disabled");$("#optImpCsv,#optImpCsv2").addClass("ui-state-disabled")});$("#rdoImpCsv").click(function(){$("#optImpDb").addClass("ui-state-disabled");
$("#btnImpTestConn").attr("disabled","disabled");$("#optImpCsv,#optImpCsv2").removeClass("ui-state-disabled")});$("#chkDropTable,#txtExportConn,#txtExpTable").click(function(){$("#rdoExpDb").click()});$("#rdoExpDb").click(function(){$("#optExpDb").removeClass("ui-state-disabled");$("#btnExpTestConn").removeAttr("disabled")});$("#rdoExpCsv").click(function(){$("#optExpDb").addClass("ui-state-disabled");$("#btnExpTestConn").attr("disabled","disabled")});$("input[name=importtype]").click(function(){$("#btnImport").button("enable")});
$("input[name=exporttype]").click(function(){$("#btnExport").button("enable")});$("#btnImpTestConn").button().click(function(){var d=$("#txtImportConn").val();test_connection(d)});$("#btnExpTestConn").button().click(function(){var d=$("#txtExportConn").val();test_connection(d)});$("#toolbar").addClass("flat").mouseover(function(){$(this).removeClass("flat")}).mouseout(function(){$(this).addClass("flat")})});
function test_connection(d){var b=$("#dlgExport,#dlgImport");b.addClass("wait");var c=alert(rs.pleaseWait);remoteCall("test_connection",{conn:d},function(a){b.removeClass("wait");c.dialog("close");a.success?alert(rs.testConnSuccess):alert(rs.testConnFailed+(empty(a.msg)?".":':<br />"{0}"'.format(a.msg)))},{hideError:!0})}function import_database(d,b,c){remoteCall("import_database",{conn:d,sql:b},function(a){c(a)},{hideError:!0,type:"POST"})}
function export_database(d,b,c,a){remoteCall("export_database",{conn:d,tbl:b,droptbl:c},a,{hideError:!0})}
$(function(){function d(b,a){var d=$.trim($("#txtColName",b).val());if(!empty(d)){var e="add"==a?b.prop("left"):null;"__id"==e&&(e="");var h=dgrid.colName();update_column(d,h,a,e,function(a){a.success?($(".autherror").hide(),dgrid.loadData(d!=h),b.dialog("close")):$(".autherror").html(a.msg).show()})}}$("#mnuDeleteAll").click(function(){deleteColumn(dgrid.colName())});$("#mnuColumn").menu({menuStyle:{width:"600px"}}).click(function(){$("#mnuColumn").css("display","none")});$("#tmnuClearColumn").click(function(){clearColumn()});
$("#tbtnDeleteTable").button({text:!0,icons:{primary:"ui-icon-close"}}).click(function(){clearTable()});$("#tbtnActions").button().click(function(b){var a=$(this).position();a.top+=$("#tbtnActions").height();setUniqueMenuFlag();showMenu($("#mnuColumn"),a);b.stopPropagation()}).button("disable");$("#dlgCreateCol").dialog({autoOpen:!1,width:600,modal:!0,buttons:[{text:rs.ok,click:function(){$(this).dialog("close")}},{text:rs.cancel,click:function(){$(this).dialog("close")}}]});var b=function(b){b.keyCode==
$.ui.keyCode.ENTER&&$(b.delegateTarget).parent().find(".ui-dialog-buttonpane button:first").click()};$("#dlgColEdit").dialog({autoOpen:!1,width:320,resizable:!1,modal:!0,buttons:[{id:"btnColEdit",text:rs.save,click:function(){d($("#dlgColEdit"),"edit")}},{text:rs.cancel,click:function(){$(".autherror").hide();$(this).dialog("close")}}]}).keypress(b);$("#dlgColAdd").dialog({autoOpen:!1,width:320,resizable:!1,modal:!0,buttons:[{id:"btnColAdd",text:rs.save,click:function(){d($("#dlgColAdd"),"add")}},
{text:rs.cancel,click:function(){$(".autherror").hide();$(this).dialog("close")}}]}).keypress(b);$("#mnuAddColumnLeft").click(addColumnLeft);$("#mnuAddColumnRight").click(addColumnRight);$("#mnuChangeColumn").click(changeColumn)});function addColumnLeft(){if(!(0<$("#mnuAddColumnLeft.ui-state-disabled").length)){var d=null,b=0,c=dgrid.colInfo();$(c.names).each(function(a){if(this==dgrid.colName())return b=a,!1});0!=b&&(d=c.names[b-1]);updateColumnDlg("Add",d)}}
function addColumnRight(){0<$("#mnuAddColumnRight.ui-state-disabled").length||updateColumnDlg("Add",dgrid.colName())}function changeColumn(){0<$("#mnuChangeColumn.ui-state-disabled").length||updateColumnDlg("Edit")}function setUniqueMenuFlag(d){void 0==d&&(d=dgrid.checkingUnique());var b=$("#imgCheckUnique,#imgCheckUnique1");d?b.addClass("ui-icon").addClass("ui-icon-check"):b.removeClass("ui-icon").removeClass("ui-icon-check")}
function updateColumnDlg(d,b){$(".autherror").hide();var c=$("#dlgCol"+d).dialog("open");c.prop("left",b);var a="Edit"==d?dgrid.colName():"";$("#txtColName",c).val(a).click().select()}function isHeaderSelected(){return 0<$("#container .ui-state-highlight").length}function clearTable(){confirmDlg(rs.deleteTable,rs.confirmDeleteAll,function(){delete_all()})}
function delete_all(){0<$("#mnuClearColumn.ui-state-disabled").length||remoteCall("delete_all",null,function(d){d.success&&(alert(rs.tableDeleted),dgrid.loadData(!0))})}function clearColumn(){if(!(0<$("#mnuClearColumn.ui-state-disabled").length)){var d=dgrid.colName();empty(d)?alert(rs.chooseColumn):confirmDlg(rs.clearContent,rs.confirmClear.format(d),function(){clear_column(d)})}}function clear_column(d){remoteCall("clear_column",{colname:d},function(b){b.success&&dgrid.loadData(!0)})}
function deleteColumn(){if(!(0<$("#mnuDeleteColumn.ui-state-disabled").length)){var d=dgrid.colName();empty(d)?alert(rs.chooseColumn):confirmDlg(rs.deleteColumn,rs.confirmDelete.format(d),function(){delete_column(d);dgrid.colName(null)})}}function delete_column(d){remoteCall("delete_column",{colname:d},function(b){b.success&&dgrid.loadData(!0)})}function update_column(d,b,c,a,g){remoteCall("update_column",{colname:d,curname:b,type:c,left:a},g,{hideError:!0})}
function get_count(d,b){var c=empty(d)?{}:{colname:d};remoteCall("get_count",c,function(a){a.success&&b(a)})}$(function(){$("#mnuAddEnd").click(dgrid.addEnd);$("#mnuInsertValue").click(dgrid.addStart)});function delete_data(d,b){remoteCall("delete_data",{colname:b,rowid:d},function(c){c.success?(dgrid.loadData(!1),dgrid.updateCurrentColName(b)):alert(c.msg)})}function afterAuth(){dgrid.initGrid()}
function auth(){remoteCall("auth",null,function(d){if(d.success){var b=d.display||d.user;$("#username").html(b);fullControl=d.isAdmin;fullControl||($("#tbtnImport").button("disable"),$("#tbtnDeleteTable").button("disable"),$("#mnuStart,#mnuStop").unbind("click").attr("disabled","disabled"),alert('<span class="ui-icon ui-icon-warning"></span>'+rs.userPermissionNeeded))}});afterAuth()}
$(function(){$("#logout").click(function(){document.execCommand("ClearAuthenticationCache","false");document.location=document.location.href})});function colAction(d){fullControl?$("#tbtnActions").button(d?"enable":"disable"):$("#tbtnActions").button("disable")}var _lastFoundPage=null,_startPage,_cpSearched=!1;function initSearch(){_lastFoundPage=null;_cpSearched=!1;dgrid.grid()&&(_startPage=dgrid.currentPage())}
function searchblur(){var d=$("#txtSearch");empty(d.val())&&d.removeClass("search-focus")}
$(function(){var d=$("#txtSearch");empty(d.val())||d.addClass("search-focus");$("#txtSearch").focus(function(){$(this).addClass("search-focus")});$("#txtSearch").blur(searchblur).keypress(function(b){b.keyCode==$.ui.keyCode.ENTER?($("#tbtnSearch").click(),window.setTimeout(function(){$("#txtSearch").focus()},1)):initSearch()}).bind("input",function(){empty($(this).val())&&dgrid.removeHighlight("highlight")});$("#tbtnSearch").button({text:!1,icons:{primary:"ui-icon-search"}}).click(function(){var b=
$("#txtSearch").val();empty(b)||(currentPageSearched()?searchDb(b):searchInPage(b))});initSearch()});RegExp.escape=function(d){return d.replace(RegExp("[.*+?|()\\[\\]{}\\\\]","g"),"\\$&")};function containValue(d,b){if(0<=b.search(d))return!0}function getNextStart(){var d=dgrid.grid().getDataIDs();return 0<d.length?parseInt(d.pop())+1:0}function currentPageSearched(d){if(void 0!=d)_cpSearched=!0==d;else return _cpSearched}
function searchInPage(d){var b=dgrid.getCols();dgrid.removeHighlight("highlight");$("th.ui-state-highlight").removeClass("ui-state-highlight");if(!empty(d)){var c=RegExp(RegExp.escape(d),"i"),a=0<b.length?b[0].col.length:0,g=0,e;for(e in b){containValue(c,b[e].name)&&(_lastFoundPage=dgrid.currentPage(),dgrid.grid().setLabel(b[e].name,"","ui-state-highlight"),g++);for(var h=0;h<a;h++){var f=b[e].col[h];if(containValue(c,f.value)){_lastFoundPage=dgrid.currentPage();var i=parseInt(e,10)+1;dgrid.grid().setCell(f.id,
i,"","highlight","");g++}}}currentPageSearched(!0);0==g&&searchDb(d)}}
function searchDb(d,b){function c(a){h=!1;if(a.success){if(a.timeout){e.start=a.start;var b=dgrid.getPageSize();blocker.block(rs.searchingPage.format(a.start/b));return remoteCall("search",e,c)}blocker.unblock();a.found?(_lastFoundPage=dgrid.currentPage(),(a=a.match)&&0<a.length&&dgrid.navigateToRow(a[0].index,function(){var a=$("#txtSearch").val();searchInPage(a);$("#txtSearch").focus()})):!1==a.found&&(1<_startPage||1<=_lastFoundPage?(_startPage=1,confirmDlg(rs.search,rs.searchEnd,function(){initSearch();
_startPage=1;searchDb(d,0)})):alert(rs.notFound))}else blocker.unblock()}var a=empty(b)?getNextStart():b,g=dgrid.getPageSize(),e={q:d,start:a,end:a+g},h=!0;window.setTimeout(function(){h&&blocker.block()},500);remoteCall("search",e,c)}var offscrn="-3000px",gid=0;
$.extend({createIframe:function(d,b){var c="jUploadFrame"+d,a='<iframe id="{0}" name="{0}" style="position:absolute; top:{1}; left:{1}" src="{2}"/>'.format(c,offscrn,"string"==typeof b?b:"javascript:void(0)");$(a).appendTo(document.body);return $("#"+c).get(0)},createUploadForm:function(d,b,c){var a=$('<form action="/" method="POST" name="{0}" id="{0}" enctype="multipart/form-data"></form>'.format("jUploadForm"+d));if(c)for(var g in c)$('<input type="hidden" name="{0}" value="{1}" />'.format(g,c[g])).appendTo(a);
b=$("#"+b);d="jUploadFile"+d;c=$(b).clone();$(b).attr("id",d).before(c).appendTo(a);$(a).css("position","absolute").css("top",offscrn).css("left",offscrn).appendTo("body");return a},ajaxFileUpload:function(d){var b=$.extend({},$.ajaxSettings,d),d=gid++,c=$.createUploadForm(d,b.fileElementId,"undefined"==typeof b.data?!1:b.data),a=$.createIframe(d,b.secureuri),d="jUploadFrame"+d;b.global&&!$.active++&&$.event.trigger("ajaxStart");var g=!1,e={};b.global&&$.event.trigger("ajaxSend",[e,b]);var h=function(d){try{var f=
(a.contentWindow||a.contentDocument).document;e.responseText=f.body?f.body.innerHTML:null;e.responseXML=f.XMLDocument?f.XMLDocument:f}catch(h){e.responseText=e.responseXML="{}"}if(e||"timeout"==d)g=!0,d="timeout"!=d?"success":"error","error"!=d?(f=$.uploadHttpData(e,b.dataType),b.success&&b.success(f,d),b.global&&$.event.trigger("ajaxSuccess",[e,b])):alert(b),b.global&&$.event.trigger("ajaxComplete",[e,b]),b.global&&!--$.active&&$.event.trigger("ajaxStop"),b.complete&&b.complete(e,d),$(a).unbind(),
setTimeout(function(){try{$(a).remove(),$(c).remove()}catch(d){$.handleError(b,e,null,d)}},100),e=null};0<b.timeout&&setTimeout(function(){g||h("timeout")},b.timeout);try{c.attr("action",b.url).attr("target",d).submit()}catch(f){$.handleError(b,e,null,f)}$("#"+d).load(h);return{abort:function(){}}},uploadHttpData:function(d,b){var c;c="xml"==b||!b?d.responseXML:d.responseText;if("json"==b){-1!=c.indexOf("<pre")&&(c=$("<div />").html(c),c=$("pre:first",c).html());try{return eval("("+c+")")}catch(a){return{}}}return c}});
function ajaxFileUpload(d,b){$.ajaxFileUpload({url:"/data/import_csv",secureuri:!1,fileElementId:"fileToUpload",dataType:"json",data:d,success:b,global:!0,error:function(b,a,d){alert("Error:"+d)}})};
