$(function(){$("#miLanguage,#miSample,#miInstMgr").click(function(a){a.stopPropagation()});initOption($("#options"));$("#txtInstName, #txtInstPort").change(function(){showMsg($("#dlgInstMgrAdd"),"",!1)}).bind("keyup",function(){var a=$("#txtInstName").val(),b=$("#txtInstPort").val(),a=!empty(a)&&!empty(b);$("#btnStartInst").button(a?"enable":"disable")});$("#btnStartInst").button().button("disable").click(function(){var a=$.trim($("#txtInstName").val()),b=$("#txtInstPort").val(),d=$("#dlgInstMgrAdd").parent().addClass("wait");
showMsg(d,"",!1);startInstance(a,b,function(a){d.removeClass("wait");if(!0==a.success){if(!empty(a.msg)){var f=getUrlWithPort(b);showMsg($("#dlgInstMgrAdd"),a.msg,!1);$("#openurl").prop("checked")&&setTimeout(function(){window.open(f,"_blank")},500)}}else showMsg($("#dlgInstMgrAdd"),a.msg,!0);listInstances()})});$("#btnStopInst").button().click(function(){showMsg(b,"",!1);var a=[];$(".listbody .ui-icon").each(function(){var b=$(this).parent().text();a.push(b)});if(0!==a.length){var b=$("#dlgInstMgrRemove").parent().addClass("wait");
stopInstances(a,function(a){b.removeClass("wait");a.success?(empty(a.msg)||showMsg(b,a.msg,!1),$(".listbody .ui-icon").each(function(){$(this).closest("li").detach()})):showMsg(b,a.msg,!0);listInstances()})}});$("#btnAddInst").click(function(){startInstanceDlg()});$("#btnRemoveInst").click(function(){stopInstanceDlg()});var b=function(){var a={};a[rs.close]=function(){$(this).dialog("close")};return a};"Default"==_settings.mode?($("#miInstDefault").parent().hide(),$("#dlgInstMgrAdd").dialog({width:"400px",
minHeight:300,autoOpen:!1,modal:!0,resizable:!1,buttons:b()}),$("#dlgInstMgrRemove").dialog({width:"400px",minHeight:430,autoOpen:!1,modal:!0,resizable:!0,buttons:b()})):$("#miInstMgr").parent().hide()});function popmenu(b,a){var c=a.position();c.top+=a.height();c.left=Math.min(c.left,$(window).width()-b.width()-10);showMenu(b,c)}
function initOption(){remoteCall("list_samples","",function(b){b.success&&updateSamplesMenu(b.list);fullControl||$("#mnuSamples li a").attr("disabled","disabled").addClass("ui-state-disabled");$("#mnuOption").menu();$("#mnuSamples li").click(function(){if(!(0<$("#mnuSamples li a.ui-state-disabled").length)){var a=$(".value",this).text();a&&importSample(a)}});$("#options").click(function(){popmenu($("#mnuOption"),$(this))}).click();$("#mnuOption").on("menufocus",function(a,b){"miInstMgr"===b.item.children().attr("id")&&
listInstances()})})}function updateSamplesMenu(b){for(i=0;i<b.length;i++){var a=$('<li><a href="#"><span class="ui-icon-dummy"></span><span class="value"g>_value</span>_display</a></li>'.replace(/_value/g,b[i].value).replace(/_display/g,b[i].display));$("#mnuSamples").append(a)}}function importSample(b){remoteCall("import_sample",{name:b},function(){dgrid.loadData(!0)})}function showMsg(b,a,c){b=$(".msg",b);b.text(a);b.show();c?b.addClass("errormsg"):b.removeClass("errormsg")}
function startInstance(b,a,c){remoteCall("start_instance",{name:b,port:a},function(a){c&&c(a)},{hideError:!0})}function stopInstances(b,a){remoteCall("stop_instances",{instances:JSON.stringify(b)},function(b){a&&a(b)},{hideError:!0})}function listInstances(b){remoteCall("list_instances",{},function(a){a.success&&(a=a.instances,updateInstancesMenu(a),b&&b(a))})}
function updateInstancesMenu(b){fullControl||($("#btnAddInst").attr("disabled","disabled").addClass("ui-state-disabled").unbind(),$("#btnRemoveInst").attr("disabled","disabled").addClass("ui-state-disabled").unbind());for($("#miInstances li:nth-child(4)");;){var a=$("#miInstances li:nth-child(4)");if(0<a.size())a.detach();else break}for(i=0;i<b.length;i++){var a=b[i],c=getUrlWithPort(a.port),d=null,d="stopped"===a.status?"ui-icon ui-icon-alert":"ui-icon-dummy",a='<li><a href="{0}" target="_blank"><span class="{3}"></span><span class="value">{1}</span>{2}: {1}</a></li>'.format(c,
a.port,a.name,d);$("#miInstances").append(a)}$("#mnuOption").menu("refresh")}function startInstanceDlg(){var b=$("#dlgInstMgrAdd").dialog("open");showMsg(b,"")}
function stopInstanceDlg(){var b=$("#dlgInstMgrRemove").dialog("open"),a=$("table.checklist").width();$("table.checklist").width(a);showMsg(b,"");$(".listbody li").detach();listInstances(function(a){for(i=0;i<a.length;i++){var b=a[i];err="stopped"===b.status?'<span style="color:red;float:right">{0}!</span>'.format(rs.error):"";var e=getUrlWithPort(b.port),b=$("<a >").attr("target","_blank").attr("href",e).text(b.name+":"+b.port);$(".listbody ol").append($("<li>").append($('<div class="mybox ui-icon-check" >')).append(b))}$(".listheader .mybox").unbind("click").click(function(){$(this).toggleClass("ui-icon").hasClass("ui-icon")?
$(".listbody .mybox").addClass("ui-icon"):$(".listbody .mybox").removeClass("ui-icon")});$(".listbody li").unbind("click").click(function(){$(".mybox",$(this)).toggleClass("ui-icon").hasClass("ui-icon")||$(".listheader .mybox").removeClass("ui-icon")})})};
