var fs=require("fs"),path=require("path"),querystring=require("querystring"),child_process=require("child_process"),csv=require("./ya-csv"),api=require("../api"),common=require("./common"),Util=common.Util,empty=Util.empty,globalize=common.Globalize,InstanceManager=require("./instmgr").InstanceManager,BATCH_SIZE=1E3,MAX_COLUMN_LENGTH=1E3,UTF8_BOM="\ufeff",DEFAULT_ENCODING="utf8",TIME_OUT=2E3,LAST_PAGE_NUMBER=9007199254740992,_tempFileDir=__dirname+"/Web/file",_adoUtility=__dirname+"/adoUtility.js",
_updateAPIs=/^(insert|edit|delete|clear|update|drop|import)/,_config=configure,_apiHttpServer=null,_apiService=null,changeMonitor=require("./notifier").changeMonitor;test_export="undefined"!=typeof UNIT_TEST&&!0===UNIT_TEST?function(a,c){exports[a]=c}:function(){};var is_local_run=!1;exports.set_local_run="undefined"!=typeof SECU_LOCAL_RUN&&!0===SECU_LOCAL_RUN?function(){is_local_run=!0}:null;
function initApiHttpServer(){_apiHttpServer=api.getHttpServer();_apiService=api.getApiService();_apiService.on("changed",function(){changeMonitor.changed()})}function getDb(){return _apiService}function handleError(a,c){var b=console.trace(),b=void 0==b?"":"\r\n"+console.trace();logger.error(c+b);a&&a.end(JSON.stringify({success:!1,msg:c.errmsg?c.errmsg:c.toString()}))}
function validateName(a){if(a.length>MAX_COLUMN_LENGTH)return!1;var c=/^[\w!#%$&amp;(-\/:-@\ u0080-\uFFFF]*$/;return!empty(a)&&c.test(a)&&/[^_.]/.test(a[0])&&/[^.]/.test(a[a.length-1])?!0:!1}function createCollection(a,c,b){a.createCollection(c,function(a){void 0!=b&&b(a)})}test_export("createCollection",createCollection);function dropCollection(a,c,b){a.deleteCollection(c,function(a){void 0!=b&&b(a)})}test_export("dropCollection",dropCollection);
function getApiServerConfig(a,c){a||(db=getDb(),a=db.system);var b={};db.open(function(){a.getConfig("start_status",function(d,e){var f=empty(e)?{}:JSON.parse(e),g={};if(null==f)b.port=_config.defaultApiPort,b.start=_config.defaultStart,g.port=_config.defaultApiPort,g.defaultApiPort=_config.defaultApiPort,g.start=_config.defaultStart,g.defaultStart=_config.defaultStart;else{f.defaultApiPort&&f.defaultApiPort==_config.defaultApiPort?b.port=f.port:(b.port=_config.defaultApiPort,g.defaultApiPort=_config.defaultApiPort,
g.port=_config.defaultApiPort);void 0!=f.defaultStart&&f.defaultStart==_config.defaultStart?b.start=f.start:(b.start=!0==_config.defaultStart,g.defaultStart=b.start,g.start=b.start);var h=!1;for(i in g){h=!0;break}if(h){for(i in g)f[i]=g[i];a.saveConfig("start_status",JSON.stringify(g),function(){})}}c(null,b)})})}function filterError(a){return null!=a&&"ns not found"!=a.errmsg?a:null}
Date.prototype.format=function(a){var c={"M+":this.getMonth()+1,"d+":this.getDate(),"h+":this.getHours(),"m+":this.getMinutes(),"s+":this.getSeconds(),"q+":Math.floor((this.getMonth()+3)/3),S:this.getMilliseconds()};/(y+)/.test(a)&&(a=a.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length)));for(var b in c)RegExp("("+b+")").test(a)&&(a=a.replace(RegExp.$1,1==RegExp.$1.length?c[b]:("00"+c[b]).substr((""+c[b]).length)));return a};
function getTables(a,c,b){a.getCache(function(a,e){var f=e.collectionInfos,g=[];if(null==f)return c(null,g);var h=[];for(i in f)h.push(f[i]);!0===b&&(h.sort(function(a,b){return a.order-b.order}),f=h);for(i in f)g.push(f[i].name);c(null,g)})}test_export("getTables",getTables);function getUser(a){var c=_config.admin.users,a=a.toLowerCase();for(i in c)if(c[i].user.toLowerCase()==a)return c[i];return null}
function getNtlmUser(a,c){var b=a.split("@");1<b.length&&(a=b[0],c=b.slice(1).join("@"));return c+"\\"+a}function isAdministrator(a){var c=_config.admin.role.administrator,b=_config.admin.role.user;if(0==c.length&&0==b.length)return!0;var a=a.toLowerCase(),d;for(d in c)if(c[d].toLowerCase()==a)return!0;return!1}
function insertColumnToInfoTable(a,c,b,d){a.getCache(function(e,f){cols=f.collectionInfos;var g,h,k=0,m,l=[];for(i in cols)l.push(cols[i]),k=Math.max(k,cols[i].order),m=void 0==m?cols[i].order:Math.min(m,cols[i].order);l.sort(function(a,b){return a.order-b.order});for(i in l)l[i].name==c&&(h=parseInt(i,10)),l[i].name==b&&(g=parseInt(i,10));if("undefined"==typeof g)throw"cannot find column with name "+rightcol;g=l[g];if("undefined"==typeof h)g.order=m-1;else if(l.length==h+1)g.order=k+1;else{var n=
function(b,c,d){if(!(c+1>=d.length)){var e=d[c+1];e===b?n(b,c+1,d):2>e.order-d[c].order&&(e.order=d[c].order+2,n(b,c+1,d),updateMeta(a,e,function(){f.invalidateCollectionOrder()}))}};g.order=l[h].order+1;n(g,h,l)}f.invalidateCollectionOrder();updateMeta(a,g,d)})}test_export("insertColumnToInfoTable",insertColumnToInfoTable);function updateMeta(a,c,b){"object"!=typeof c&&b("invalid data");a.updateMeta(c,b)}test_export("updateMeta",updateMeta);
function clearColumn(a,c,b){a.clearRecords(c,function(a){b(a)})}test_export("clearColumn",clearColumn);function countRows(a,c,b){var d=0;a.getCache(function(a,f){if(a)return c(a);var g=f.collectionInfos;if(empty(b)){var h={};for(i in g){var k=g[i],m=k.high-k.low;h[k.name]=m;d=Math.max(d,m)}c(null,d,h)}else{var k=f.collectionInfos[b];d=null==k?0:k.high-k.low;c(null,d)}})}test_export("countRows",countRows);
function refCount(a){var c=a;this.release=function(a){0==--c&&"function"==typeof a&&a()};this.addRef=function(){++c};this.releaseAll=function(a){c=0;"function"==typeof a&&a()}}function renameCollection(a,c,b,d){a.getCache(function(e,f){var g=f.collectionInfos[c];"undefined"==typeof g?d("Column does not exist."):(g.name=b,updateMeta(a,g,function(){delete f.collectionInfos[c];f.collectionInfos[b]=g;d()}))})}test_export("renameCollection",renameCollection);
function unicodeProcess(a,c,b,d){logger.info('run process: cscript "'+c.join('" "')+'"');var a=child_process.spawn(a,c,b),e="";a.on("exit",function(a){logger.info("error "+a+":"+e);d(a,e)});a.stderr.setEncoding("utf8");a.stdout.setEncoding("utf8");a.stdout.on("data",function(a){process.stdout.write(unescape(a))});a.stdout.on("error",function(a){logger.error(a)});a.stderr.on("data",function(a){e+=unescape(a)});this.child=a;this.stdout=a.stdout;this.stdin=a.stdin;this.stderr=a.stderr}
unicodeProcess.prototype.write=function(a){a=new Buffer(a,"ucs2");this.child.stdin.write(a)};unicodeProcess.prototype.on=function(a,c){this.child.on(a,c)};test_export("unicodeProcess",unicodeProcess);function execAdoUtility(a,c){var b=[_adoUtility,"//Nologo"].concat(a).concat("escape"),b=new unicodeProcess("cscript",b,{},c);b.write("\r\n");return b}function isPortValid(a){var c=/^\d{1,5}$/;return!empty(a)&&0==a.search(c)?(a=parseInt(a,10),0<a&&65535>=a):!1}
function deleteAll(a,c,b){c(a,function(c,e){if(c)return b(c);var f=new refCount(e.length);if(!e||0==e.length)return b(null,[]);for(i in e)dropCollection(a,e[i],function(a){if(a)return b(a,e);f.release(function(){b(null,e)})})})}test_export("deleteAll",deleteAll);function getEncoding(a){var c=DEFAULT_ENCODING;try{var b=new Buffer(2),d=fs.openSync(a,"r");fs.readSync(d,b,0,2,0);255==b[0]&&254==b[1]&&(c="ucs2")}finally{void 0!=d&&fs.closeSync(d)}return c}
function findNonExists(a,c,b){var d={};for(i in a)d[a[i]]=a[i];for(i=c.length-1;0<=i;i--)void 0!=d[c[i]]&&(c.splice(i,1),b.splice(i,1));return c}test_export("importCsv",importCsv);
function importCsv(a,c,b,d,e,f,g){function h(a,b){var c=function(){!0!=u&&(u=!0,a?e.updateStatus(Status.succeeded,""):(b=empty(b)?k.errorOccurred:b,e.updateStatus(Status.failed,b)),"function"===typeof g&&g(b))};if(0<q.length){var f=q;q=[];batchInsert(f,r,function(a){if(a)return e.updateStatus(Status.failed,a);c()})}else c();m&&fs.unlink(d,function(){})}var k=a.rs,m=!1!==f,a=getEncoding(d),l=csv.createCsvFileReader(d,{separator:b,quote:'"',escape:'"',comment:"",encoding:a}),n=!1,p=[],r=[],t=!1,u=!1;
l.addListener("end",function(){t=!0;h(!0);logger.info("end import.")});l.addListener("error",function(a){logger.error("Error reading the csv file. ",a.code,a.message);!0!==t&&(errmsg=a.code&&k.csvErrors&&k.csvErrors[a.code]?k.csvErrors[a.code]:a.message,e.updateStatus(Status.failed,errmsg),t=!0,l.pause(),l.end(),h(!1,errmsg))});var q=[],s=0;l.addListener("data",function(a){if(n){if(_config.normalizeCSV)for(;a.length<r.length;)a.push("");q.push(a);q.length>=BATCH_SIZE&&!0==n&&(a=q,q=[],l.pause(),batchInsert(a,
r,function(a){if(a)return l.end(),e.updateStatus(Status.failed,a);l.resume()}),s+=a.length,e.updateStatus(null,k.importing+" "+s))}else{l.pause();n="parsing";a:{var b=function(a){if(a)return e.updateStatus(Status.failed,a);n=!0;l.resume()};for(i in a){var d=a[i];if(!validateName(d)){l.pause();!empty(d)&&d.length>MAX_COLUMN_LENGTH&&(d=d.substring(0,MAX_COLUMN_LENGTH)+"...");h(!1,k.invalidColumnName+' "'+d+'"');break a}r.push(d);p.push(d)}getTables(c,function(a,d){if(a)return b(a);var e=p.slice(),f=
r.slice();findNonExists(d,e,f);if(0==f.length)l.resume(),b();else{if(a)return b(a);for(var g=new refCount(f.length);0<f.length;){var h=e.shift();f.shift();if(null==h)break;createCollection(c,h,function(a){if(a)return b(a);g.release(b)})}}})}}})}function batchInsert(a,c,b){var d=[];for(i in a)d.push(function(a){var b={};for(i in a)b[c[i]]=a[i];return b}(a[i]));_apiService.addStackMultiple(d,function(a){if(a)return b(a);b()})}
function getOneColumnData(a,c,b,d,e,f){0==d&&(d=1);b+=1;a.getRecords(c,b,b+d,function(a,b){if(a||null==b)return f(a);for(j in b){var d=parseInt(j,10);(empty(e[d])?e[d]={}:e[d])[c]=b[j]}f(null)})}test_export("getOneColumnData",getOneColumnData);
function GridData(){function a(c,b,d){getTables(c,function(e,f){if(e)return d(e);var g=[],h=new refCount(f.length);if(0==f.length)return d(e,g,f);for(i in f)getOneColumnData(c,f[i],b,BATCH_SIZE,g,function(e){if(e)return d(e,g,f);h.release(function(){d(null,g,f);0!=g.length&&a(c,b+BATCH_SIZE,d)})})},!0)}return{exportData:a,getMultiTablePage:function(a,b,d,e){var f=parseInt(d,10),g=parseInt(b,10);0>g&&(g=0);var h=e.rs,k=(g-1)*f,m=[];countRows(a,function(b,d,p){if(b)return handleError(e,b);if(0!=f){var r=
Math.floor((d+1)/f+(0<(d+1)%f?1:0));g=Math.min(g,r)}getTables(a,function(b,l){function q(){var a=k;for(i in m)m[i].__id=a++;e.end(JSON.stringify({rows:m,total:r,records:d,page:g,columns:s,countsPerColumn:p,timestamp:new Date}))}b&&handleError(e,b);if(0==l.length)e.end(JSON.stringify({rows:[{__id:0}],total:1,records:0,page:1,columns:["__id",h.newColumnName],timestamp:new Date}));else{var s=["__id"].concat(l),v=new refCount(l.length);for(i in l)getOneColumnData(a,l[i],k,f,m,function(a){if(a)return handleError(e,
a);v.release(q)})}},!0)})}}}
function exportToFile(a,c,b){var d=null,e=0,f=!0,g={};(new GridData).exportData(a,0,function(a,k,m){if(a)return b(a);if(f){if(!m||0==m.length)return b(null,e,[]);for(i in m)g[m[i]]=50;d=fs.createWriteStream(c);d.write(UTF8_BOM);writer=csv.createCsvStreamWriter(d);writer.writeRecord(m);f=!1}if(!k||0==k.length)return d.end(),b(null,e,g);for(i in k){var a=[],l=k[i];for(j in m){var n=m[j],p=l[n];void 0==p&&(p="");a.push(p);g[n]=Math.max(p.length,g[n])}writer.writeRecord(a)}e+=k.length})}
test_export("exportToFile",exportToFile);function searchMatchInOneColumn(a,c,b,d,e,f){var g=e+1;a.getRecords(c,g,g+BATCH_SIZE,function(a,c){if(a)return f(a,!1,null);if(null!=c&&0<c.length){for(i in c)if(0<=c[i].search(d)){var e={};e.index=g+parseInt(i,10);b.push(e)}f(null,!0,b)}else logger.info("no more records"),f(null,!1,b)})}
function searchOneMatch(a,c,b,d,e,f,g){ref=new refCount(e.length);var h=[],k=!1;if(0===e.length)return g(null,{match:h,found:!1}),!1;for(i in e)searchMatchInOneColumn(b,e[i],h,d,f,function(h,l,n){if(h)return g(h,null);k=k||l;(new Date).getTime()-a>TIME_OUT&&ref.releaseAll(function(){g(null,{timeout:!0,start:f,match:n})});n.length>BATCH_SIZE/2?ref.releaseAll(function(){g(null,{match:n,found:!0})}):ref.release(function(){if(!k||0<n.length)if(0<n.length){var h=0;imin=LAST_PAGE_NUMBER;for(i in n){var l=
n[i];l.index<imin&&(imin=l.index,h=i)}g(null,{match:[n[h]],found:!0})}else g(null,{match:n,found:!1});else searchOneMatch(a,c,b,d,e,f+BATCH_SIZE,g)})})}RegExp.escape=function(a){return a.replace(RegExp("[.*+?|()\\[\\]{}\\\\]","g"),"\\$&")};function Admin(a){this.options=a}test_export("Admin",Admin);Admin.prototype.last_updated=function(a,c,b){changeMonitor.handle(a,"true"===b["long"])};
Admin.prototype.get_settings=function(a,c){var b=this;getApiServerConfig(c,function(c,e){if(c)return handleError(a,c);e.auth=_config.admin.authentication;e.started=_apiHttpServer.started;e.autoRefreshGrid=b.options.autoRefreshGrid;e.name=b.options.name;e.mode=b.options.mode;e.mode==common.enumMode.NamedInstance&&(e.port=b.options.port,e.adminPort=configure.adminPort);a.end(JSON.stringify({success:!0,settings:e}))})};
Admin.prototype.get_count=function(a,c,b){countRows(c,function(b,c){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0,count:c}))},b.colname)};function ensureNotEmpty(a,c){return empty(a)?(c.end(JSON.stringify({success:!1,msg:c.rs.invalidParameters})),!1):!0}
Admin.prototype.insert_cell=function(a,c,b){var d=parseInt(b.idx,10),e=b.key,b=b.value,f={success:!0};ensureNotEmpty(e)&&(0==d?c.insertRecord(e,b,function(b){if(b)return handleError(a,b);a.end(JSON.stringify(f))}):(c={},c[e]=b,_apiService.update(c,d+1,function(b){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0,updated:new Date}))})))};
Admin.prototype.edit_cell=function(a,c,b){var d=a.rs;if("edit"!=b.oper)a.end(JSON.stringify({success:!1,msg:d.invalidParameters}));else{var c=parseInt(b.id,10),e=b.key;empty(e)?a.end(JSON.stringify({success:!1,msg:d.invalidParameters})):(d={},d[e]=b.value,_apiService.update(d,c+1,function(b){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0,updated:new Date}))}))}};
Admin.prototype.ensure_index=function(a,c,b){_apiService.ensureIndex(b.colname,function(b){if(null!=b)return handleError(a,b);a.end(JSON.stringify({success:!0}))})};Admin.prototype.search=function(a,c,b){var d=b.q;empty(d);var e=RegExp(RegExp.escape(d),"i"),f=parseInt(b.start,10);if(isNaN(f)||!isFinite(f))f=0;var g=(new Date).getTime();getTables(c,function(b,d){if(b)return handleError(a,b);searchOneMatch(g,a,c,e,d,f,function(b,c){if(b)return handleError(a,b);c.success=!0;a.end(JSON.stringify(c))})})};
function saveSetting(a,c,b){a.getConfig("start_status",function(d,e){if(d)return b(d);if(!empty(e)){var f=JSON.parse(e);for(i in f)void 0==c[i]&&(c[i]=f[i])}a.saveConfig("start_status",JSON.stringify(c),b)})}test_export("saveSetting",saveSetting);
Admin.prototype.start_server=function(a,c,b){var d=a.rs;if(empty(b.start)||"true"!=b.start&&"false"!=b.start||"true"==b.start&&!isPortValid(b.port))a.end(JSON.stringify({success:!1,msg:d.invalidPort}));else{if(this.options.mode===common.enumMode.NamedInstance)return handleError(a,"cannot call this command from a named instance");var d=parseInt(b.port,10),b="true"==b.start,e={start:b};!0==b?(d!=_apiHttpServer.port&&_apiHttpServer.started&&_apiHttpServer.stop(),_apiHttpServer.start(d),_apiHttpServer.started&&
(e.port=d)):_apiHttpServer.stop();InstanceManager.Instance.enableApiAccess(b);saveSetting(c,e,function(b){if(b)return handleError(a,b);b=_apiHttpServer.started;ret={success:!0,started:b};a.end(JSON.stringify(ret));changeMonitor.notifyConfig({started:b})})}};
Admin.prototype.start_instance=function(a,c,b){var d=a.rs,c=b.port,e=b.name;if(!isPortValid(b.port))return a.end(JSON.stringify({success:!1,msg:d.invalidPort})),!1;InstanceManager.Instance.addNewInstance({port:c,name:e},function(b){Util.empty(b)||(b.code&&("INST_STARTED"===b.code?a.end(JSON.stringify({success:!1,msg:d.InstanceStarted})):"PORT_IN_USE"===b.code&&a.end(JSON.stringify({success:!1,msg:d.PortNameInUse}))),a.end(JSON.stringify({success:!1,msg:b})));a.end(JSON.stringify({success:!0,msg:d.InstanceAddSucceed}))})};
Admin.prototype.stop_instance=function(a,c,b){var d=a.rs,c=InstanceManager.Instance,e=c.instances,f=parseInt(b.port,10),b=b.name;isNaN(f)&&Util.empty(b)&&a.end(JSON.stringify({success:!1,msg:d.invalidParameters}));var g=!1;for(i in e)if(!Util.empty(b)&&e[i].name===b||e[i].port==f){var g=!0,h=e[i];c.stopInstance(h.port,h.name,function(b){b?"NOINSTANCE"===b.code?a.end(JSON.stringify({success:!1,msg:d.cannotFindInstance.format(h.name)})):a.end(JSON.stringify({success:!1,msg:b})):a.end(JSON.stringify({success:!0,
msg:d.InstanceStoppedSuccessful}))})}g||a.end(JSON.stringify({success:!1,msg:d.cannotFindInstance.format(b)}))};
Admin.prototype.stop_instances=function(a,c,b){var d=a.rs,c=InstanceManager.Instance,b=JSON.parse(b.instances);null==b&&a.end(JSON.stringify({success:!1,msg:d.invalidParameters}));var e=[];for(i in b){var f=b[i].split(":");2!==f.length&&a.end(JSON.stringify({success:!1,msg:d.invalidParameters}));e.push({port:f[1],name:f[0]})}var g=[];0===e.length?a.end(JSON.stringify({success:!0,msg:d.InstanceStoppedSuccessful})):c.stopInstances(e,function(b){Util.empty(b)?a.end(JSON.stringify({success:!0,msg:d.InstanceStoppedSuccessful})):
b instanceof Array&&(g=b,a.end(JSON.stringify({success:!1,msg:d.cannotFindInstance.format(g.join(" "))})))})};Admin.prototype.stop_all_instances=function(a){var c=a.rs;InstanceManager.Instance.stopAllInstances(function(){a.end(JSON.stringify({success:!0,msg:c.InstanceStoppedSuccessful}))})};Admin.prototype.list_instances=function(a){var c=InstanceManager.Instance.listInstances();a.end(JSON.stringify({success:!0,instances:c}))};
Admin.prototype.auth=function(a,c,b,d){"Basic"==_config.admin.authentication?(d=d.headers.authorization)?(d=d.split(" "),d=(new Buffer(d[1],"base64")).toString().split(":")[0],c=getUser(d),b=isAdministrator(d),a.end(JSON.stringify({success:!0,user:d,display:c&&c.display?c.display:d,isAdmin:b}))):(logger.warning("no authorization header"),a.end(JSON.stringify({success:!1}))):"NTLM"==_config.admin.authentication?(c=getNtlmUser(d.ntlm.UserName,d.ntlm.DomainName),b=isAdministrator(c),a.end(JSON.stringify({success:!0,
user:d.ntlm.UserName,display:d.ntlm.UserName,isAdmin:b}))):a.end(JSON.stringify({success:!1}))};Admin.prototype.get_page=function(a,c,b){(new GridData).getMultiTablePage(c,b.page,b.rows,a)};
function exportCsvFile(a,c,b,d,e){function f(f){var h=[];for(name in d.columnSizes)h.push(d.columnSizes[name]);var k=d.job;execAdoUtility(["import",a,c,b,JSON.stringify(h)],function(b,c){if(0!=b){var h=d.rs.adoErrors?d.rs.adoErrors[b]:"";empty(h)&&(h=d.rs.errorOccurred+":<br />"+(f?f+"\n":"")+c);e(h)}else e(null);d.deleteFile&&fs.unlink(a,function(){})}).stdout.on("data",function(a){data=unescape(a);0==data.indexOf("status:")&&(data=data.substring(7),k&&k.updateStatus(null,data))})}d.dropTable?execAdoUtility(["drop",
c,b],function(a,b){var c=0!=a?b:null;console.log("table dropped");f(c)}):f()}test_export("exportCsvFile",exportCsvFile);var _importingOrExporting=!1;
Admin.prototype.export_database=function(a,c,b){var d=_tempFileDir+"/"+Util.getTempFileName(".csv"),e=a.rs;if(is_local_run)if(is_local_run=!1,!0==_importingOrExporting)a.end(JSON.stringify({success:!1,msg:e.importExportInProgress}));else{_importingOrExporting=!0;var f=Job.create();a.end(JSON.stringify({success:!0,jobid:f.jobid}));try{exportToFile(c,d,function(c,g,m){0==g&&0==m?(_importingOrExporting=!1,f.updateStatus(Status.failed,e.noDataToExport)):exportCsvFile(d,b.tbl,b.conn,{deleteFile:!0,dropTable:"true"===
b.droptbl,columnSizes:m,job:f,rs:a.rs},function(a){_importingOrExporting=!1;a?f.updateStatus(Status.failed,a):f.updateStatus(Status.succeeded,g)})})}catch(g){_importingOrExporting=!1}}else c=globalize.instance.processText("{{js.exportDbApiNote}}",a.rs),a.end(JSON.stringify({success:!1,msg:c}))};
Admin.prototype.job_status=function(a,c,b){c=parseInt(b.jobid,10);if(-1==c)return a.end(JSON.stringify({success:!1,error:a.rs.invalidParameters}));c=Job.AllJobs[c];if(empty(c))return a.end(JSON.stringify({success:!1,error:a.rs.invalidParameters}));"true"===b.deletejob&&c.unregister();b=globalize.instance.processText(c.msg,a.rs);a.end(JSON.stringify({success:!0,job:{status:c.status,msg:b}}))};function Job(){this.jobid=this.register()}Job.AllJobs={};Job.seed=0;Job.create=function(){return new Job};
Job.prototype.register=function(){var a=Job.seed++;Job.AllJobs[a]=this;this.created=new Date;this.status=Status.inProgress;return a};var Status={inProgress:1,failed:2,succeeded:3};Job.prototype.updateStatus=function(a,c){empty(a)||(this.status=a);this.lastUpdated=new Date;void 0!=c&&(this.msg=c)};Job.prototype.unregister=function(){delete Job.AllJobs[this.jobid]};
Admin.prototype.import_csv=function(a,c,b,d){var e=b.separator||"auto",f=b.path,g=!1!==b.deleteFile,b=__dirname+"/Web/file/",h=function(b){var e=Job.create();"function"===typeof d?importCsv(a,c,b,f,e,g,d):(importCsv(a,c,b,f,e,g),a.end(JSON.stringify({success:!0,jobid:e.jobid})))},k=path.basename(f);empty(k)||!validateName(k)||""!==path.relative(b,path.dirname(f))?(a.setHeader("Content-Type","application/json"),a.end(JSON.stringify({success:!1,msg:a.rs.cannotAccessFile.format(f)}))):fs.exists(b+path.basename(f),
function(b){if(b){if("\\t"==e)e="\t";else if("auto"==e){csv.detectSeparator(f,function(b,c){if(b)logger.error(b),handleError(a,b);else if(null==c){var d=a.rs;logger.warning("Cannot detect separator");a.end(JSON.stringify({success:!1,msg:d.cannotDetectSeparator}))}else h(c)});return}h(e)}else a.setHeader("Content-Type","application/json"),a.end(JSON.stringify({success:!1,msg:a.rs.cannotAccessFile.format(f)}))})};
Admin.prototype.export_csv=function(a,c){var b=new GridData,d=!0,e="VTS data "+(new Date).format("yyyy-MM-dd(hh_mm_ss)")+".csv",f=null;b.exportData(c,0,function(b,c,k){if(b)return d&&a.setHeader("content-type","text/html"),handleError({end:function(b){b=JSON.parse(b);a.end(b.errmsg)}},b);if(d&&(null==k||0==k.length))a.setHeader("Content-Type","text/html; charset=UTF-8"),a.end(a.rs.noDataToExport);else{d&&(a.setHeader("Content-Type","application/binary"),a.setHeader("Content-Disposition","attachment;filename="+
e),changeToDirect(a),a.write(UTF8_BOM,DEFAULT_ENCODING),f=csv.createCsvStreamWriter(a),f.writeRecord(k),d=!1);if(0==c.length)return a.end();for(i in c){b=[];for(j in k){var m=c[i][k[j]];b.push(void 0==m?"":m)}f.writeRecord(b)}}})};
Admin.prototype.delete_data=function(a,c,b){var d=b.colname,e=!0;empty(d)&&(e=!1);b=parseInt(b.rowid,10);0<=b||(e=!1);e?(e=function(b){if(b)return handleError(b);a.end(JSON.stringify({success:!0}))},0==b?c.retrieveRecord(d,e):c.retrieveBottom(d,e)):a.end(JSON.stringify({success:!1,msg:a.rs.invalidParameters}))};
Admin.prototype.import_local_file=function(a,c,b){var d=b.name;empty(d)||!validateName(d)?a.end(JSON.stringify({success:!1,msg:a.rs.invalidMessage})):(b.path=__dirname+"/Web/file/"+d,this.import_csv(a,c,b,function(b){a.end(JSON.stringify({success:empty(b),msg:b}))}))};
Admin.prototype.import_sample=function(a,c,b){var d=b.name;if(empty(d)||!validateName(d))a.end(JSON.stringify({success:!1,msg:a.rs.invalidMessage}));else{var d=__dirname+"\\..\\samples\\"+d+".csv",e=Util.getTempFileName(d);b.path=__dirname+"\\Web\\file\\"+e;Util.copyFile(d,b.path,function(d){Util.empty(d)?(b.deleteFile=!0,Admin.prototype.import_csv(a,c,b)):logger.error(d)})}};
Admin.prototype.list_samples=function(a){fs.readdir(__dirname+"/../samples",function(c,b){if(c)return a.end(JSON.stringify({success:!1,msg:c}));var d=[];for(i in b)if(0<=b[i].search(/\.csv$/ig)){var e=b[i].replace(/\.csv/ig,""),f=globalize.instance.processText("{{ page."+e+" }}",a.rs);if(f==="{{ page."+e+" }}"||""===f)f=e;d.push({value:e,display:f})}a.end(JSON.stringify({success:!0,list:d}))})};
Admin.prototype.update_column=function(a,c,b){var d=a.rs,e={success:!0};if(empty(b.colname)||!validateName(b.colname))a.end(JSON.stringify({success:!1,msg:d.invalidColumnName}));else{var f=b.colname,g=empty(b.curname)?"":b.curname,h=b.type;if("add"==h){var k=b.left;c.getCache(function(b,g){if(b)return handleError(a,b);if(void 0!=g.collectionInfos[f])return handleError(a,d.columnExists);createCollection(c,f,function(b){if(b)return handleError(a,b);insertColumnToInfoTable(c,k,f,function(b){if(null!=
b)return handleError(b);a.end(JSON.stringify(e))})})})}else"edit"==h?(empty(g)&&a.end(JSON.stringify(retInvalid)),g==f?a.end(JSON.stringify(e)):c.getCache(function(b,h){if(b)return handleError(a,b);if(void 0!=h.collectionInfos[f])return handleError(a,d.columnExists);h.collectionInfos[g]?renameCollection(c,g,f,function(b){if(b)return handleError(a,b);a.end(JSON.stringify(e))}):createCollection(c,f,function(b){if(b)return handleError(a,b);a.end(JSON.stringify(e))})})):a.end(JSON.stringify({success:!1,
msg:d.invalidParameters}))}};Admin.prototype.clear_column=function(a,c,b){var d=b.colname;clearColumn(c,d,function(b){if(b)return handleError(a,b);c.clearRecords(d,function(){a.end(JSON.stringify({success:!0}))})})};Admin.prototype.delete_column=function(a,c,b){c.deleteCollection(b.colname,function(b){if(filterError(b))return handleError(a,b);a.end(JSON.stringify({success:!0}))})};Admin.prototype.col_info=function(a,c,b){c=c.hasIndex(b.colname);a.end(JSON.stringify({success:!0,indexed:c}))};
Admin.prototype.set_index=function(a,c,b){if(ensureNotEmpty(b.colname,a)&&ensureNotEmpty(b.index,a)){var d=b.colname;"true"==b.index?c.ensureIndex([d],function(b){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0,indexed:!0}))}):c.dropIndex([d],function(b){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0,indexed:!1}))})}};Admin.prototype.delete_all=function(a,c){deleteAll(c,getTables,function(b){if(filterError(b))return handleError(a,b);a.end(JSON.stringify({success:!0}))})};
Admin.prototype.import_database=function(a,c,b){var d=_tempFileDir+"/"+Util.getTempFileName(".csv");if(is_local_run){is_local_run=!1;var e=Job.create();a.end(JSON.stringify({success:!0,jobid:e.jobid}));execAdoUtility(["export",d,b.sql,b.conn],function(b,g){b?e.updateStatus(Status.failed,g):importCsv(a,c,",",d,e)})}else b=globalize.instance.processText("{{js.importDbApiNote}}",a.rs),a.end(JSON.stringify({success:!1,msg:b}))};
Admin.prototype.test_connection=function(a,c,b){logger.sendToParent("success");is_local_run?(is_local_run=!1,execAdoUtility(["test_connection",b.conn],function(b,c){b?a.end(JSON.stringify({success:!1,msg:c})):a.end(JSON.stringify({success:!0}))})):(c=globalize.instance.processText("{{js.connectDbApiNote}}",a.rs),a.end(JSON.stringify({success:!1,msg:c})))};
function enumerateRecords(a,c,b,d,e){void 0==e&&(e=0);var f=e+1;a.getRecords(c,f,f+BATCH_SIZE,function(f,h){!1!==b(f,e,h)&&null!=h&&0<h.length?enumerateRecords(a,c,b,d,e+BATCH_SIZE):d()})}function enumerateRecordsIndex(a,c,b,d,e){a.getKeysOfValue(c,b,d,e)}test_export("enumerateRecordsIndex",enumerateRecordsIndex);
function findDup(a,c,b,d){var e=0;a.hasIndex(c)?enumerateRecordsIndex(a,c,b,function(){e++;if(2<=e)return!0},function(){d(null,e)}):enumerateRecords(a,c,function(a,c,d){for(i in d)if(d[i]==b&&(e++,2<=e))return!1},function(){d(null,e)})}
Admin.prototype.check_item=function(a,c,b){var d=b.colname,e=a.rs;if(empty(d))a.end(JSON.stringify({success:!1,msg:e.invalidParameters}));else{var f=b.action;"is_end"==f?(b=parseInt(b.rowid,10),isNaN(b)&&a.end(JSON.stringify({success:!1,msg:e.invalidParameters})),isEnd(c,d,b,function(b,c){if(b)return handleError(a,b);c.success=!0;a.end(JSON.stringify(c))})):"has_dup"==f&&findDup(c,d,b.value,function(b,c){if(b)return handleError(a,b);a.end(JSON.stringify(2<=c?{success:!0,duplicated:!0}:{success:!0,
duplicated:!1}))})}};var diag;Admin.prototype.diag=function(a,c,b,d){diag||(diag=require("./diag").diag);diag(a,c,b,d)};function isEnd(a,c,b,d){if(0==b)return d(null,{add:!0,del:!0});if(0>b)return d(null,!1);b+=1;a.getRecords(c,b,b+2,function(a,b){if(a)return d(a,{add:!1,del:!1});if(b){if(1==b.length)return d(null,{add:!1,del:!0});if(2<=b.length)return d(null,{add:!1,del:!1})}d(null,{add:!0,del:!1})})}test_export("isEnd",isEnd);Admin.prototype.resource=function(a){a.write("var rs=");a.end(a.rs.js)};
function getCommand(a){a=a.match(/\/data\/([a-z_]*)[?/]?/);return null!=a?a[1]:null}
function changeToBuffered(a){function c(c,e){e|=DEFAULT_ENCODING;a.write(c);var f=0;for(i=0;i<b.length;i++)f+=Buffer.byteLength(b[i],e);a.writeHead(200,{"Content-Length":f});for(i=0;i<b.length;i++)a.realWrite(b[i],e);a.realEnd()}a.realEnd=a.end;a.realWrite=a.write;var b=[];a.write=function(a){void 0!=a&&b.push(a)};a.end=function(b,e){var f=!0;"object"==typeof b?(c(JSON.stringify(b),e),f=!1!=b.success):c(b,e);f&&a.emit("ended")};return a}
function changeToDirect(a){a.write=a.realWrite;a.end=a.realEnd;return a}function AdminHandler(a){this.options=a;this.admin=new Admin(a)}
AdminHandler.prototype.handle=function(a,c,b){var d=b.rs=c.context().getResource(),e=getCommand(a.path);logger.info("Execute: "+e);changeToBuffered(b);b.on("ended",function(){0<=e.search(_updateAPIs)&&changeMonitor.changed()});var f=null;a.search&&(f=a.search.lastIndexOf("?"),f=a.search.substr(0<=f?f+1:0),f=querystring.parse(f));"POST"==c.method&&(c.body&&(f=c.body),c.files&&c.files.fileToUpload&&(a=c.files.fileToUpload.path,f.path=a,logger.info(a)));void 0==f&&(f={});!e||"function"!=typeof this.admin[e]?
b.end(JSON.stringify({err:-1,msg:d.unknownCommand})):(logger.info(f),a=!0,0<=e.search(_updateAPIs)&&"None"!=_config.admin.authentication&&("Basic"==_config.admin.authentication?(a=c.headers.authorization,a||(logger.warning("no authorization header"),b.end(JSON.stringify({err:-1,msg:d.userPermissionNeeded}))),a=a.split(" "),a=(new Buffer(a[1],"base64")).toString().split(":")[0],getUser(a),a=isAdministrator(a)):"NTLM"==_config.admin.authentication&&(a=isAdministrator(c.ntlm.DomainName+"\\"+c.ntlm.UserName))),
a?(db=getDb(),this.admin[e](b,db.system,f,c)):b.end(JSON.stringify({err:-1,msg:d.js.userPermissionNeeded})))};exports.getHandler=function(a){initApiHttpServer();return new AdminHandler(a)};exports.getApiServerConfig=getApiServerConfig;exports.Job=Job;
