var path=require("path"),fs=require("fs"),cp=require("child_process"),log=require("../log"),common=require("./common"),enumMode=common.enumMode,changeMonitor=require("./notifier").changeMonitor,TIMEOUT=6E4;function Instance(a,b){"object"===typeof a?(this.port=a.port,this.name=a.name):(this.port=a,this.name=b);this.status="unknown";this.proc=null}
Instance.prototype.launch=function(a){function b(b){a&&!d&&(d=!0,a(b))}var c=["-port",this.port];this.name&&(c.push("-name"),c.push(this.name));logger.info("starting node instance with parameters",c);var d=!1,e=cp.fork(__dirname+"/../main.js",c,{});this.proc=e;this.status="starting";logger.info("launched child process, pid = "+e.pid);var g=!1,f=setTimeout(function(){if(!1===g){var a="Cannot launch process timely with info({0}).".format(c);logger.error(a);process.kill(e.pid);b(a)}else logger.info("doing nothing ...")},
TIMEOUT),h=this;e.on("message",function(a){if(Util.empty(a.status))"success"===a&&(g=!0,h.status="started",clearTimeout(f),b(null));else{var c=logger[a.status];"function"===typeof c&&(a="object"==typeof a?JSON.stringify(a):a,c("receive from child {0} message : {1}".format(e.pid,a)))}});e.on("exit",function(a){clearTimeout(f);h.status="stopped";errmsg="VTS Instance (port:{0}, name:{1}) exit with code {2}.".format(h.port,h.name,a);b(errmsg);logger.info(errmsg)})};Instance.prototype.status=function(){return this.status};
Instance.prototype.serialize=function(a){return!0===a?{port:this.port,name:this.name}:{port:this.port,name:this.name,status:this.status}};Instance.prototype.stop=function(){var a=this.proc;"stopped"===this.status;a&&(a.kill(),logger.info("process "+a.pid+" is killed"))};Instance.prototype.enableApiAccess=function(a,b){this.send({type:"enableAccess",value:!1!==a});b&&b()};Instance.prototype.send=function(a){this.proc&&this.proc.send(a)};
function ChildInstance(a){this.proc=a;var b=this;a.on("message",function(a){if(a&&a.type)switch(a.type){case "enableAccess":b.enableFunc?b.enableFunc(a.value):logger.error("enableFunc is not initialized"),changeMonitor.notifyConfig({started:a.value})}})}ChildInstance.prototype.enableAccess=function(a){this.enableFunc=a};InstanceManager.initInstance=function(a,b){return InstanceManager.Instance=new InstanceManager(a,b)};
function InstanceManager(a,b){logger.info("initialize InstanceManger with options",a);this.mode=a.mode;this.mode!==enumMode.Commander&&(this.port=a.port,this.name=a.name);this.apiAccessEnabled=!0;this.configPath=path.join(configure.dbPath,"instances.json");this.instances=this.readInstances();if(this.isDefaultInstance()){this.launchInstances(this.instances,b);var c=this;process.on("exit",function(){for(i in c.instances)c.instances[i].stop();process.exit(0)})}else b&&b(this)}
InstanceManager.prototype.readInstances=function(a){var b="";if(fs.existsSync(this.configPath))try{b=fs.readFileSync(this.configPath,"utf8")}catch(c){logger.error(c)}return readInstances(a,b)};InstanceManager.prototype.writeInstances=function(){var a=this.instances,b=[];for(i in a)b.push(a[i].serialize(!0));a=JSON.stringify(b,null,4);fs.writeFileSync(this.configPath,a,"utf8")};InstanceManager.prototype.commitSuicide=function(){process.exit(code=0)};
InstanceManager.prototype.isInInstancesList=function(a){if(!a)return!0;a=a[this.port];return void 0==a?!1:a!==this.name?(logger.warning("an instance with same port but different name: port="+this.port+" name="+this.name),!1):!0};InstanceManager.prototype.isDefaultInstance=function(){return this.mode===enumMode.Default};InstanceManager.prototype.launchInstances=function(a,b){var c=Object.size(a);if(0==c)b&&b(this);else{var d=this;for(i in a)a[i].launch(function(){c--;0===c&&b&&b(d)})}};
InstanceManager.prototype.addNewInstance=function(a,b){var c=null,c=a instanceof Instance?a:new Instance(a),d=this.instances,e=c.name,g=c.port;for(i in d){if(g==d[i].port&&e==d[i].name){b({code:"INST_STARTED",message:"Instance already started"});return}if(g==d[i].port||e==d[i].name){b({code:"PORT_IN_USE",message:"Port or name is in use"});return}}if(0<configure.maxInstancesAllowed&&Object.size(this.instances)>=configure.maxInstancesAllowed)b("exceed max allowed instance");else{var f=this;c.launch(function(a){if(Util.empty(a))c.enableApiAccess(f.apiAccessEnabled),
f.instances[g]=c,f.writeInstances(),b&&b();else if(b)b(a);else throw a;})}};InstanceManager.prototype.stopAllInstances=function(a){console.log("stoping all instances...");for(i in this.instances)this.instances[i].stop();this.instances={};this.writeInstances();a&&a(null)};
InstanceManager.prototype.stopInstance=function(a,b,c){var d=this.instances,e=!1;for(i in d)d[i].name===b&&(e=!0,d[i].stop());delete d[a];this.writeInstances();if(!1===e)if(errmsg="cannot find instance with port = {0}, name = {1}".format(a,b),c)c({code:"NOINSTANCE",message:errmsg});else throw error;else c&&c(null)};
InstanceManager.prototype.stopInstances=function(a,b){var c=[],d=this;0!==a.length&&function g(f){var h=a[f].name;d.stopInstance(a[f].port,h,function(a){a&&"NOINSTANCE"===a.code&&c.push(h);0>=f?0===c.length?b():b(c):g(f-1)})}(a.length-1)};InstanceManager.prototype.enableApiAccess=function(a,b){this.apiAccessEnabled=a;var c=this.instances;for(i in c)c[i].enableApiAccess(a);b&&b()};InstanceManager.prototype.listInstances=function(){var a=[],b=this.instances;for(i in b)a.push(b[i].serialize());return a};
InstanceManager.prototype.sendMessage=function(a){var b=this.instances;for(i in b)b[i].send(a)};
function readInstances(a,b){var c=[];try{Util.empty(b)||(c=eval("("+b+")"))}catch(d){}if(!0===a)return c;if(!(c instanceof Array))throw"invalid configure file, Array expected";var e={};for(i in c){var g=c[i],f=g.port,g=g.name||"";void 0!=e[f]&&logger.warning("instances with the same port {0} detected: ".format(f));var h=!0;for(pt in e)if(g==e[pt].name){h=!1;logger.warning('instances with duplicate name "{0}" detected'.format(g));break}h&&(e[f]=new Instance(f,g))}return e}exports.readInstances=readInstances;
exports.InstanceManager=InstanceManager;exports.ChildInstance=ChildInstance;
