var Mustache;
(function(n){"undefined"!==typeof module?module.exports=n:"function"===typeof define?define(n):Mustache=n})(function(){function n(a){return!RegExp.prototype.test.call(A,a)}function l(a){return'"'+a.replace(B,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"'}function r(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function t(a){return String(a).replace(/[&<>"'\/]/g,function(a){return C[a]})}function q(a){this.tail=this.string=a;this.pos=0}function i(a,c){this.view=
a;this.parent=c;this.clearCache()}function f(){this.clearCache()}function u(a,c){for(var b=['""'],d,g,e=0,h=a.length;e<h;++e)switch(d=a[e],d.type){case "#":case "^":g="#"===d.type?"_section":"_inverted";b.push("r."+g+"("+l(d.value)+", c, function (c, r) {\n  "+u(d.tokens,!0)+"\n})");break;case "{":case "&":case "name":g="name"===d.type?"true":"false";b.push("r._name("+l(d.value)+", c, "+g+")");break;case ">":b.push("r._partial("+l(d.value)+", c)");break;case "text":b.push(l(d.value))}b="return "+
b.join(" + ")+";";return c?b:new Function("c, r",b)}function v(a){if(2===a.length)return[RegExp(r(a[0])+"\\s*"),RegExp("\\s*"+r(a[1]))];throw Error("Invalid tags: "+a.join(" "));}function w(a,c){for(var c=c||e.tags,b=v(c),d=new q(a),g=[],f=[],h=!1,i=!1,j,k;!d.eos();){if(k=d.scanUntil(b[0]))for(var l=0,p=k.length;l<p;++l)if(j=k.charAt(l),n(j)?f.push(g.length):i=!0,g.push({type:"text",value:j}),"\n"===j){if(h&&!i)for(;f.length;)g.splice(f.pop(),1);else f=[];i=h=!1}if(!d.scan(b[0]))break;h=!0;j=d.scan(D)||
"name";d.scan(E);"="===j?(k=d.scanUntil(x),d.scan(x),d.scanUntil(b[1])):"{"===j?(k=RegExp("\\s*"+r("}"+c[1])),k=d.scanUntil(k),d.scan(F),d.scanUntil(b[1])):k=d.scanUntil(b[1]);if(!d.scan(b[1]))throw Error("Unclosed tag at "+d.pos);g.push({type:j,value:k});if("name"===j||"{"===j||"&"===j)i=!0;"="===j&&(c=k.split(G),b=v(c))}for(var m,b=0;b<g.length;++b)d=g[b],m&&"text"===m.type&&"text"===d.type?(m.value+=d.value,g.splice(b--,1)):m=d;h=m=[];b=[];for(f=0;f<g.length;++f)switch(d=g[f],d.type){case "#":case "^":d.tokens=
[];b.push(d);h.push(d);h=d.tokens;break;case "/":if(0===b.length)throw Error("Unopened section: "+d.value);h=b.pop();if(h.value!==d.value)throw Error("Unclosed section: "+h.value);h=0<b.length?b[b.length-1].tokens:m;break;default:h.push(d)}if(h=b.pop())throw Error("Unclosed section: "+h.value);return m}function y(a,c,b){return p.compilePartial(a,c,b)}function z(a,c,b){if(b)for(var d in b)y(d,b[d]);return p.render(a,c)}var e={name:"mustache.js",version:"0.5.1-dev",tags:["{{","}}"]};e.parse=w;e.clearCache=
function(){p.clearCache()};e.compile=function(a,c){return p.compile(a,c)};e.compilePartial=y;e.render=z;e.Scanner=q;e.Context=i;e.Renderer=f;e.to_html=function(a,c,b,d){a=z(a,c,b);if("function"===typeof d)d(a);else return a};var E=/\s*/,G=/\s+/,A=/\S/,x=/\s*=/,F=/\s*\}/,D=/#|\^|\/|>|\{|&|=|!/,s=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},B=/[\x00-\x2F\x3A-\x40\x5B-\x60\x7B-\xFF\u2028\u2029]/gm,C={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;",
"/":"&#x2F;"};e.isWhitespace=n;e.isArray=s;e.quote=l;e.escapeRe=r;e.escapeHtml=t;q.prototype.eos=function(){return""===this.tail};q.prototype.scan=function(a){return(a=this.tail.match(a))&&0===a.index?(this.tail=this.tail.substring(a[0].length),this.pos+=a[0].length,a[0]):null};q.prototype.scanUntil=function(a){var c=this.tail.search(a);switch(c){case -1:a=this.tail;this.pos+=this.tail.length;this.tail="";break;case 0:a=null;break;default:a=this.tail.substring(0,c),this.tail=this.tail.substring(c),
this.pos+=c}return a};i.make=function(a){return a instanceof i?a:new i(a)};i.prototype.clearCache=function(){this._cache={}};i.prototype.push=function(a){return new i(a,this)};i.prototype.lookup=function(a){var c=this._cache[a];if(!c){if("."===a)c=this.view;else for(var b=this;b;){if(0<a.indexOf("."))for(var d=a.split("."),g=0,c=b.view;c&&g<d.length;)c=c[d[g++]];else c=b.view[a];if(null!=c)break;b=b.parent}this._cache[a]=c}"function"===typeof c&&(c=c.call(this.view));return c};f.prototype.clearCache=
function(){this._cache={};this._partialCache={}};f.prototype.compile=function(a,c){"string"===typeof a&&(a=w(a,c));var b=u(a),d=this;return function(a){return b(i.make(a),d)}};f.prototype.compilePartial=function(a,c,b){this._partialCache[a]=this.compile(c,b);return this._partialCache[a]};f.prototype.render=function(a,c){var b=this._cache[a];b||(b=this.compile(a),this._cache[a]=b);return b(c)};f.prototype._section=function(a,c,b){a=c.lookup(a);switch(typeof a){case "object":if(s(a)){for(var d="",g=
0,e=a.length;g<e;++g)d+=b(c.push(a[g]),this);return d}return a?b(c.push(a),this):"";case "function":var b=b(c,this),f=this;return a.call(c.view,b,function(a){return f.render(a,c)})||"";default:if(a)return b(c,this)}return""};f.prototype._inverted=function(a,c,b){a=c.lookup(a);return null==a||!1===a||s(a)&&0===a.length?b(c,this):""};f.prototype._partial=function(a,c){var b=this._partialCache[a];return b?b(c,this):""};f.prototype._name=function(a,c,b){a=c.lookup(a);"function"===typeof a&&(a=a.call(c.view));
c=null==a?"":String(a);return b?t(c):c};var p=new f;return e}());
