var sys;try{sys=require("util")}catch(e$$10){sys=require("sys")}var events=require("events"),fs=require("fs"),csv=exports;function UserError(a,b){this.constructor.prototype=Error.prototype;Error.captureStackTrace(this,this.constructor);this.name=this.constructor.name;this.message=b;this.code=a}
var CsvReader=csv.CsvReader=function(a,b){var c=this;_setOptions(c,b);c.parsingStatus={rows:0,openRecord:[],openField:"",lastChar:"",quotedField:!1,commentedLine:!1};a&&(a.addListener("data",this.parse.bind(this)),a.addListener("error",this.emit.bind(this,"error")),a.addListener("end",this.end.bind(this)),c.pause=function(){a.pause();return c},c.resume=function(){a.resume();return c},c.destroy=function(){a.destroy();return c},c.destroySoon=function(){readstream.destroy();return c})};
sys.inherits(CsvReader,events.EventEmitter);
CsvReader.prototype.parse=function(a){var b=this.parsingStatus;0==b.openRecord.length&&65279===a.charCodeAt(0)&&(a=a.slice(1));for(var c=0;c<a.length;c++){var d=a.charAt(c);switch(d){case this.escapechar:case this.quotechar:if(b.commentedLine)break;if(d===this.quotechar&&!b.quotedField){b.quotedField=!0;break}if(d===this.escapechar&&b.quotedField){var e=a.charAt(c+1);if(this._isEscapable(e)){this._addCharacter(e);c++;break}}d===this.quotechar&&b.quotedField&&((e=a.charAt(c+1))&&"\r"!=e&&"\n"!=e&&
e!==this.separator&&!0!=this.nestedQuotes?this.emit("error",new UserError(10,"separator expected after a closing quote; found "+e)):b.quotedField=!1);break;case this.separator:if(b.commentedLine)break;b.quotedField?this._addCharacter(d):this._addField();break;case "\n":if(!b.quotedField&&"\r"===b.lastChar)break;case "\r":if(!b.quotedField&&("\r"===b.lastChar||"\n"===b.lastChar))break;b.commentedLine?b.commentedLine=!1:b.quotedField?this._addCharacter(d):(this._addField(),this._addRecord());break;
case this.commentchar:if(b.commentedLine)break;0===b.openRecord.length&&""===b.openField&&!b.quotedField?b.commentedLine=!0:this._addCharacter(d);default:if(b.commentedLine)break;this._addCharacter(d)}b.lastChar=d}};CsvReader.prototype.end=function(){var a=this.parsingStatus;a.quotedField?this.emit("error",new UserError(11,"Input stream ended but closing quotes expected")):(a.openField&&this._addField(),0<a.openRecord.length&&this._addRecord(),this.emit("end"))};
CsvReader.prototype._isEscapable=function(a){return a===this.escapechar||a===this.quotechar?!0:!1};CsvReader.prototype._addCharacter=function(a){this.parsingStatus.openField+=a};CsvReader.prototype._addField=function(){var a=this.parsingStatus;a.openRecord.push(a.openField);a.openField="";a.quotedField=!1};CsvReader.prototype.setColumnNames=function(a){this.columnNames=a};
CsvReader.prototype._addRecord=function(){var a=this.parsingStatus;if(this.columnsFromHeader&&0===a.rows)this.setColumnNames(a.openRecord);else if(null!=this.columnNames&&0<this.columnNames.length){for(var b={},c=0;c<this.columnNames.length;c++)b[this.columnNames[c]]=a.openRecord[c];this.emit("data",b)}else this.emit("data",a.openRecord);a.rows++;a.openRecord=[];a.openField="";a.quotedField=!1};
csv.createCsvFileReader=function(a,b){var b=b||{},c=fs.createReadStream(a,{flags:b.flags||"r"});c.setEncoding(b.encoding||"utf8");return new CsvReader(c,b)};csv.createCsvStreamReader=function(a,b){void 0===b&&"object"===typeof a&&(b=a,a=void 0);b=b||{};a&&a.setEncoding(b.encoding||"utf8");return new CsvReader(a,b)};
var CsvWriter=csv.CsvWriter=function(a,b){this.writeStream=a;b=b||{};_setOptions(this,b);this.encoding=b.encoding||"utf8";"function"===typeof a.setEncoding&&a.setEncoding(this.encoding);a.addListener("drain",this.emit.bind(this,"drain"));a.addListener("error",this.emit.bind(this,"error"));a.addListener("close",this.emit.bind(this,"close"))};sys.inherits(CsvWriter,events.EventEmitter);
CsvWriter.prototype.writeRecord=function(a){if(a){if(!Array.isArray(a))throw new UserError(12,"CsvWriter.writeRecord only takes an array as an argument");_writeArray(this,a)}};function _writeArray(a,b){for(var c=[],d=0;d<b.length;d++)0!=d&&c.push(a.separator),c.push(a.quotechar),_appendField(c,a,b[d]),c.push(a.quotechar);c.push("\r\n");a.writeStream.write(c.join(""),this.encoding)}
function _appendField(a,b,c){if("string"!==typeof c)if("undefined"!==typeof c&&null!==c)c=String(c);else{a.push("");return}for(var d=0;d<c.length;d++)(c.charAt(d)===b.quotechar||c.charAt(d)===b.escapechar)&&a.push(b.escapechar),a.push(c.charAt(d))}csv.createCsvFileWriter=function(a,b){var b=b||{flags:"w"},c=fs.createWriteStream(a,{flags:b.flags||"w"});return new CsvWriter(c,b)};csv.createCsvStreamWriter=function(a,b){return new CsvWriter(a,b)};
function _setOptions(a,b){b=b||{};a.separator=b.separator||",";a.quotechar=b.quote||'"';a.escapechar=b.escape||'"';a.commentchar=b.comment||"";a.columnNames=b.columnNames||[];a.columnsFromHeader=b.columnsFromHeader||!1;a.nestedQuotes=b.nestedQuotes||!1}function SeparatorDetector(a,b){var c=[];for(i=0;i<b.length;i++)c[i]=0;this.parsingStatus={separators:b,rowCount:a,row:0,quoted:!1,firstChar:!0,separatorsCount:c}}
SeparatorDetector.prototype.detect=function(a){console.log("detect");var b=-1,c=this.parsingStatus;if(c.row>=c.rowCount)return!0;for(65279===a.charCodeAt(0)&&(a=a.slice(1));c.row<c.rowCount&&b<a.length;){var d=a.charAt(++b);switch(d){case '"':c.quoted?'"'!=a.charAt(b+1)?c.quoted=!1:b++:c.firstChar&&(c.quoted=!0);break;case "\n":if(!c.quoted){++c.row;c.firstChar=!0;continue}break;case -1:c.row=c.rowCount;break;default:if(!c.quoted&&(d=c.separators.indexOf(d),-1!=d)){++c.separatorsCount[d];c.firstChar=
!0;continue}}c.firstChar&&(c.firstChar=!1)}return c.row>=c.rowCount?!0:!1};SeparatorDetector.prototype.getSeparator=function(){var a=this.parsingStatus,b=0;mcIndex=0;for(i in a.separatorsCount)b<a.separatorsCount[i]&&(b=a.separatorsCount[i],mcIndex=i);return 0==b?a.separators[0]:a.separators[mcIndex]};
csv.detectSeparator=function(a,b){var c=fs.createReadStream(a,{encoding:"utf8"}),d=new SeparatorDetector(1,[",",":",";","\t"," "]);c.addListener("data",function(a){console.log("data");d.detect(a)&&(c.pause(),c.destroy(),console.log("detected"))});c.addListener("error",function(a){logger.error("Error checking separator");logger.error(a);b(a)});c.addListener("end",function(){console.log("end")});c.addListener("close",function(){console.log("close");var a=d.getSeparator();console.log(d.parsingStatus);
b(null,a)})};
