var stdin=WScript.StdIn,stdout=WScript.StdOut,escapeOutput=!1,errorCodes={success:0,error_internal:1,error_invalid_operation:2,error_file_not_specified:3,error_file_not_found:4,error_table_not_specified:5,error_table_not_exist:6,error_table_already_exists:7,error_query_not_specified:8,error_connection_string_not_specified:9,error_cannot_connect_to_data_server:10,error_incorrect_file_format:11,error_dependencies_not_found:12,error_column_not_exist_in_dest_table:13,error_invalid_column_name:14,error_invalid_table_name:15},
strings={success:"success",error_internal:"Internal error",error_invalid_operation:"Invalid operation",error_file_not_specified:"File not specified",error_file_not_found:"File not found",error_table_not_specified:"Table not specified",error_table_not_exist:"Table does not exist",error_table_already_exists:"Table already exists",error_query_not_specified:"Query not specified",error_connection_string_not_specified:"Connection string not specified",error_cannot_connect_to_data_server:"Cannot connect to data server",
error_incorrect_file_format:"Incorrect file format",error_dependencies_not_found:"Dependencies not found",error_column_not_exist_in_dest_table:'Destination table exists, but it doesn\'t contain column "%1". Try dropping and reconstructing the table.',error_invalid_column_name:'Invalid column name "%1"',error_invalid_table_name:'Invalid table name "%1"'};
"function"!=typeof Function.prototype.bind&&(Function.prototype.bind=function(a){var b=this,c=Array.prototype.slice.call(arguments,1);return function(){b.apply(a,c.concat(Array.prototype.slice.call(arguments)))}});if("undefined"==typeof console||"undefined"==typeof console.log)var stdError=WScript.StdErr,console={log:function(a){WScript.Echo(escapeOutput?escape(a):a)},error:function(a){stdError.Write((escapeOutput?escape(a):a)+"\n")}};var asyncQueue=[];
function queueAsyncCall(a){asyncQueue.push(a)}function executeAsyncCall(){for(;asyncQueue.length;){var a=asyncQueue.shift();"function"==typeof a&&a()}}"function"!=typeof Array.isArray&&(Array.isArray=function(a){return a instanceof Array});if("undefined"==typeof exports)var exports={};
function require(a){var b={};switch(a){case "sys":case "util":b={inherits:function(a,b){function d(){}a.super_=b;d.prototype=b.prototype;a.prototype=new d}};break;case "events":a=function(){};b.EventEmitter=a;a.prototype.addListener=function(a,b){this._eventHandlers||(this._eventHandlers=[]);this._eventHandlers.push({name:a,callback:b})};a.prototype.emit=function(a,b){if(this._eventHandlers)for(var d in this._eventHandlers){var f=this._eventHandlers[d];f.name==a&&f.callback(b)}};break;case "fs":new ActiveXObject("Scripting.FileSystemObject");
b={createReadStream:function(a){a=a.toLowerCase();return"/c"===a||"-c"===a?new ReadStream:new ReadFileStream},createWriteStream:function(a){function b(){var d=new ActiveXObject("ADODB.Stream");d.Open();d.Charset="utf-8";this.write=function(a){d.WriteText(a)};this.destroy=function(){d.SaveToFile(a,2);d.Close()}}sys.inherits(b,events.EventEmitter);return new b}};break;default:throw Error("Cannot find library: "+a);}return b}var sys=require("sys"),events=require("events");
function ReadStream(){this._stream=stdin;this.paused=!1;var a=this;queueAsyncCall(function(){a.read()})}sys.inherits(ReadStream,events.EventEmitter);ReadStream.prototype.read=function(){for(;!this._stream.AtEndOfStream&&!paused;){try{var a=this._stream.ReadLine()+"\n"}catch(b){this.emit("error",b);return}a&&this.emit("data",a)}this.emit("end")};ReadStream.prototype.pause=function(){this.paused=!0};ReadStream.prototype.resume=function(){this.paused=!1;read()};ReadStream.prototype.setEncoding=function(){};
ReadStream.prototype.destroy=function(){this.paused=!0};
function ReadFileStream(){var a=new ActiveXObject("ADODB.Stream");a.Open();a.Charset="utf-8";a.LoadFromFile(path);var b=!1;this.read=function(){for(;!a.EOS&&!b;){try{var c=a.ReadText(4096)}catch(d){this.emit("error",d);return}c&&this.emit("data",c)}this.endEmitted||(this.emit("end"),this.endEmitted=!0)};var c=this;this.destroy=function(){this.destroyed||(a.Close(),this.destroyed=!0);b=!0;this.endEmitted||(this.emit("end"),this.endEmitted=!0)};queueAsyncCall(function(){c.read()})}
sys.inherits(ReadFileStream,ReadStream);function AdoWrapper(){}AdoWrapper.prototype.testConnection=function(a,b){try{var c=new ActiveXObject("ADODB.Connection");c.Open(a);c.Close()}catch(e){b(e,!1);return}b(null,!0)};
AdoWrapper.prototype.exportData=function(a,b,c,e){var d=new ActiveXObject("ADODB.Connection"),f=new ActiveXObject("ADODB.Recordset");d.Open(c);f.Open(b,d);c=[];for(b=0;b<f.fields.count;++b)field=f.fields(b),c.push(field.name);a.writeRecord(c);if(!f.EOF)for(f.MoveFirst();!f.EOF;){c=[];for(b=0;b<f.fields.count;++b){var h=f.fields(b).value;"unknown"===typeof h&&(h="");null==h?c.push(""):c.push(h)}a.writeRecord(c);f.MoveNext()}f.Close();d.Close();e()};
function buildError(a,b){var c=Error(b);c.code=a;return c}function isValidatIdentityName(a){return a.match(/^.*$/)}function validateColumnName(a){if(!isValidatIdentityName(a))throw buildError(errorCodes.error_invalid_column_name,strings.error_invalid_column_name.replace("%1",a));}function validateTableName(a){if(!isValidatIdentityName(a))throw buildError(errorCodes.error_invalid_table_name,strings.error_invalid_table_name.replace("%1",a));}
function escapeIdentityName(a){return a.replace(/\]/g,"]]")}function buildCreateTableCommand(a,b){if(!(b instanceof Array)||0>=b.length)throw Error("Cannot build create table command because columnDefs is empty");return"CREATE TABLE "+a+"("+b.join(",")+")"}function buildColumnDefinitions(a,b){var c=[],e;for(e in a){var d=a[e];c.push("["+escapeIdentityName(e)+"] "+(d>b?"[ntext]":"[nvarchar]("+d+")"))}return c}function escapeTableName(a){return a="["+escapeIdentityName(a)+"]"}
function createTable(a,b,c,e,d){try{console.log("status: {{Creating table}}...");var f=new ActiveXObject("ADODB.Command"),h=buildColumnDefinitions(c,e),g=buildCreateTableCommand(b,h);f.ActiveConnection=a;f.CommandText=g;f.CommandType=1;f.Execute();console.log("table created")}catch(j){d(j);return}d()}function createTableForCsv(a,b,c,e,d){b=csv.createCsvFileReader(b);getColumnSizes(b,e,function(b,e){for(var g in e)validateColumnName(g);console.log("creating table "+c);createTable(a,c,e,8E3,d)})}
function getColumnSizes(a,b,c){var e=null,d={};a.addListener("data",function(c){if(e)for(g=0;g<c.length;g++){if("string"==typeof c[g]){var h=e[g];d[h]=Math.max(c[g].length,d[h])}}else{e=c;for(var g=0;g<c.length;g++)d[e[g]]=50;if(b){g=0;for(name in d)d[name]=Math.max(b[g++],d[name]);console.log("column size constructed");a.destroy()}}});a.addListener("end",function(){c(null,d)})}
AdoWrapper.prototype.dropTable=function(a,b,c){try{var e=new ActiveXObject("ADODB.Connection"),d=new ActiveXObject("ADODB.Command");e.Open(b);d.ActiveConnection=e;d.CommandText="DROP TABLE "+a;d.CommandType=1;d.Execute();e.Close();c()}catch(f){c(f)}};
AdoWrapper.prototype.importData=function(a,b,c,e){var d=new ActiveXObject("ADODB.Recordset"),f=null;console.log("status:{{Start exporting data}}...");var h=0;a.addListener("data",function(a){if(f){try{d.AddNew(f,a)}catch(e){if(-2146825023==e.number)throw buildError(errorCodes.error_column_not_exist_in_dest_table,strings.error_column_not_exist_in_dest_table.replace("%1",f[i]));throw e;}++h;0==h%100&&console.log("status: {{Exporting row}} "+h+"...");d.Update()}else f=a,d.Open("select * from "+b,c,1,
3)});a.addListener("end",function(){d.close();console.log("status: {{Exporting row}} "+h+"...");e(null)})};AdoWrapper.prototype.importDataWithTableCreation=function(a,b,c,e,d){var f=new ActiveXObject("ADODB.Connection");f.Open(c);createTableForCsv(f,a,b,e,function(){var c=csv.createCsvFileReader(a);AdoWrapper.prototype.importData(c,b,f,d)})};for(var arguments=[],i=0;i<WScript.Arguments.length;i++)arguments.push(WScript.Arguments(i));
function printCommandLine(a){var b="";0<a.length&&(b=' "'+a.join('" "')+'"');console.log("cscript "+WScript.ScriptName+b)}printCommandLine(arguments);var fso=new ActiveXObject("Scripting.FileSystemObject");function csrequire(a){a=fso.OpenTextFile(a,1).ReadAll();eval(a);return exports}function getErrorExplainationString(a,b){var c=errorCodes[a].toString();return b.slice(0,b.length-c.length)+c+": "+strings[a]}
function getErrorsExplainationString(a,b){var c="",e;for(e in a)c+=getErrorExplainationString(e,b)+"\n";return c}
function printUsage(){console.log("Usage:\n  cscript "+WScript.ScriptName+" import <path> <table> <connection string>\n  cscript "+WScript.ScriptName+" export <path> <query> <connection string>\n  cscript "+WScript.ScriptName+" drop <table> <connection string>\n  cscript "+WScript.ScriptName+" test_connection <connection string>\n\nError Codes:\n"+getErrorsExplainationString(errorCodes,"      ")+"\nExamples:\ncscript "+WScript.ScriptName+' import "C:/import.csv" "test" "Provider=SQLOLEDB;Data Source=.;Integrated Security=SSPI;Initial Catalog=Northwind"\ncscript '+
WScript.ScriptName+' export "C:/export.csv" "SELECT * FROM Orders" "Provider=SQLOLEDB;Data Source=.;Integrated Security=SSPI;Initial Catalog=Northwind"\ncscript '+WScript.ScriptName+' drop "test" "Provider=SQLOLEDB;Data Source=.;Integrated Security=SSPI;Initial Catalog=Northwind"\ncscript '+WScript.ScriptName+' test_connection "Provider=SQLOLEDB;Data Source=.;Integrated Security=SSPI;Initial Catalog=Northwind"\n')}function print(a){for(var b in a)console.log(b+":"+a[b])}
function quit(a){a?(console.error(a.message),WScript.Quit(a.code)):WScript.Quit(errorCodes.success)}0==arguments.length&&(printUsage(),quit(null));var __dirname=fso.GetFile(WScript.ScriptFullName).ParentFolder;try{var csv=csrequire(__dirname+"/ya-csv.js")}catch(ex$$5){ex$$5.code=errorCodes.error_dependencies_not_found,handleError(ex$$5)}function handleError(a){a&&"undefined"==typeof a.code&&(a.code=errorCodes.error_internal);quit(a)}
for(i in arguments)"escape"==arguments[i].toLowerCase()&&(escapeOutput=!0);
switch(arguments[0]){case "help":printUsage();quit(null);break;case "import":try{2>arguments.length&&quit(buildError(errorCodes.error_file_not_specified,strings.error_file_not_specified));3>arguments.length&&quit(buildError(errorCodes.error_table_not_specified,strings.error_table_not_specified));4>arguments.length&&quit(buildError(errorCodes.error_connection_string_not_specified,strings.error_connection_string_not_specified));var path=arguments[1],table=arguments[2];validateTableName(table);var table=
escapeTableName(table),connectionString=arguments[3],sizes=null;if(5<=arguments.length)try{sizes=eval(arguments[4]),"Array"!=typeof sizes&&(sizes=null)}catch(e$$11){}var ado=new AdoWrapper;ado.importDataWithTableCreation(path,table,connectionString,sizes,handleError)}catch(ex$$6){handleError(ex$$6)}break;case "export":try{2>arguments.length&&quit(buildError(errorCodes.error_file_not_specified,strings.error_file_not_specified));3>arguments.length&&quit(buildError(errorCodes.error_query_not_specified,
strings.error_query_not_specified));4>arguments.length&&quit(buildError(errorCodes.error_connection_string_not_specified,strings.error_connection_string_not_specified));var path=arguments[1],query=arguments[2],connectionString=arguments[3],writer=csv.createCsvFileWriter(path);writer.addListener("close",function(){writer.writeStream.destroy()});(new AdoWrapper).exportData(writer,query,connectionString,function(a){writer.emit("close");handleError(a)})}catch(ex$$7){handleError(ex$$7)}break;case "drop":2>
arguments.length&&quit(buildError(errorCodes.error_table_not_specified,strings.error_table_not_specified));3>arguments.length&&quit(buildError(errorCodes.error_connection_string_not_specified,strings.error_connection_string_not_specified));table=escapeTableName(arguments[1]);connectionString=arguments[2];(new AdoWrapper).dropTable(table,connectionString,handleError);break;case "test_connection":2>arguments.length&&quit(buildError(errorCodes.error_connection_string_not_specified,strings.error_connection_string_not_specified));
connectionString=arguments[1];(new AdoWrapper).testConnection(connectionString,function(a){a&&(a.code=errorCodes.error_cannot_connect_to_data_server);quit(a)});break;default:quit(buildError(errorCodes.error_invalid_operation,strings.error_invalid_operation))}try{executeAsyncCall()}catch(ex$$8){handleError(ex$$8)};
