var fs=require("fs"),path=require("path"),http=require("http"),https=require("https"),querystring=require("querystring"),child_process=require("child_process"),csv=require("./ya-csv"),common=require("./common"),Util=common.Util,empty=Util.empty,globalize=common.Globalize,InstanceManager=require("./instmgr").InstanceManager,BATCH_SIZE=1E3,MAX_COLUMN_LENGTH=1E3,UTF8_BOM="\ufeff",DEFAULT_ENCODING="utf8",TIME_OUT=2E3,apiServer="./daemon",LAST_PAGE_NUMBER=9007199254740992,_tempFileDir=__dirname+"/Web/file",
_adoUtility=__dirname+"/adoUtility.js",_updateAPIs=/^(insert|edit|delete|clear|update|drop|import|retrieve|create|change)/,_config=configure,_apiHttpServer=null,_apiService=null,changeMonitor=require("./notifier").changeMonitor;test_export="undefined"!=typeof UNIT_TEST&&!0===UNIT_TEST?function(a,b){exports[a]=b}:function(){};var is_local_run=!1;exports.set_local_run="undefined"!=typeof SECU_LOCAL_RUN&&!0===SECU_LOCAL_RUN?function(){is_local_run=!0}:null;
function handleError(a,b){var c=console.trace(),c=void 0==c?"":"\r\n"+console.trace();logger.error(b+c);var c=a.rs,d;d=b.errmsg?b.errmsg:b.toString();0<=d.search("ECONNREFUSED")&&(d=c.js.loading);a&&a.end(JSON.stringify({success:!1,msg:d}))}function validateName(a){if(a.length>MAX_COLUMN_LENGTH)return!1;var b=/^[\w!#%$&amp;(-\/:-@\ u0080-\uFFFF]*$/;return!empty(a)&&b.test(a)&&/[^_.]/.test(a[0])&&/[^.]/.test(a[a.length-1])?!0:!1}
function filterError(a){return null!=a&&"ns not found"!=a.errmsg?a:null}
Date.prototype.format=function(a){var b={"M+":this.getMonth()+1,"d+":this.getDate(),"h+":this.getHours(),"m+":this.getMinutes(),"s+":this.getSeconds(),"q+":Math.floor((this.getMonth()+3)/3),S:this.getMilliseconds()};/(y+)/.test(a)&&(a=a.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length)));for(var c in b)RegExp("("+c+")").test(a)&&(a=a.replace(RegExp.$1,1==RegExp.$1.length?b[c]:("00"+b[c]).substr((""+b[c]).length)));return a};
function sendApiRequest(a,b,c){var d=querystring.stringify({request:JSON.stringify(a)}),e={port:b,host:"localhost",method:"post",path:"/redirect/",headers:{"content-type":"application/x-www-form-urlencoded","Content-Length":d.length}};!0==_config.admin.useSSL?(e.rejectUnauthorized=!1,e=https.request(e)):e=http.request(e);e.end(d);var f="";e.on("response",function(d){d.on("data",function(a){f+=a});d.on("end",function(){c(null,JSON.parse(f.toString()));0<=a.cmd.search(_updateAPIs)&&changeMonitor.changed(1,
b)})});e.on("error",function(a){c(a)})}function createApiRequest(a,b){return{cmd:a,version:"1.0",data:b}}function enableApiAccess(a,b,c){b=createApiRequest("servicestatus",{value:b});sendApiRequest(b,a,function(){c()})}function createApiServer(a){_apiHttpServer=child_process.execFile(apiServer,[a,configure.defaultDbName],function(){logger.info("api server started")});_apiHttpServer.on("close",function(){logger.info("api server exited")})}
function getTables(a,b){var c=createApiRequest("getAllColumns",null);sendApiRequest(c,a,function(a,c){b(null,c.data)})}test_export("getTables",getTables);function getUser(a){var b=_config.admin.users,a=a.toLowerCase();for(i in b)if(b[i].user.toLowerCase()==a)return b[i];return null}function getNtlmUser(a,b){var c=a.split("@");1<c.length&&(a=c[0],b=c.slice(1).join("@"));return b+"\\"+a}
function isAdministrator(a){var b=_config.admin.role.administrator,c=_config.admin.role.user;if(0==b.length&&0==c.length)return!0;var a=a.toLowerCase(),d;for(d in b)if(b[d].toLowerCase()==a)return!0;return!1}function clearColumn(a,b,c){b=createApiRequest("clearColumn",{column:b});sendApiRequest(b,a,function(a){c(a)})}test_export("clearColumn",clearColumn);
function countRows(a,b,c){var d=0,e={column:void 0==c?"":c};void 0==c?(e=createApiRequest("getAllColumnsSize",e),sendApiRequest(e,a,function(a,c){if(a)return b(a);var e={},e=c.data,h;for(h in e)d=Math.max(d,e[h]);b(null,d,e)})):(e=createApiRequest("getColumnSize",e),sendApiRequest(e,a,function(a,e){if(a)return b(a);var k={};d=k[c]=e.data;b(null,d,k)}))}test_export("countRows",countRows);
function refCount(a){var b=a;this.release=function(a){0==--b&&"function"==typeof a&&a()};this.addRef=function(){++b};this.releaseAll=function(a){b=0;"function"==typeof a&&a()}}
function unicodeProcess(a,b,c,d){logger.info('run process: cscript "'+b.join('" "')+'"');var a=child_process.spawn(a,b,c),e="";a.on("exit",function(a){logger.info("error "+a+":"+e);d(a,e)});a.stderr.setEncoding("utf8");a.stdout.setEncoding("utf8");a.stdout.on("data",function(a){process.stdout.write(unescape(a))});a.stdout.on("error",function(a){logger.error(a)});a.stderr.on("data",function(a){e+=unescape(a)});this.child=a;this.stdout=a.stdout;this.stdin=a.stdin;this.stderr=a.stderr}
unicodeProcess.prototype.write=function(a){a=new Buffer(a,"ucs2");this.child.stdin.write(a)};unicodeProcess.prototype.on=function(a,b){this.child.on(a,b)};test_export("unicodeProcess",unicodeProcess);function execAdoUtility(a,b){var c=[_adoUtility,"//Nologo"].concat(a).concat("escape"),c=new unicodeProcess("cscript",c,{},b);c.write("\r\n");return c}function isPortValid(a){var b=/^\d{1,5}$/;return!empty(a)&&0==a.search(b)?(a=parseInt(a,10),0<a&&65535>=a):!1}
function getEncoding(a){var b=DEFAULT_ENCODING;try{var c=new Buffer(2),d=fs.openSync(a,"r");fs.readSync(d,c,0,2,0);255==c[0]&&254==c[1]&&(b="ucs2")}finally{void 0!=d&&fs.closeSync(d)}return b}function findNonExists(a,b,c){var d={};for(i in a)d[a[i]]=a[i];for(i=b.length-1;0<=i;i--)void 0!=d[b[i]]&&(b.splice(i,1),c.splice(i,1));return b}test_export("importCsv",importCsv);
function importCsv(a,b,c,d,e,f,g){b=createApiRequest("import",{url:d,delimiter:c});sendApiRequest(b,a,function(a){"function"===typeof g&&g("");null==a?e.updateStatus(Status.succeeded,""):e.updateStatus(Status.failed,a)})}function getOneColumnData(a,b,c,d,e,f){0==d&&(d=1);c+=1;d=createApiRequest("getColumnRange",{column:b,start:c,end:c+d});sendApiRequest(d,a,function(a,c){if(a||null==c)return f(a);for(j in c.data){var d=parseInt(j,10);(empty(e[d])?e[d]={}:e[d])[b]=c.data[j]}f(null)})}
test_export("getOneColumnData",getOneColumnData);
function GridData(){function a(b,c){getTables(function(d,e){if(d)return c(d);var f=[],g=new refCount(e.length);if(0==e.length)return c(d,f,e);for(i in e)getOneColumnData(e[i],b,BATCH_SIZE,f,function(d){if(d)return c(d,f,e);g.release(function(){c(null,f,e);0!=f.length&&a(b+BATCH_SIZE,c)})})})}return{exportData:a,getMultiTablePage:function(a,c,d,e){var f=parseInt(d,10),g=parseInt(c,10);0>g&&(g=0);var k=e.rs,h=(g-1)*f,m=[];countRows(a,function(c,d,q){if(c)return handleError(e,c);if(0!=f){var p=Math.floor((d+
1)/f+(0<(d+1)%f?1:0));g=Math.min(g,p)}getTables(a,function(c,l){function r(){var a=h;for(i in m)m[i].__id=a++;e.end(JSON.stringify({rows:m,total:p,records:d,page:g,columns:s,countsPerColumn:q,timestamp:new Date}))}c&&handleError(e,c);if(null==l||0==l.length)e.end(JSON.stringify({rows:[{__id:0}],total:1,records:0,page:1,columns:["__id",k.newColumnName],timestamp:new Date}));else{var s=["__id"].concat(l),t=new refCount(l.length);for(i in l)getOneColumnData(a,l[i],h,f,m,function(a){if(a)return handleError(e,
a);t.release(r)})}})})}}}
function exportToFile(a,b){var c=null,d=0,e=!0,f={};(new GridData).exportData(0,function(g,k,h){if(g)return b(g);if(e){if(!h||0==h.length)return b(null,d,[]);for(i in h)f[h[i]]=50;c=fs.createWriteStream(a);c.write(UTF8_BOM);writer=csv.createCsvStreamWriter(c);writer.writeRecord(h);e=!1}if(!k||0==k.length)return c.end(),b(null,d,f);for(i in k){var g=[],m=k[i];for(j in h){var l=h[j],n=m[l];void 0==n&&(n="");g.push(n);f[l]=Math.max(n.length,f[l])}writer.writeRecord(g)}d+=k.length})}
test_export("exportToFile",exportToFile);function searchOneMatch(a,b,c,d,e,f,g,k){ref=new refCount(e.length);var h=[];if(0===e.length)return k(null,{match:h,found:!1}),!1;b=createApiRequest("search",{start:f+1,end:g+1,value:d});sendApiRequest(b,a,function(a,b){if(a)return k(a,!1,null);null!=b&&null!=b.data?(h[0]={index:b.data.index},k(null,{match:h,found:!0})):(logger.info("no more records"),k(null,{match:h,found:!1}))})}
RegExp.escape=function(a){return a.replace(RegExp("[.*+?|()\\[\\]{}\\\\]","g"),"\\$&")};function Admin(a){this.options=a}test_export("Admin",Admin);function subscribeUpdate(a){setInterval(function(){var b={port:a,host:"localhost",method:"get",path:"/stat/update/"};!0==_config.admin.useSSL?(b.rejectUnauthorized=!1,b=https.request(b)):b=http.request(b);b.end();b.on("response",function(b){b.on("data",function(b){0<b&&changeMonitor.changed(b,a)})})},3E3)}
Admin.prototype.set_port=function(a){this.options.port=a};
Admin.prototype.get_settings=function(a){var b={};b.auth=_config.admin.authentication;b.started=!1;b.autoRefreshGrid=this.options.autoRefreshGrid;b.name=this.options.name;b.mode=this.options.mode;b.mode==common.enumMode.NamedInstance?(b.port=this.options.port,b.adminPort=configure.adminPort):b.port=_config.defaultApiPort;var c=createApiRequest("getSettings",{});sendApiRequest(c,b.port,function(c,e){void 0!=e&&(b.name=e.data.name,b.started=e.data.status,subscribeUpdate(b.port));a.end(JSON.stringify({success:!0,
settings:b}))})};Admin.prototype.get_count=function(a,b){countRows(this.options.port,function(b,d){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0,count:d}))},b.colname)};function ensureNotEmpty(a,b){return empty(a)?(b.end(JSON.stringify({success:!1,msg:b.rs.invalidParameters})),!1):!0}
Admin.prototype.insert_cell=function(a,b){var c=parseInt(b.idx,10),d=b.key,e=b.value,f={success:!0};if(ensureNotEmpty(d)){var g={};g[d]=e;0==c?(c={"new":g},c=createApiRequest("insert",c),sendApiRequest(c,this.options.port,function(b){if(b)return handleError(a,b);a.end(JSON.stringify(f))})):(c={"new":g,index:c+1},c=createApiRequest("update",c),sendApiRequest(c,this.options.port,function(b){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0,updated:new Date}))}))}};
Admin.prototype.edit_cell=function(a,b){var c=a.rs;if("edit"!=b.oper)a.end(JSON.stringify({success:!1,msg:c.invalidParameters}));else{var d=parseInt(b.id,10),e=b.key;empty(e)?a.end(JSON.stringify({success:!1,msg:c.invalidParameters})):(c={},c[e]=b.value,d=createApiRequest("update",{"new":c,index:d+1}),sendApiRequest(d,this.options.port,function(b){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0,updated:new Date}))}))}};Admin.prototype.ensure_index=function(){};
Admin.prototype.search=function(a,b){var c=b.q;empty(c);var d=parseInt(b.start,10),e=parseInt(b.end,10);if(isNaN(d)||!isFinite(d))d=0;var f=(new Date).getTime(),g=this.options.port;getTables(g,function(b,h){if(b)return handleError(a,b);searchOneMatch(g,f,a,c,h,d,e,function(b,c){if(b)return handleError(a,b);c.success=!0;a.end(JSON.stringify(c))})})};function saveSetting(){}test_export("saveSetting",saveSetting);
function updateConfig(a,b){var c=__dirname+"/../configure.json",d=fs.readFileSync(c,"utf8"),a=parseInt(a);isNaN(a)||(d=d.replace(/"defaultApiPort":\s*\d+,/,'"defaultApiPort": '+a+","),d=d.replace(/"defaultStart":\s*.+,/,'"defaultStart": '+b+","));fs.writeFileSync(c,d)}
Admin.prototype.start_server=function(a,b){function c(){ret={success:!0,started:f};a.end(JSON.stringify(ret));changeMonitor.notifyConfig({started:f})}var d=a.rs;if(empty(b.start)||"true"!=b.start&&"false"!=b.start||"true"==b.start&&!isPortValid(b.port))a.end(JSON.stringify({success:!1,msg:d.invalidPort}));else{if(this.options.mode===common.enumMode.NamedInstance)return handleError(a,"cannot call this command from a named instance");var e=parseInt(b.port,10),f="true"==b.start;this.start=f;d=InstanceManager.Instance.instances;
for(i in d)enableApiAccess(d[i].port,f,function(){logger.info("change access for script")});!0==f?e!=this.options.port?(_config.defaultApiPort=e,this.options.port=e,_apiHttpServer.kill(),createApiServer(e,setTimeout(function(){enableApiAccess(e,!0,function(){c();updateConfig(e,f);logger.info("change access for script")})},3E3))):enableApiAccess(e,f,function(){c();updateConfig(e,f);logger.info("change access for script")}):(e=this.options.port,enableApiAccess(e,f,function(){c();updateConfig(e,f);logger.info("change access for script")}))}};
Admin.prototype.start_instance=function(a,b){var c=a.rs,d=b.port,e=b.name;if(!isPortValid(b.port))return a.end(JSON.stringify({success:!1,msg:c.invalidPort})),!1;var f=this;InstanceManager.Instance.addNewInstance({port:d,name:e},function(b){Util.empty(b)||(b.code&&("INST_STARTED"===b.code?a.end(JSON.stringify({success:!1,msg:c.InstanceStarted})):"PORT_IN_USE"===b.code&&a.end(JSON.stringify({success:!1,msg:c.PortNameInUse}))),a.end(JSON.stringify({success:!1,msg:b})));setTimeout(function(){enableApiAccess(d,
f.start,function(){a.end(JSON.stringify({success:!0,msg:c.InstanceAddSucceed}))})},3E3)})};
Admin.prototype.stop_instance=function(a,b){var c=a.rs,d=InstanceManager.Instance,e=d.instances,f=parseInt(b.port,10),g=b.name;isNaN(f)&&Util.empty(g)&&a.end(JSON.stringify({success:!1,msg:c.invalidParameters}));var k=!1;for(i in e)if(!Util.empty(g)&&e[i].name===g||e[i].port==f){var k=!0,h=e[i];d.stopInstance(h.port,h.name,function(b){b?"NOINSTANCE"===b.code?a.end(JSON.stringify({success:!1,msg:c.cannotFindInstance.format(h.name)})):a.end(JSON.stringify({success:!1,msg:b})):a.end(JSON.stringify({success:!0,
msg:c.InstanceStoppedSuccessful}))})}k||a.end(JSON.stringify({success:!1,msg:c.cannotFindInstance.format(g)}))};
Admin.prototype.stop_instances=function(a,b){var c=a.rs,d=InstanceManager.Instance,e=JSON.parse(b.instances);null==e&&a.end(JSON.stringify({success:!1,msg:c.invalidParameters}));var f=[];for(i in e){var g=e[i].split(":");2!==g.length&&a.end(JSON.stringify({success:!1,msg:c.invalidParameters}));f.push({port:g[1],name:g[0]})}var k=[];0===f.length?a.end(JSON.stringify({success:!0,msg:c.InstanceStoppedSuccessful})):d.stopInstances(f,function(b){Util.empty(b)?a.end(JSON.stringify({success:!0,msg:c.InstanceStoppedSuccessful})):
b instanceof Array&&(k=b,a.end(JSON.stringify({success:!1,msg:c.cannotFindInstance.format(k.join(" "))})))})};Admin.prototype.stop_all_instances=function(a){var b=a.rs;InstanceManager.Instance.stopAllInstances(function(){a.end(JSON.stringify({success:!0,msg:b.InstanceStoppedSuccessful}))})};Admin.prototype.list_instances=function(a){var b=InstanceManager.Instance.listInstances();a.end(JSON.stringify({success:!0,instances:b}))};
Admin.prototype.auth=function(a,b,c){if("Basic"==_config.admin.authentication)if(c=c.headers.authorization){var c=c.split(" "),c=(new Buffer(c[1],"base64")).toString().split(":")[0],b=getUser(c),d=isAdministrator(c);a.end(JSON.stringify({success:!0,user:c,display:b&&b.display?b.display:c,isAdmin:d}))}else logger.warning("no authorization header"),a.end(JSON.stringify({success:!1}));else"NTLM"==_config.admin.authentication?(b=getNtlmUser(c.ntlm.UserName,c.ntlm.DomainName),d=isAdministrator(b),a.end(JSON.stringify({success:!0,
user:c.ntlm.UserName,display:c.ntlm.UserName,isAdmin:d}))):a.end(JSON.stringify({success:!1}))};Admin.prototype.get_page=function(a,b){(new GridData).getMultiTablePage(this.options.port,b.page,b.rows,a)};
function exportCsvFile(a,b,c,d,e){function f(f){var k=[];for(name in d.columnSizes)k.push(d.columnSizes[name]);var h=d.job;execAdoUtility(["import",a,b,c,JSON.stringify(k)],function(b,c){if(0!=b){var h=d.rs.adoErrors?d.rs.adoErrors[b]:"";empty(h)&&(h=d.rs.errorOccurred+":<br />"+(f?f+"\n":"")+c);e(h)}else e(null);d.deleteFile&&fs.unlink(a,function(){})}).stdout.on("data",function(a){data=unescape(a);0==data.indexOf("status:")&&(data=data.substring(7),h&&h.updateStatus(null,data))})}d.dropTable?execAdoUtility(["drop",
b,c],function(a,b){var c=0!=a?b:null;console.log("table dropped");f(c)}):f()}test_export("exportCsvFile",exportCsvFile);var _importingOrExporting=!1;
Admin.prototype.export_database=function(a,b){var c=_tempFileDir+"/"+Util.getTempFileName(".csv"),d=a.rs;if(is_local_run)if(is_local_run=!1,!0==_importingOrExporting)a.end(JSON.stringify({success:!1,msg:d.importExportInProgress}));else{_importingOrExporting=!0;var e=Job.create();a.end(JSON.stringify({success:!0,jobid:e.jobid}));try{exportToFile(c,function(f,g,m){0==g&&0==m?(_importingOrExporting=!1,e.updateStatus(Status.failed,d.noDataToExport)):exportCsvFile(c,b.tbl,b.conn,{deleteFile:!0,dropTable:"true"===
b.droptbl,columnSizes:m,job:e,rs:a.rs},function(a){_importingOrExporting=!1;a?e.updateStatus(Status.failed,a):e.updateStatus(Status.succeeded,g)})})}catch(f){_importingOrExporting=!1}}else{var g=globalize.instance.processText("{{js.exportDbApiNote}}",a.rs);a.end(JSON.stringify({success:!1,msg:g}))}};
Admin.prototype.job_status=function(a,b){var c=parseInt(b.jobid,10);if(-1==c)return a.end(JSON.stringify({success:!1,error:a.rs.invalidParameters}));c=Job.AllJobs[c];if(empty(c))return a.end(JSON.stringify({success:!1,error:a.rs.invalidParameters}));"true"===b.deletejob&&c.unregister();var d=globalize.instance.processText(c.msg,a.rs);a.end(JSON.stringify({success:!0,job:{status:c.status,msg:d}}))};function Job(){this.jobid=this.register()}Job.AllJobs={};Job.seed=0;Job.create=function(){return new Job};
Job.prototype.register=function(){var a=Job.seed++;Job.AllJobs[a]=this;this.created=new Date;this.status=Status.inProgress;return a};var Status={inProgress:1,failed:2,succeeded:3};Job.prototype.updateStatus=function(a,b){empty(a)||(this.status=a);this.lastUpdated=new Date;void 0!=b&&(this.msg=b)};Job.prototype.unregister=function(){delete Job.AllJobs[this.jobid]};
Admin.prototype.import_csv=function(a,b,c){var d=b.separator||"auto",e=b.path,f=!1!==b.deleteFile,b=__dirname+"/Web/file/",g=this.options.port,k=function(b){var d=Job.create();"function"===typeof c?importCsv(g,a,b,e,d,f,c):(importCsv(g,a,b,e,d,f),a.end(JSON.stringify({success:!0,jobid:d.jobid})))},h=path.basename(e);empty(h)||!validateName(h)||""!==path.relative(b,path.dirname(e))?(a.setHeader("Content-Type","application/json"),a.end(JSON.stringify({success:!1,msg:a.rs.cannotAccessFile.format(e)}))):
fs.exists(b+path.basename(e),function(b){if(b){b=fs.readFileSync(e,"utf8");65279===b.charCodeAt(0)&&(b=b.slice(1),fs.writeFileSync(e,b));if("\\t"==d)d="\t";else if("auto"==d){csv.detectSeparator(e,function(b,c){if(b)logger.error(b),handleError(a,b);else if(null==c){var d=a.rs;logger.warning("Cannot detect separator");a.end(JSON.stringify({success:!1,msg:d.cannotDetectSeparator}))}else k(c)});return}k(d)}else a.setHeader("Content-Type","application/json"),a.end(JSON.stringify({success:!1,msg:a.rs.cannotAccessFile.format(e)}))})};
Admin.prototype.export_csv=function(a){var b="VTS data "+(new Date).format("yyyy-MM-dd(hh_mm_ss)")+".csv",c=createApiRequest("export",{url:b});sendApiRequest(c,this.options.port,function(c){c?(a.setHeader("content-type","text/html"),a.end(c)):(fs.readFile(b,"utf8",function(c,d){c?(a.setHeader("content-type","text/html"),a.end(c)):(a.setHeader("Content-Type","application/binary"),a.setHeader("Content-Disposition","attachment;filename="+b),a.end(d))}),fs.unlink(b,function(){}))})};
Admin.prototype.delete_data=function(a,b){var c=b.colname,d=!0;empty(c)&&(d=!1);var e=parseInt(b.rowid,10);0<=e||(d=!1);d?(c=createApiRequest("retrieve",0==e?{columns:[c]}:{columns:[c],condition:!0}),sendApiRequest(c,this.options.port,function(b){if(b)return handleError(b);a.end(JSON.stringify({success:!0}))})):a.end(JSON.stringify({success:!1,msg:a.rs.invalidParameters}))};
Admin.prototype.import_local_file=function(a,b){var c=b.name;this.options.port=b.port;empty(c)||!validateName(c)?a.end(JSON.stringify({success:!1,msg:a.rs.invalidMessage})):(b.path=__dirname+"/Web/file/"+c,this.import_csv(a,b,function(b){a.end(JSON.stringify({success:empty(b),msg:b}))}))};
Admin.prototype.import_sample=function(a,b){var c=b.name;if(empty(c)||!validateName(c))a.end(JSON.stringify({success:!1,msg:a.rs.invalidMessage}));else{var c=__dirname+"/../samples/"+c+".csv",d=Util.getTempFileName(c);b.path=__dirname+"/Web/file/"+d;var e=this;Util.copyFile(c,b.path,function(c){Util.empty(c)?(b.deleteFile=!0,e.import_csv(a,b)):logger.error(c)})}};
Admin.prototype.list_samples=function(a){fs.readdir(__dirname+"/../samples",function(b,c){if(b)return a.end(JSON.stringify({success:!1,msg:b}));var d=[];for(i in c)if(0<=c[i].search(/\.csv$/ig)){var e=c[i].replace(/\.csv/ig,""),f=globalize.instance.processText("{{ page."+e+" }}",a.rs);if(f==="{{ page."+e+" }}"||""===f)f=e;d.push({value:e,display:f})}a.end(JSON.stringify({success:!0,list:d}))})};
Admin.prototype.update_column=function(a,b){var c=a.rs,d={success:!0};if(empty(b.colname)||!validateName(b.colname))a.end(JSON.stringify({success:!1,msg:c.invalidColumnName}));else{var e=b.colname,f=empty(b.curname)?"":b.curname,g=b.type,k=createApiRequest("getAllColumns",null);sendApiRequest(k,this.options.port,function(b,d){for(i in d.data)if(e==d.data[i])return handleError(a,c.columnExists)});if("add"==g)f=b.left,g={columns:[e],start:f,condition:!0},""==f&&(g={columns:[e],condition:!0}),k=createApiRequest("createColumn",
g),sendApiRequest(k,this.options.port,function(b){if(b)return handleError(a,b);a.end(JSON.stringify(d))});else if("edit"==g){empty(f)&&a.end(JSON.stringify(retInvalid));if(f==e)return handleError(a,c.columnExists);g={columns:[f],NewValue:e};k=createApiRequest("change",g);sendApiRequest(k,this.options.port,function(b){if(b)return handleError(a,b);a.end(JSON.stringify(d))})}else a.end(JSON.stringify({success:!1,msg:c.invalidParameters}))}};
Admin.prototype.clear_column=function(a,b){var c=createApiRequest("clearColumn",{columns:[b.colname]});sendApiRequest(c,this.options.port,function(b){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0}))})};Admin.prototype.delete_column=function(a,b){var c=createApiRequest("delete",{columns:[b.colname]});sendApiRequest(c,this.options.port,function(b){if(b)return handleError(a,b);a.end(JSON.stringify({success:!0}))})};
Admin.prototype.col_info=function(a){var b=configure.autoCreateIndexedColumn;void 0!=this.options.indexed&&(b=this.options.indexed);a.end(JSON.stringify({success:!0,indexed:b}))};Admin.prototype.set_index=function(a,b){ensureNotEmpty(b.colname,a)&&ensureNotEmpty(b.index,a)&&(this.options.indexed="true"==b.index,this.options.indexed?a.end(JSON.stringify({success:!0,indexed:!0})):a.end(JSON.stringify({success:!0,indexed:!1})))};
Admin.prototype.delete_all=function(a){var b=createApiRequest("delete",null);sendApiRequest(b,this.options.port,function(b){if(filterError(b))return handleError(a,b);a.end(JSON.stringify({success:!0}))})};Admin.prototype.delete_instance=function(a,b){this.options.port=b.port;var c=createApiRequest("delete",null);sendApiRequest(c,this.options.port,function(b){if(filterError(b))return handleError(a,b);a.end(JSON.stringify({success:!0}))})};
Admin.prototype.import_database=function(a,b){var c=_tempFileDir+"/"+Util.getTempFileName(".csv");if(is_local_run){is_local_run=!1;var d=Job.create();a.end(JSON.stringify({success:!0,jobid:d.jobid}));execAdoUtility(["export",c,b.sql,b.conn],function(b,e){b?d.updateStatus(Status.failed,e):importCsv(port,a,",",c,d)})}else{var e=globalize.instance.processText("{{js.importDbApiNote}}",a.rs);a.end(JSON.stringify({success:!1,msg:e}))}};
Admin.prototype.test_connection=function(a,b){logger.sendToParent("success");if(is_local_run)is_local_run=!1,execAdoUtility(["test_connection",b.conn],function(b,c){b?a.end(JSON.stringify({success:!1,msg:c})):a.end(JSON.stringify({success:!0}))});else{var c=globalize.instance.processText("{{js.connectDbApiNote}}",a.rs);a.end(JSON.stringify({success:!1,msg:c}))}};function findDup(a,b,c,d){b=createApiRequest("checkdup",{columns:[b],value:c});sendApiRequest(b,a,function(a,b){d(a,b.data)})}
Admin.prototype.check_item=function(a,b){var c=b.colname,d=a.rs;if(empty(c))a.end(JSON.stringify({success:!1,msg:d.invalidParameters}));else{var e=b.action;"is_end"==e?(e=parseInt(b.rowid,10),isNaN(e)&&a.end(JSON.stringify({success:!1,msg:d.invalidParameters})),isEnd(this.options.port,c,e,function(b,c){if(b)return handleError(a,b);c.success=!0;a.end(JSON.stringify(c))})):"has_dup"==e&&findDup(this.options.port,c,b.value,function(b,c){if(b)return handleError(a,b);a.end(JSON.stringify(1==c?{success:!0,
duplicated:!0}:{success:!0,duplicated:!1}))})}};var diag;Admin.prototype.diag=function(a,b,c){diag||(diag=require("./diag").diag);diag(a,b,c)};function isEnd(a,b,c,d){if(0==c)return d(null,{add:!0,del:!0});if(0>c)return d(null,!1);b=createApiRequest("getColumnSize",{column:b});sendApiRequest(b,a,function(a,b){if(a)return handleError(null,a);if(0<c&&c<b.data-1)return d(null,{add:!1,del:!1});if(c==b.data-1)return d(null,{add:!1,del:!0});d(null,{add:!0,del:!1})})}test_export("isEnd",isEnd);
Admin.prototype.resource=function(a){a.write("var rs=");a.end(a.rs.js)};function getCommand(a){a=a.match(/\/data\/([a-z_]*)[?/]?/);return null!=a?a[1]:null}
function changeToBuffered(a){function b(b,e){e|=DEFAULT_ENCODING;a.write(b);var f=0;for(i=0;i<c.length;i++)f+=Buffer.byteLength(c[i],e);a.writeHead(200,{"Content-Length":f});for(i=0;i<c.length;i++)a.realWrite(c[i],e);a.realEnd()}a.realEnd=a.end;a.realWrite=a.write;var c=[];a.write=function(a){void 0!=a&&c.push(a)};a.end=function(c,e){var f=!0;"object"==typeof c?(b(JSON.stringify(c),e),f=!1!=c.success):b(c,e);f&&a.emit("ended")};return a}
function changeToDirect(a){a.write=a.realWrite;a.end=a.realEnd;return a}function AdminHandler(a){this.options=a;this.admin=new Admin(a)}AdminHandler.prototype.change_options=function(a,b){this.options.mode=a;this.admin.set_port(b)};
AdminHandler.prototype.handle=function(a,b,c){var d=c.rs=b.context().getResource(),e=getCommand(a.path);logger.info("Execute: "+e);changeToBuffered(c);var f=null;a.search&&(f=a.search.lastIndexOf("?"),f=a.search.substr(0<=f?f+1:0),f=querystring.parse(f));"POST"==b.method&&(b.body&&(f=b.body),b.files&&b.files.fileToUpload&&(a=b.files.fileToUpload.path,f.path=a,logger.info(a)));void 0==f&&(f={});if(!e||"function"!=typeof this.admin[e])c.end(JSON.stringify({err:-1,msg:d.unknownCommand}));else if(logger.info(f),
a=!0,0<=e.search(_updateAPIs)&&"None"!=_config.admin.authentication&&("Basic"==_config.admin.authentication?(a=b.headers.authorization,a||(logger.warning("no authorization header"),c.end(JSON.stringify({err:-1,msg:d.userPermissionNeeded}))),a=a.split(" "),a=(new Buffer(a[1],"base64")).toString().split(":")[0],getUser(a),a=isAdministrator(a)):"NTLM"==_config.admin.authentication&&(a=isAdministrator(b.ntlm.DomainName+"\\"+b.ntlm.UserName))),a)this.admin[e](c,f,b);else c.end(JSON.stringify({err:-1,msg:d.js.userPermissionNeeded}))};
exports.getHandler=function(a){return new AdminHandler(a)};exports.createApiServer=createApiServer;exports.Job=Job;
